<section class="static-content accessibility-help">
	<div class="title-wrap">
		<h1 class="title">ACCESSIBILITY HELP</h1>
		<h2 class="sub-title">Hearing Impaired</h2>
	</div>
	<div class="tab-wrap">
		<ul>
			<li>
				<a href="#">Keyboard Controls</a>
			</li>
			<li>
				<a href="#">Visually Impaired</a>
			</li>
			<li class="active">
				<a href="#">Hearing Impaired</a>
			</li>
		</ul>
	</div>
	<div class="overview-wrap">
		<div class="overview-list">
			<p class="title">In this section, you can find how to:</p>
			<ul class="has-bullet">
				<li>
					<a href="#adjust_volume">Adjust System Volume</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="how-to-wrap">
		<div class="how-to-block" id="adjust_volume">
			<div class="block-title">
				<h3 class="title">Adjust System Volume</h3>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/adjust_volume_1.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">1</span> Select ‘Hardware and Sound’ in the control panel.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/adjust_volume_2.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">2</span> Select ‘Adjust System Volume'.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/adjust_volume_3.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">3</span> Use the volume control to increase or decrease sound to the desired level.</p>
				</div>
			</div>
		</div>
	</div>
</section>