<section class="static-content accessibility-help">
	<div class="title-wrap">
		<h1 class="title">ACCESSIBILITY HELP</h1>
		<h2 class="sub-title">Keyboard Controls</h2>
	</div>
	<div class="tab-wrap">
		<ul>
			<li class="active">
				<a href="#">Keyboard Controls</a>
			</li>
			<li>
				<a href="#">Visually Impaired</a>
			</li>
			<li>
				<a href="#">Hearing Impaired</a>
			</li>
		</ul>
	</div>
	<div class="overview-wrap">
		<div class="overview-desc desc">
			<p>This page explains how to use accessibility features offered by Windows, Web Browsers, or LG.COM in order to help users to use LG.COM in a more accessible way. <br>If you are using a keyboard or assistive technologies instead of using a mouse, please select <strong>‘Keyboard Controls’</strong> tab. If you can’t see very well, please select <strong>‘Visually Impaired’</strong> tab.  If you can’t hear very well, please select <strong>‘Hearing Impaired’</strong> tab.</p>
		</div>
		<div class="overview-list">
			<p class="title">In this section, you can find how to:</p>
			<ul class="has-bullet">
				<li>
					<a href="#bypass_block">Use Bypass Blocks</a>
				</li>
				<li>
					<a href="#date_picker">Use Date-picker</a>
				</li>
				<li>
					<a href="#slider">Use Slider</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="how-to-wrap">
		<div class="how-to-block" id="bypass_block">
			<div class="block-title">
				<h3 class="title">Use Bypass Blocks</h3>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/bypass_block_1.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">1</span> Once you are on LG.com, press <strong>Tab</strong> on your keyboard. You will see a link that reads “Skip to Contents”. Press <strong>Enter</strong> to directly go to main content.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/bypass_block_2.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">2</span> Press <strong>Tab</strong> on your keyboard twice on LG.com. A link that reads “Skip to Accessibility Help” will appear. Press <strong>Enter</strong> to directly go to accessibility help.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/bypass_block_3.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">3</span> Press <strong>Tab</strong> on your keyboard in the navigation area. A link that reads “Skip to Next Menu” will appear. Press <strong>Enter</strong> to directly go to the next menu.</p>
				</div>
			</div>
		</div>
		<div class="how-to-block" id="date_picker">
			<div class="block-title">
				<h3 class="title">Use Date Picker</h3>
			</div>
			<div class="row">
				<div class="image has-border">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/date_picker_1.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">1</span> Calendar layer appears whenever an input box with calendar icon is focused. Press <strong>Tab</strong> or <strong>Shift + Tab</strong> on your keyboard to move back and forth in the calendar layer.</p>
					<p><span class="bg-circle">2</span> If the date is not selected once the calendar layer is opened and the arrow key is activated, the calendar will be set to ‘today’s date’ before another date is selected.</p>
					<p><span class="bg-circle">3</span> With the calendar layer opened, press <strong>Shift + Arrow keys</strong> for a monthly view of the calendar.</p>
					<p><span class="bg-circle">4</span> With the calendar layer opened, press <strong>Ctrl + Arrow keys</strong> to view a yearly calendar. </p>
					<p><span class="bg-circle">5</span> You need to choose a date to close the layer.</p>
				</div>
			</div>
		</div>
		<div class="how-to-block" id="slider">
			<div class="block-title">
				<h3 class="title">Use Slider</h3>
			</div>
			<div class="row">
				<div class="image has-border">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/slider_1.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">1</span> Press Tab key to set focus to the slider and use the <strong>Arrow keys</strong> to set the slider values.</p>
					<p><span class="bg-circle">2</span> When using the Screen Reader Program (JAWS or NVDA), press <strong>Tab</strong> key to set focus to the slider and use the <strong>Arrow keys</strong> to set the slider values.</p>
				</div>
			</div>
		</div>
	</div>
</section>