<section class="static-content accessibility-help">
	<div class="title-wrap">
		<h1 class="title">ACCESSIBILITY HELP</h1>
		<h2 class="sub-title">Visually Impaired</h2>
	</div>
	<div class="tab-wrap">
		<ul>
			<li>
				<a href="#">Keyboard Controls</a>
			</li>
			<li class="active">
				<a href="#">Visually Impaired</a>
			</li>
			<li>
				<a href="#">Hearing Impaired</a>
			</li>
		</ul>
	</div>
	<div class="overview-wrap">
		<div class="overview-list">
			<p class="title">In this section, you can find how to:</p>
			<ul class="has-bullet">
				<li>
					Use the Zoom Function – <a href="#zoom_ie">IE(version 9.0 or later),</a> <a href="#zoom_firefox">Firefox(Current –1),</a> <a href="#zoom_chrome">Chrome(Current –1)</a>
				</li>
				<li>
					<a href="#magnifier">Use Magnifier, the Built-in Magnification Feature in Windows</a>
				</li>
				<li>
					<a href="#set_magnifier">Set Magnifier to Start Automatically</a>
				</li>
				<li>
					Change Background and Text Colors - <a href="#changeColor_ie">IE(version 9.0 or later),</a> <a href="#changeColor_firefox">Firefox(Current –1),</a> <a href="#changeColor_chrome">Chrome(Current –1)</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="how-to-wrap">
		<div class="how-to-block" id="zoom_ie">
			<div class="block-title">
				<h3 class="title">Zoom Function in Internet Explorer (version 9.0 or later)</h3>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/zoom_ie_1.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">1</span> If you are using Internet Explorer, go to the menu at the top of the browser window and click on 'View'.</p>
					<p><span class="bg-circle">2</span> From the list of options, click 'Zoom'. You will see a side menu open up.</p>
					<p><span class="bg-circle">3</span> Select the predefined zoom level, or specify a custom level by clicking 'Custom' and entering a zoom value.</p>
				</div>
				<div class="additional">
					<div class="desc">
						<p class="em">Internet Explorer also allows the text size to be changed with keyboard shortcuts:</p>
						<ul class="has-bullet">
							<li>Press <strong>Ctrl</strong> and <strong>+</strong> to increase the size</li>
							<li>Press <strong>Ctrl</strong> and <strong>-</strong> to decrease the size</li>
							<li>Press <strong>Ctrl</strong> and <strong>0</strong> to go back to the default size</li>
						</ul>
					</div>
				</div>

			</div>
		</div>
		<div class="how-to-block" id="zoom_firefox">
			<div class="block-title">
				<h3 class="title">Zoom Function in Firefox (Current –1)</h3>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/zoom_firefox_1.jpg" alt="" />
				</div>
				<div class="desc">
					<p class="em">Zoom Function in Firefox (Current –1)</p>
					<p><span class="bg-circle">1</span> If you are using Firefox, go to the menu at the top of the browser window and click on 'View'.</p>
					<p><span class="bg-circle">2</span> From the list of options, click 'Zoom'. You will see a side menu open up.</p>
					<p><span class="bg-circle">3</span> Select 'Zoom In' option to increase the text size or select the 'Zoom out' option to decrease the text size.</p>
					<p><span class="bg-circle">4</span> Select 'Reset' to reset to default settings.</p>
				</div>
				<div class="additional">
					<div class="desc">
						<p class="em">Firefox also allows the text size to be changed with keyboard shortcuts:</p>
						<ul class="has-bullet">
							<li>Press <strong>Ctrl</strong> and <strong>+</strong> to increase the size</li>
							<li>Press <strong>Ctrl</strong> and <strong>-</strong> to decrease the size</li>
							<li>Press <strong>Ctrl</strong> and <strong>0</strong> to go back to the default size</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="how-to-block" id="zoom_chrome">
			<div class="block-title">
				<h3 class="title">Zoom Function in Chrome (Current –1)</h3>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/zoom_chrome_1.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">1</span> If you are using Chrome, click the Menu icon on the top right.</p>
					<p><span class="bg-circle">2</span> Click on '–' to zoom out. Click on '+' to zoom in.</p>
					<p><span class="bg-circle">3</span> Click on '100%' to return to default size.</p>
				</div>
				<div class="additional">
					<div class="desc">
						<p class="em">Chrome also allows the text size to be changed with keyboard shortcuts:</p>
						<ul class="has-bullet">
							<li>Press <strong>Ctrl</strong> and <strong>+</strong> to increase the size</li>
							<li>Press <strong>Ctrl</strong> and <strong>-</strong> to decrease the size</li>
							<li>Press <strong>Ctrl</strong> and <strong>0</strong> to go back to the default size</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="how-to-block" id="magnifier">
			<div class="block-title">
				<h3 class="title">Use Magnifier, the Built-in Magnification Feature in Windows</h3>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/magnifier_1.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">1</span> Select 'Ease of Access' in the control panel.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/magnifier_2.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">2</span> Select 'Ease of Access Center'.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/magnifier_3.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">3</span> Under the 'Quick access to common tools' header, click 'Start Magnifier'. This will start the magnifier for current use.</p>
				</div>
			</div>
		</div>
		<div class="how-to-block" id="set_magnifier">
			<div class="block-title">
				<h3 class="title">Set Magnifier to Start Automatically</h3>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/set_magnifier_1.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">1</span> Select 'Ease of Access' in the control panel.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/set_magnifier_2.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">2</span> Select 'Ease of Access Center'.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/set_magnifier_3.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">3</span> Under the 'Explore all settings' header, click on 'Make the computer easier to see'.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/set_magnifier_4.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">4</span> Under the 'Make things on the screen larger' header, Click the box next to 'Turn on Magnifier'.</p>
					<p><span class="bg-circle">5</span> Click the 'OK' button to save tour changes.</p>
				</div>
			</div>
		</div>
		<div class="how-to-block">
			<div class="block-title">
				<h3 class="title">The following keyboard shortcuts are available when using Magnifier.</h3>
			</div>
			<div class="additional">
				<div class="desc">
					<ul class="has-bullet">
						<li>Press <strong>Windows key</strong> and <strong>+</strong> to zoom in.</li>
						<li>Press <strong>Windows key</strong> and <strong>-</strong> to zoom out.</li>
						<li>Press <strong>Ctrl</strong>, <strong>Alt</strong> and <strong>F</strong> to switch to 'Full-screen' mode.</li>
						<li>Press <strong>Ctrl</strong>, <strong>Alt</strong> and <strong>Spacebar</strong> to preview the desktop in full-screen mode.</li>
						<li>Press <strong>Ctrl</strong>, <strong>Alt</strong> and <strong>L</strong> to switch to 'Lens' mode.</li>
						<li>Press <strong>Ctrl</strong>, <strong>Alt</strong> and <strong>R</strong> to resize the lens.</li>
						<li>Press <strong>Ctrl</strong>, <strong>Alt</strong> and <strong>D</strong> to switch to 'Docked' mode.</li>
						<li>Press <strong>Ctrl</strong>, <strong>Alt</strong> and <strong>I</strong> to invert the colors in the magnification window.</li>
						<li>Press <strong>Ctrl</strong>, <strong>Alt</strong> and <strong>Arrow keys</strong> to move the focus in the direction chosen.</li>
						<li>Press <strong>Windows key</strong> and <strong>Esc</strong> to exit Magnifier.</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="how-to-block" id="changeColor_ie">
			<div class="block-title">
				<h3 class="title">Change Background and Text Colors in Internet Explorer (version 9.0 or later)</h3>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/changecolor_ie_1.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">1</span> Go to 'Tools' and then select 'Internet Options'.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/changecolor_ie_2.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">2</span> Ensure the 'General' tab is selected. Under the 'Appearance' header click the 'Colors' button.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/changecolor_ie_3.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">3</span> Unclick the 'Use Windows colors' checkbox and then select the background and text colors you require. </p>
					<p><span class="bg-circle">4</span> Click 'OK' to close the dialog box.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/changecolor_ie_4.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">5</span> Click the 'Accessibility' button.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/changecolor_ie_5.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">6</span> Click the 'Formatting' checkboxes to overrule the system colors.</p>
					<p><span class="bg-circle">7</span> Click the 'OK' button to save your changes.</p>
				</div>
			</div>
		</div>
		<div class="how-to-block" id="changeColor_firefox">
			<div class="block-title">
				<h3 class="title">Change Background and Text Colors in Firefox (Current –1)</h3>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/changecolor_firefox_1.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">1</span> From the toolbar at the top of the Firefox browser window, select 'Tools' and select 'Options'.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/changecolor_firefox_2.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">2</span> Ensure the 'Content' tab is highlighted.</p>
					<p><span class="bg-circle">3</span> Under the 'Font &amp; Colors' header, select 'Colors'.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/changecolor_firefox_3.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">4</span> Choose between the color swatches to select different background colors and text colors.</p>
				</div>
			</div>
			<div class="row">
				<div class="image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/help/changecolor_firefox_4.jpg" alt="" />
				</div>
				<div class="desc">
					<p><span class="bg-circle">5</span> Choose one option from the drop-down box.</p>
					<p><span class="bg-circle">6</span> Click the 'OK' button to save your changes.</p>
				</div>
			</div>
		</div>
		<div class="how-to-block" id="changeColor_chrome">
			<div class="block-title">
				<h3 class="title">Change Background and Text Colors in Chrome (Current –1)</h3>
			</div>
			<div class="additional">
				<div class="desc">
					<p class="regular">If you are using Google Chrome, you need to install a plug in to change the background colors. A number of accessibility plug ins are available here: <br><a href="https://chrome.google.com/webstore/category/ext/22-accessibility" target="_blank" title="Open the new window">https://chrome.google.com/webstore/category/ext/22-accessibility</a></p>
				</div>
			</div>
		</div>
	</div>
</section>