<section class="ask-answer dark-grey-background">
  <div class="container">
		<h3>ASK &amp; ANSWER</h3>
		<p class="sub-header">Ask your questions. Share your answers.</p>
		<div class="content-area">
			<div id="BVQAContainer"></div>
		</div>
		<!-- XXX
		<form class="ask-search">
			<div class="field-wrap"><label for="input-ask-answer"><input type="text" name="input-ask-answer" id="input-ask-answer" maxlength="" class="" placeholder="Search All Questions for This Product"></label></div>
			<div class="button-wrap"><button class="btn" type="submit">Go</button></div>
		</form>
		<div class="ask-list-wrap">
			<form class="ask-select">
				<div class="ask-sort-option">
					<label for="sortby"><p>Sort by: </p></label>
					<div class="ask-selectbox">
						<select class="chosen-select" id="sortby">
							<option value=''>Most Helpful Questions</option>
							<option value=''>Most Helpful Questions</option>
						</select>
						<div class="button-wrap"><button class="btn" type="submit">Go</button></div>
					</div>
				</div>
				<p class="ask-result-counts">4 Questions &amp; 8 Answers</p>
			</form>
			<ul class="ask-list">
				<li>
					<div class="question">
						<strong>
							<a href="#">
								<i class="icon icon-tab-plus"></i>
								<span>PHYSICAL DIMENSIONS</span>
							</a>
						</strong>
						<span class="count">1 Answer</span>
					</div>
					<div class="answer">
						<strong>What are the physical dimensions?</strong>
						<p class="comment">We'll likely buy the http://www.lg.com/us/tvs/lg-55EG9600-oled-tv as soon as it is available.... if it fits.</p>
						<p class="category">Category: I do not own this product</p>
						<p class="date"><span>3 MONTHS AGO</span> <span>User Name : HeyBob</span> <span>Atlanta, GA, USA</span></p>
						<div class="result">
							<a href="#" class="btn">Answer This Question</a>
							<p>
								0out of 0 found this question helpful .
								<span><a href="#none">Helpful</a> | <a href="#none">Not Helpful</a> | <a href="#none">Report</a></span>
							</p>
						</div>
					</div>
				</li>
				<li>
					<div class="question">
						<strong>
							<a href="#">
								<i class="icon icon-tab-plus"></i>
								<span>WITH LG 9600 AND THE RECOMMENDED WALL MOUNT, WHAT WOULD THE DISTANCE FROM THE OUTER EDGE OF THE TV AT IT'S WIDTH, WHAT WOULD THE DISTANCE FROM THE EDG</span>
							</a>
						</strong>
						<span class="count">4 Answers</span>
					</div>
					<div class="answer">
						<strong>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</strong>
						<p class="comment">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. </p>
						<p class="category">Category: I do not own this product</p>
						<p class="date"><span>3 MONTHS AGO</span> <span>User Name : HeyBob</span> <span>Atlanta, GA, USA</span></p>
						<div class="result">
							<a href="#" class="btn">Answer This Question</a>
							<p>
								0out of 0 found this question helpful .
								<span><a href="#none">Helpful</a> | <a href="#none">Not Helpful</a> | <a href="#none">Report</a></span>
							</p>
						</div>
					</div>
				</li>
				<li>
					<div class="question">
						<strong>
							<a href="#">
								<i class="icon icon-tab-plus"></i>
								<span>What does the warranty cover</span>
							</a>
						</strong>
						<span class="count">2 Answers</span>
					</div>
					<div class="answer">
						<strong>What are the physical dimensions?</strong>
						<p class="comment">We'll likely buy the http://www.lg.com/us/tvs/lg-55EG9600-oled-tv as soon as it is available.... if it fits.</p>
						<p class="category">Category: I do not own this product</p>
						<p class="date"><span>3 MONTHS AGO</span> <span>User Name : HeyBob</span> <span>Atlanta, GA, USA</span></p>
						<div class="result">
							<a href="#" class="btn">Answer This Question</a>
							<p>
								0out of 0 found this question helpful .
								<span><a href="#none">Helpful</a> | <a href="#none">Not Helpful</a> | <a href="#none">Report</a></span>
							</p>
						</div>
					</div>
				</li>
				<li>
					<div class="question">
						<strong>
							<a href="#">
								<i class="icon icon-tab-plus"></i>
								<span>Smart Diagnosis technology</span>
							</a>
						</strong>
						<span class="count">1 Answer</span>
					</div>
					<div class="answer">
						<strong>What are the physical dimensions?</strong>
						<p class="comment">We'll likely buy the http://www.lg.com/us/tvs/lg-55EG9600-oled-tv as soon as it is available.... if it fits.</p>
						<p class="category">Category: I do not own this product</p>
						<p class="date"><span>3 MONTHS AGO</span> <span>User Name : HeyBob</span> <span>Atlanta, GA, USA</span></p>
						<div class="result">
							<a href="#" class="btn">Answer This Question</a>
							<p>
								0out of 0 found this question helpful .
								<span><a href="#none">Helpful</a> | <a href="#none">Not Helpful</a> | <a href="#none">Report</a></span>
							</p>
						</div>
					</div>
				</li>
			</ul>
			<div class="ask-bottom">
				<div class="ask-mobile-pagination">
					<a href="#"><i class="icon icon-arrow-prev-bold"></i></a>
					<div class="ask-page-counter"><span>1</span>/<span>4</span></div>
					<a href="#" class="on"><i class="icon icon-arrow-next-bold"></i></a>
				</div>
				<div class="ask-desktop-pagination">
					<ol>
						<li><a href="#" class="on">1</a></li>
						<li><a href="#">2</a></li>
						<li><a href="#">3</a></li>
						<li><a href="#">4</a></li>
					</ol>
					<a href="#" class="next">Next</a>
				</div>
				<a href="#" class="btn ask-new-question-btn">Ask a New Question</a>
			</div>
		</div>
		-->
	</div>
</section>
<!--
<section class="ask-answer dark-grey-background">
  <div class="container">
	  <h3>ASK &amp; ANSWER</h3>
	  <p class="sub-header">Ask your questions. Share your answers.</p>
	  <div class="content-area">
		<form class="ask-search">
			<div class="field-wrap"><label for="input-ask-answer"><input type="text" name="input-ask-answer" id="input-ask-answer" maxlength="" class="" placeholder="Search All Questions for This Product"></label></div>
			<div class="button-wrap"><button class="btn" type="submit">Go</button></div>
		</form>
		<div class="ask-no-result">
			<p>Be the first to ask a question</p>
			<div class="ask-bottom">
				<a href="#" class="btn ask-new-question-btn">Ask a New Question</a>
			</div>
		</div>
	</div>
</div>
</section>
-->