<section class="module-group group-carousel">
	<div class="module-carousel">

		<section class="module m01 text-light text-bottom">
			<div class="background-image" itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><!-- 2015-08-27 add itemprop, itemscope, itemtype -->
				<!-- 카테고리 상단에 slick 을 사용할경우 아래 이미지태그로 사용 부탁드립니다. -->
				<img data-lazy="/img_sample/group_category/group_01.jpg" data-src="" alt=""  />
				<!-- <img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/group_category/group_01.jpg" alt="LG Kitchen Appliances" /> -->
				<meta itemprop="contentUrl" content="/img_sample/group_category/group_01.jpg" /><!-- 2015-08-27 add meta -->
			</div>
			<div class="text-block">
				<h3>LG Kitchen Appliances</h3>
				<p>
					Fueled by innovation and state-of-the-art designs, LG brings innovation to your everyday experience with multiple benefits to suit your needs.

				</p>
				<div class="cta cta-button">
					<a href="#" class="btn">Learn More</a>
				</div>
			</div>
		</section>
	</div>
	<div class="module-carousel">

		<section class="module m01 text-light text-bottom">
			<div class="background-image" itemprop="image" itemscope itemtype="http://schema.org/ImageObject">
				<!-- 카테고리 상단에 slick 을 사용할경우 아래 이미지태그로 사용 부탁드립니다. -->
				<img data-lazy="/img_sample/group_category/group_01.jpg" data-src="" alt=""  />
				<!-- <img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/group_category/group_01.jpg" alt="LG Kitchen Appliances" /> -->
				<meta itemprop="contentUrl" content="/img_sample/group_category/group_01.jpg" />
			</div>
			<div class="text-block">
				<h3>LG Kitchen Appliances</h3>
				<p>
					Fueled by innovation and state-of-the-art designs, LG brings innovation to your everyday experience with multiple benefits to suit your needs.

				</p>
				<div class="cta cta-button">
					<a href="#" class="btn">Learn More</a>
				</div>
			</div>
		</section>
	</div>
</section>