<div class="add-to-compare">
	<div class="compare-view-item-holder"><div class="showdow"></div></div>
	<section class="compare-view-item">
<!-- 2015-05-22 폰트 아이콘으로 일부 이미지 변경, 별포인트 마크업 변경 -->
<!-- 2015-06-01 data-search-category 속성삭제 -->
		<form action="/ajaxData/compare.lg.html" method="post" class="filter" data-event="change" data-sc-item="filter-search">
			<!-- 2015-06-03 제거 -->
			<div class="compare-view-left">
				<div><a href="#" class="back-btn">&lt; Back</a></div>
			</div>

			<div class="compare-item">
				<p class="compare-title">Compare TVs</p>
				<!-- 2015-08-24 마크업 일부 수정 -->
				<p class="compare-count"><strong><span class="count">6</span></strong> <span class="check-singular" data-singular="Product in Comparison" data-plural="Products in Comparison">Products in Comparison</span></p><!-- 2015-06-01 숫자만 변경 -->

				<div class="item-view">
					<div class="view-cont">
						<!-- 2015-06-18 width값 수정-->
						<ul class="product-lists item-list" style="width:1700px;" data-change-text="LOCK|UNLOCK">
							<li class="item">
								<div class="item-area">
									<ul class="item-uitls">
										<li><a href="#" data-product-id="LRG3181ST">LOCK</a></li>
										<li><a href="#" data-product-id="LRG3181ST">REMOVE</a></li>
									</ul>
									<!-- 2015-06-22 lazy load 적용 -->
									<p class="item-img"><a href="#"><img src="/img_sample/cate_refrig_1.jpg" alt="" /></a></p>
									<div class="item-list-info">
										<p class="model-num">65EG9700</p>
									</div>
									<div class="item-details">
										<div class="rating" data-modelid="MD00001294">
											<div class="points_wrap">
												<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
											</div>
											<span><a href="#">(9)</a></span><!-- 2015-06-01 link -->
										</div>
										<a href="#" class="item-buy-btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to Buy</a>
										<!-- 2015-06-12 마크업 수정 -->
										<div class="product-price">
											<!-- 2015-06-01 promotional-price 가 있는 경우
											<div class="suggested-price">
												<p class="price">$3499.<span>99</span></p>
												<p class="legal">Suggested Price</p>
											</div>
											<div class="promotional-price">
												<p class="price">$1499.<span>99</span></p>
												<p class="legal">Promotional Price</p>
											</div>
											-->
											<div class="purchase-price">
												<p class="price">$3499.<span>99</span></p>
												<p class="legal">Suggested Price</p>
											</div>
										</div>
									</div>
								</div>
							</li>
							<li class="item">
								<div class="item-area">
									<ul class="item-uitls">
										<li><a href="#" data-product-id="LRG3182ST">LOCK</a></li>
										<li><a href="#" data-product-id="LRG3182ST">REMOVE</a></li>
									</ul>
									<!-- 2015-06-22 lazy load 적용 -->
									<p class="item-img"><a href="#"><img src="/img_sample/cate_refrig_2.jpg" alt="" /></a></p>
									<div class="item-list-info">
										<p class="model-num">65EG9700</p>
									</div>
									<div class="item-details">
										<div class="rating" data-modelid="MD00001200">
											<a href="#" class="no-rating">(Write a Review)</a><!-- 2015-06-01 별점 없을때 -->
										</div>
										<a href="#" class="item-buy-btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to Buy</a>
										<!-- 2015-06-12 마크업 수정 -->
										<div class="product-price">
											<!-- 2015-06-01 promotional-price 가 있는 경우
											<div class="suggested-price">
												<p class="price">$3499.<span>99</span></p>
												<p class="legal">Suggested Price</p>
											</div>
											<div class="promotional-price">
												<p class="price">$1499.<span>99</span></p>
												<p class="legal">Promotional Price</p>
											</div>
											-->
											<div class="purchase-price">
												<p class="price">$3499.<span>99</span></p>
												<p class="legal">Suggested Price</p>
											</div>
										</div>
									</div>
								</div>
							</li>
							<li class="item">
								<div class="item-area">
									<ul class="item-uitls">
										<li><a href="#" data-product-id="LRG3183ST">LOCK</a></li>
										<li><a href="#" data-product-id="LRG3183ST">REMOVE</a></li>
									</ul>
									<!-- 2015-06-22 lazy load 적용 -->
									<p class="item-img"><a href="#"><img src="/img_sample/cate_refrig_1.jpg" alt="" /></a></p>
									<div class="item-list-info">
										<p class="model-num">65EG9700</p>
									</div>
									<div class="item-details">
										<div class="rating" data-modelid="MD00001395">
											<div class="points_wrap">
												<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
											</div>
											<span><a href="#">(9)</a></span><!-- 2015-06-01 link -->
										</div>
										<a href="#" class="item-buy-btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to Buy</a>
										<!-- 2015-06-12 마크업 수정 -->
										<div class="product-price">
											<!-- 2015-06-01 promotional-price 가 있는 경우
											<div class="suggested-price">
												<p class="price">$3499.<span>99</span></p>
												<p class="legal">Suggested Price</p>
											</div>
											<div class="promotional-price">
												<p class="price">$1499.<span>99</span></p>
												<p class="legal">Promotional Price</p>
											</div>
											-->
											<div class="purchase-price">
												<p class="price">$3499.<span>99</span></p>
												<p class="legal">Suggested Price</p>
											</div>
										</div>
									</div>
								</div>
							</li>
							<li class="item">
								<div class="item-area">
									<ul class="item-uitls">
										<li><a href="#" data-product-id="LRG3184ST">LOCK</a></li>
										<li><a href="#" data-product-id="LRG3184ST">REMOVE</a></li>
									</ul>
									<!-- 2015-06-22 lazy load 적용 -->
									<p class="item-img"><a href="#"><img src="/img_sample/cate_refrig_2.jpg" alt="" /></a></p>
									<div class="item-list-info">
										<p class="model-num">65EG9700</p>
									</div>
									<div class="item-details">
										<div class="rating" data-modelid="MD00001396">
											<div class="points_wrap">
												<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
											</div>
											<span><a href="#">(9)</a></span><!-- 2015-06-01 link -->
										</div>
										<a href="#" class="item-buy-btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to Buy</a>
										<!-- 2015-06-12 마크업 수정 -->
										<div class="product-price">
											<!-- 2015-06-01 promotional-price 가 있는 경우
											<div class="suggested-price">
												<p class="price">$3499.<span>99</span></p>
												<p class="legal">Suggested Price</p>
											</div>
											<div class="promotional-price">
												<p class="price">$1499.<span>99</span></p>
												<p class="legal">Promotional Price</p>
											</div>
											-->
											<div class="purchase-price">
												<p class="price">$3499.<span>99</span></p>
												<p class="legal">Suggested Price</p>
											</div>
										</div>
									</div>
								</div>
							</li>
							<li class="item">
								<div class="item-area">
									<ul class="item-uitls">
										<li><a href="#" data-product-id="LRG3185ST">LOCK</a></li>
										<li><a href="#" data-product-id="LRG3185ST">REMOVE</a></li>
									</ul>
									<!-- 2015-06-22 lazy load 적용 -->
									<p class="item-img"><a href="#"><img src="/img_sample/cate_refrig_1.jpg" alt="" /></a></p>
									<div class="item-list-info">
										<p class="model-num">65EG9700</p>
									</div>
									<div class="item-details">
										<div class="rating" data-modelid="MD00001397">
											<div class="points_wrap">
												<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
											</div>
											<span><a href="#">(9)</a></span><!-- 2015-06-01 link -->
										</div>
										<a href="#" class="item-buy-btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to Buy</a>
										<!-- 2015-06-12 마크업 수정 -->
										<div class="product-price">
											<!-- 2015-06-01 promotional-price 가 있는 경우
											<div class="suggested-price">
												<p class="price">$3499.<span>99</span></p>
												<p class="legal">Suggested Price</p>
											</div>
											<div class="promotional-price">
												<p class="price">$1499.<span>99</span></p>
												<p class="legal">Promotional Price</p>
											</div>
											-->
											<div class="purchase-price">
												<p class="price">$3499.<span>99</span></p>
												<p class="legal">Suggested Price</p>
											</div>
										</div>
									</div>
								</div>
							</li>
							<li class="item">
								<div class="item-area">
									<ul class="item-uitls">
										<li><a href="#" data-product-id="LRG3186ST">LOCK</a></li>
										<li><a href="#" data-product-id="LRG3186ST">REMOVE</a></li>
									</ul>
									<!-- 2015-06-22 lazy load 적용 -->
									<p class="item-img"><a href="#"><img src="/img_sample/cate_refrig_2.jpg" alt="" /></a></p>
									<div class="item-list-info">
										<p class="model-num">65EG9700</p>
									</div>
									<div class="item-details">
										<div class="rating" data-modelid="MD00001398">
											<div class="points_wrap">
												<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
											</div>
											<span><a href="#">(9)</a></span><!-- 2015-06-01 link -->
										</div>
										<a href="#" class="item-buy-btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to Buy</a>
										<!-- 2015-06-12 마크업 수정 -->
										<div class="product-price">
											<!-- 2015-06-01 promotional-price 가 있는 경우
											<div class="suggested-price">
												<p class="price">$3499.<span>99</span></p>
												<p class="legal">Suggested Price</p>
											</div>
											<div class="promotional-price">
												<p class="price">$1499.<span>99</span></p>
												<p class="legal">Promotional Price</p>
											</div>
											-->
											<div class="purchase-price">
												<p class="price">$3499.<span>99</span></p>
												<p class="legal">Suggested Price</p>
											</div>
										</div>
									</div>
								</div>
							</li>
						</ul>
					</div>

					<div class="view-control">
						<a href="#" class="btn-prev" style="display:none;"><i class="icon icon-arrow-prev"></i><span class="alt-text">Previous</span></a><!-- 2015-08-27 -->
						<a href="#" class="btn-next" style="display:none;"><i class="icon icon-arrow-next"></i><span class="alt-text">Next</span></a><!-- 2015-08-27 -->
					</div>
				</div>

			</div>
		</form>
	</section>
	<section class="compare-item-info">
		<div class="info-summary">
			<p class="summary-title">Summary</p>
			<div class="info-list">
				<ul class="info-title">
					<li>Size (Diagonal)</li>
					<li>Display type</li>
					<li>Resolution</li>
					<li>Smart TV Platform</li>
					<li>HDMI</li>
				</ul>
				<div class="info-cont">
					<div class="info-view">
						<div class="info-cont-view" style="width:1700px;">
							<ul class="info-cont-list">
								<li>LED, TV, smart TV,Ultra HD 4k tv</li>
								<li>LED, TV, smart TV,Ultra HD 4k tv</li>
								<li>Full HD 1080pFull HD 1080pFull HD 1080pFull HD 1080p</li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li>2 (rear)</li>
							</ul>
							<ul class="info-cont-list">
								<li>LED, TV, smart TV, ultra HD 4k tv</li>
								<li>OLED LED, TV, Smart TV,Ultra HD 4k tv</li>
								<li>Ultra HD 4K</li>
								<li>WebOS 2.0</li>
								<li>4 (rear), 2 (side)</li>
							</ul>
							<ul class="info-cont-list">
								<li>65” (64.5”)</li>
								<li>OLED LED, TV, Smart TV,Ultra HD 4k tv</li>
								<li>Ultra HD 4K</li>
								<li>WebOS 2.0</li>
								<li>4 (rear), 1 (side)</li>
							</ul>
							<ul class="info-cont-list">
								<li>65” (64.5”)</li>
								<li>OLED OLED LED, TV, smart TV, ultra HD 4k tv OLED LED, TV, smart TV, ultra HD 4k tv</li>
								<li>Ultra HD 4K</li>
								<li>WebOS 2.0</li>
								<li>3 (rear), 1 (side)</li>
							</ul>
							<ul class="info-cont-list">
								<li>65” (64.5”)</li>
								<li>OLED OLED LED, TV, smart TV, ultra HD 4k tv</li>
								<li>Ultra HD 4K</li>
								<li>WebOS 2.0</li>
								<li>3 (rear), 2 (side)</li>
							</ul>
							<ul class="info-cont-list">
								<li>65” (64.5”)</li>
								<li>OLED OLED LED, TV, smart TV, ultra HD 4k tv</li>
								<li>Ultra HD 4K</li>
								<li>WebOS 2.0</li>
								<li>2 (rear), 1 (side)</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<p class="compare-sub-title">Technical Specifications</p>
		<!-- 2015-05-22 마크업변경-->
		<div class="accordion-control-holder"><div class="showdow"></div></div>
		<div class="accordion-control">
			<div>
				<dl class="choice-control">
					<dt>Show:</dt>
					<dd class="selected"><a href="#">All Specs</a></dd><!-- 선택시 clicked 추가 -->
					<dd class="hide"><a href="#">All Specs</a></dd>
					<dd class="hide"><a href="#">Differences</a></dd>
					<dd class="hide"><a href="#">Selection</a></dd>
				</dl>
				<a href="#" class="all-view"><i class="icon icon-tab-plus"></i> Expand All</a><!-- 2015-05-22 / 2015-06-04 -->
				<a href="#" class="all-close" style="display:none;"><i class="icon icon-tab-minus"></i> Collapse All</a>
			</div>
		</div>
		<!-- //2015-05-22 마크업변경-->
		<div class="info-technical">
			<p class="info-list-title"><a href="#" class="hidden-title"><i class="icon icon-tab-minus"></i> Picture Quality</a></p><!-- 접기아이콘은 view-title 대신 hidden-title로 -->
			<div class="info-list">
				<ul class="info-title">
					<li><label><input type="checkbox" class="chk" /> Ultra HD (3840x2160)</label></li>
					<li><label><input type="checkbox" class="chk" /> Refresh Rate</label></li>
					<li><label><input type="checkbox" class="chk" /> LED Plus  (local dimming)</label></li>
					<li><label><input type="checkbox" class="chk" /> Tru-4k Engine</label></li>
					<li><label><input type="checkbox" class="chk" /> Tru-4k upscaler</label></li>
					<li><label><input type="checkbox" class="chk" /> Triple xd engine</label></li>
				</ul>
				<div class="info-cont">
					<div class="info-view">
						<!-- 2015-06-18 width값 수정-->
						<div class="info-cont-view" style="width:1700px;">
							<ul class="info-cont-list">
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li>12Hz 12Hz12Hz 12Hz 12Hz12Hz 12Hz 12Hz12Hz </li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li><!-- 2015-08-27 alt-text 추가 -->
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li><!-- 2015-08-27 alt None을 N/A로 변경 -->
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
							<ul class="info-cont-list">
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li>12Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="info-technical techmical-hidden">
			<p class="info-list-title"><a href="#" class="view-title"><i class="icon icon-tab-minus"></i> Audio</a></p><!-- - 아이콘은 view-title 대신 hidden-title로 -->
			<div class="info-list">
				<ul class="info-title">
					<li><label><input type="checkbox" class="chk" /> Ultra HD (3840x2160)</label></li>
					<li><label><input type="checkbox" class="chk" /> Refresh Rate</label></li>
					<li><label><input type="checkbox" class="chk" /> LED Plus  (local dimming)</label></li>
					<li><label><input type="checkbox" class="chk" /> Tru-4k Engine</label></li>
					<li><label><input type="checkbox" class="chk" /> Tru-4k upscaler</label></li>
					<li><label><input type="checkbox" class="chk" /> Triple xd engine</label></li>
				</ul>
				<div class="info-cont">
					<div class="info-view">
						<!-- 2015-06-18 width값 수정-->
						<div class="info-cont-view" style="width:1700px;">
							<ul class="info-cont-list">
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li>1 Year Parts & Labor</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>1 Year Parts & Labor</li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
							<ul class="info-cont-list">
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li>12Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="info-technical techmical-hidden">
			<p class="info-list-title"><a href="#" class="view-title"><i class="icon icon-tab-minus"></i> connectivity</a></p><!-- - 아이콘은 view-title 대신 hidden-title로 -->
			<div class="info-list">
				<ul class="info-title">
					<li><label><input type="checkbox" class="chk" /> Ultra HD (3840x2160)</label></li>
					<li><label><input type="checkbox" class="chk" /> Refresh Rate</label></li>
					<li><label><input type="checkbox" class="chk" /> LED Plus  (local dimming)</label></li>
					<li><label><input type="checkbox" class="chk" /> Tru-4k Engine</label></li>
					<li><label><input type="checkbox" class="chk" /> Tru-4k upscaler</label></li>
					<li><label><input type="checkbox" class="chk" /> Triple xd engine</label></li>
				</ul>
				<div class="info-cont">
					<div class="info-view">
						<!-- 2015-06-18 width값 수정-->
						<div class="info-cont-view" style="width:1700px;">
							<ul class="info-cont-list">
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li>12Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
							<ul class="info-cont-list">
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li>12Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="info-technical techmical-hidden">
			<p class="info-list-title"><a href="#" class="view-title"><i class="icon icon-tab-minus"></i> smart tv</a></p><!-- - 아이콘은 view-title 대신 hidden-title로 -->
			<div class="info-list">
				<ul class="info-title">
					<li><label><input type="checkbox" class="chk" /> Ultra HD (3840x2160)</label></li>
					<li><label><input type="checkbox" class="chk" /> Refresh Rate</label></li>
					<li><label><input type="checkbox" class="chk" /> LED Plus  (local dimming)</label></li>
					<li><label><input type="checkbox" class="chk" /> Tru-4k Engine</label></li>
					<li><label><input type="checkbox" class="chk" /> Tru-4k upscaler</label></li>
					<li><label><input type="checkbox" class="chk" /> Triple xd engine</label></li>
				</ul>
				<div class="info-cont">
					<div class="info-view">
						<!-- 2015-06-18 width값 수정-->
						<div class="info-cont-view" style="width:1700px;">
							<ul class="info-cont-list">
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li>12Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
							<ul class="info-cont-list">
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li>12Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="info-technical techmical-hidden">
			<p class="info-list-title"><a href="#" class="view-title"><i class="icon icon-tab-minus"></i> smart share</a></p><!-- - 아이콘은 view-title 대신 hidden-title로 -->
			<div class="info-list">
				<ul class="info-title">
					<li><label><input type="checkbox" class="chk" /> Ultra HD (3840x2160)</label></li>
					<li><label><input type="checkbox" class="chk" /> Refresh Rate</label></li>
					<li><label><input type="checkbox" class="chk" /> LED Plus  (local dimming)</label></li>
					<li><label><input type="checkbox" class="chk" /> Tru-4k Engine</label></li>
					<li><label><input type="checkbox" class="chk" /> Tru-4k upscaler</label></li>
					<li><label><input type="checkbox" class="chk" /> Triple xd engine</label></li>
				</ul>
				<div class="info-cont">
					<div class="info-view">
						<!-- 2015-06-18 width값 수정-->
						<div class="info-cont-view" style="width:1700px;">
							<ul class="info-cont-list">
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li>12Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
							<ul class="info-cont-list">
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li>12Hz</li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							</ul>
							<ul class="info-cont-list">
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li>240Hz</li>
								<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
								<li><i class="icon icon-check"></i><span class="alt-text">available</span></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
<!-- 2015-06-03 script 삭제 -->