<!-- 2015-06-02 앵커 href속성 제거 -->
<!-- 2015-06-04 상품 별점 이미지 아이콘으로 수정, 상품스팩 체크 이미지 아이콘으로 수정, 스팩 title 이미지 아이콘으로 수정 -->
<div class="compare-view-item">
	<div class="compare-view-left">
		<h1><img src="/lg4-common/img/mysearch/logo.png" alt="LG" /></h1>
	</div>
	<div class="compare-item">
		<h2 class="compare-title">Compare TVs</h2>
		<ul class="item-list">
			<li class="item">
				<div class="item-area">
					<p class="item-img"><img src="/img_sample/cate_refrig_1.jpg" alt="샘플이미지" /></p>
					<div class="item-list-info">
						<p class="model-num">65EG9700 65EG9700 65EG9700 65EG9700 65EG9700 65EG9700 65EG9700 65EG9700 65EG9700</p>
					</div>
					<div class="item-details">
						<div class="rating" data-modelid="MD05196041"><!-- 2015-08-11 -->
							<div class="points_wrap">
								<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
							</div>
							<span>(9)</span>
						</div>
						<p class="item-price">
							<strong>$6993.<em>99</em></strong>
							<span>Suggested Price</span>
						</p>
					</div>
				</div>
			</li>
			<li class="item">
				<div class="item-area">
					<p class="item-img"><img src="/img_sample/cate_refrig_1.jpg" alt="샘플이미지" /></p>
					<div class="item-list-info">
						<p class="model-num">55EG9700</p>
					</div>
					<div class="item-details">
						<div class="rating" data-modelid="MD05196042"><!-- 2015-08-11 -->
							<p class="no-rating">Be the first to review</p><!-- 2015-06-01 별점 없을때 -->
						</div>
						<p class="item-price">
							<strong>$6999.<em>99</em></strong>
							<span>Suggested Price</span>
						</p>
					</div>
				</div>
			</li>
			<li class="item">
				<div class="item-area">
					<p class="item-img"><img src="/img_sample/cate_refrig_1.jpg" alt="샘플이미지" /></p>
					<div class="item-list-info">
						<p class="model-num">65EG9700</p>
					</div>
					<div class="item-details">
						<div class="rating" data-modelid="MD05196043"><!-- 2015-08-11 -->
							<p class="no-rating">Be the first to review</p><!-- 2015-06-01 별점 없을때 -->
						</div>
						<p class="item-price">
							<strong>$6993.<em>99</em></strong>
							<span>Suggested Price</span>
						</p>
					</div>
				</div>
			</li>
			<li class="item">
				<div class="item-area">
					<p class="item-img"><img src="/img_sample/cate_refrig_1.jpg" alt="샘플이미지" /></p>
					<div class="item-list-info">
						<p class="model-num">55EG9700</p>
					</div>
					<div class="item-details">
						<div class="rating" data-modelid="MD051960444"><!-- 2015-08-11 -->
							<p class="no-rating">Be the first to review</p><!-- 2015-06-01 별점 없을때 -->
						</div>
						<p class="item-price">
							<strong>$6999.<em>99</em></strong>
							<span>Suggested Price</span>
						</p>
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>
<div class="compare-item-info">
	<div class="info-summary">
		<p class="summary-title">Summary</p>
		<div class="info-list">
			<ul class="info-title">
				<li>Display type</li>
				<li>Resolution</li>
				<li>Smart TV Platform</li>
				<li>HDMI</li>
			</ul>
			<div class="info-cont">
				<div class="info-view">
					<div class="info-cont-view" style="width:1236px;">
						<ul class="info-cont-list">
							<li>LED TV Smart TV Ultra HD 4k TV</li>
							<li>Full HD 1080p</li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li>2 (rear)</li>
						</ul>
						<ul class="info-cont-list">
							<li>LED TV Smart TV Ultra HD 4k TV</li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li>WebOS 2.0</li>
							<li>4 (rear), 2 (side)</li>
						</ul>
						<ul class="info-cont-list">
							<li>LED TV Smart TV Ultra HD 4k TV</li>
							<li>Ultra HD 4K</li>
							<li>WebOS 2.0</li>
							<li>4 (rear), 1 (side)</li>
						</ul>
						<ul class="info-cont-list">
							<li>LED TV Smart TV Ultra HD 4k TV</li>
							<li>Ultra HD 4K</li>
							<li>WebOS 2.0</li>
							<li>3 (rear), 1 (side)</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<p class="compare-sub-title">Technical Specifications</p>
	<div class="info-technical">
		<p class="info-list-title"><span class="hidden-title"><i class="icon icon-tab-minus"></i>Picture Quality</span></p>
		<div class="info-list">
			<ul class="info-title">
				<li>Ultra HD (3840x2160)</li>
				<li>Refresh Rate</li>
				<li>LED Plus  (local dimming)</li>
				<li>Tru-4k Engine</li>
				<li>Tru-4k upscaler</li>
				<li>Triple xd engine</li>
			</ul>
			<div class="info-cont">
				<div class="info-view">
					<div class="info-cont-view" style="width:1236px;">
						<ul class="info-cont-list">
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li>12Hz</li>
							<li><i class="icon icon-check"></i></li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
						</ul>
						<ul class="info-cont-list">
							<li><i class="icon icon-check"></i></li>
							<li>240Hz</li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
						</ul>
						<ul class="info-cont-list">
							<li><i class="icon icon-check"></i></li>
							<li>240Hz</li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
						</ul>
						<ul class="info-cont-list">
							<li><i class="icon icon-check"></i></li>
							<li>240Hz</li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="info-technical">
		<p class="info-list-title"><span class="view-title"><i class="icon icon-tab-minus"></i>Audio</span></p>
		<div class="info-list">
			<ul class="info-title">
				<li>Ultra HD (3840x2160)</li>
				<li>Refresh Rate</li>
				<li>LED Plus  (local dimming)</li>
				<li>Tru-4k Engine</li>
				<li>Tru-4k upscaler</li>
				<li>Triple xd engine</li>
			</ul>
			<div class="info-cont">
				<div class="info-view">
					<div class="info-cont-view" style="width:1236px;">
						<ul class="info-cont-list">
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li>12Hz</li>
							<li><i class="icon icon-check"></i></li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
						</ul>
						<ul class="info-cont-list">
							<li><i class="icon icon-check"></i></li>
							<li>240Hz</li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
						</ul>
						<ul class="info-cont-list">
							<li><i class="icon icon-check"></i></li>
							<li>240Hz</li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
						</ul>
						<ul class="info-cont-list">
							<li><i class="icon icon-check"></i></li>
							<li>240Hz</li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!--
<div class="compare-view-item">
	<div class="compare-item">
		<ul class="item-list">
			<li class="item">
				<div class="item-area">
					<p class="item-img"><img src="/img_sample/cate_refrig_1.jpg" alt="샘플이미지" /></p>
					<div class="item-list-info">
						<p class="model-num">65EG9700</p>
					</div>
					<div class="item-details">
						<div class="rating">
							<div class="points_wrap">
								<div class="review_bg" style="width:40%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
							</div>
							<span>(4)</span>
						</div>
						<p class="item-price">
							<strong>$6993.<em>99</em></strong>
							<span>Suggested Price</span>
						</p>
					</div>
				</div>
			</li>
			<li class="item">
				<div class="item-area">
					<p class="item-img"><img src="/img_sample/cate_refrig_1.jpg" alt="샘플이미지" /></p>
					<div class="item-list-info">
						<p class="model-num">55EG9700</p>
					</div>
					<div class="item-details">
						<div class="rating">
							<div class="points_wrap">
								<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
							</div>
							<span>(5)</span>
						</div>
						<p class="item-price">
							<strong>$6999.<em>99</em></strong>
							<span>Suggested Price</span>
						</p>
					</div>
				</div>
			</li>
			<li class="item">
				<div class="item-area">
					<p class="item-img"><img src="/img_sample/cate_refrig_1.jpg" alt="샘플이미지" /></p>
					<div class="item-list-info">
						<p class="model-num">65EG9700</p>
					</div>
					<div class="item-details">
						<div class="rating">
							<div class="points_wrap">
								<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
							</div>
							<span>(9)</span>
						</div>
						<p class="item-price">
							<strong>$6993.<em>99</em></strong>
							<span>Suggested Price</span>
						</p>
					</div>
				</div>
			</li>
			<li class="item">
				<div class="item-area">
					<p class="item-img"><img src="/img_sample/cate_refrig_1.jpg" alt="샘플이미지" /></p>
					<div class="item-list-info">
						<p class="model-num">55EG9700</p>
					</div>
					<div class="item-details">
						<div class="rating">
							<div class="points_wrap">
								<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
							</div>
							<span>(9)</span>
						</div>
						<p class="item-price">
							<strong>$6999.<em>99</em></strong>
							<span>Suggested Price</span>
						</p>
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>

<div class="compare-item-info">
	<div class="info-summary">
		<p class="summary-title">Summary</p>
		<div class="info-list">
			<ul class="info-title">
				<li>Size (Diagonal)</li>
				<li>Display type</li>
				<li>Resolution</li>
				<li>Smart TV Platform</li>
				<li>HDMI</li>
			</ul>
			<div class="info-cont">
				<div class="info-view">
					<div class="info-cont-view" style="width:1236px;">
						<ul class="info-cont-list">
							<li>55” (54.5”)</li>
							<li>LED</li>
							<li>Full HD 1080p</li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li>2 (rear)</li>
						</ul>
						<ul class="info-cont-list">
							<li>65” (64.5”)</li>
							<li>OLED</li>
							<li>Ultra HD 4K</li>
							<li>WebOS 2.0</li>
							<li>4 (rear), 2 (side)</li>
						</ul>
						<ul class="info-cont-list">
							<li>65” (64.5”)</li>
							<li>OLED</li>
							<li>Ultra HD 4K</li>
							<li>WebOS 2.0</li>
							<li>4 (rear), 1 (side)</li>
						</ul>
						<ul class="info-cont-list">
							<li>65” (64.5”)</li>
							<li>OLED</li>
							<li>Ultra HD 4K</li>
							<li>WebOS 2.0</li>
							<li>3 (rear), 1 (side)</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<p class="compare-sub-title">Technical Specifications</p>
	<div class="info-technical">
		<p class="info-list-title"><span class="hidden-title"><i class="icon icon-tab-minus"></i>Picture Quality</span></p>
		<div class="info-list">
			<ul class="info-title">
				<li>Ultra HD (3840x2160)</li>
				<li>Refresh Rate</li>
				<li>LED Plus  (local dimming)</li>
				<li>Tru-4k Engine</li>
				<li>Tru-4k upscaler</li>
				<li>Triple xd engine</li>
			</ul>
			<div class="info-cont">
				<div class="info-view">
					<div class="info-cont-view" style="width:1236px;">
						<ul class="info-cont-list">
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li>12Hz</li>
							<li><i class="icon icon-check"></i></li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
						</ul>
						<ul class="info-cont-list">
							<li><i class="icon icon-check"></i></li>
							<li>240Hz</li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
						</ul>
						<ul class="info-cont-list">
							<li><i class="icon icon-check"></i></li>
							<li>240Hz</li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
						</ul>
						<ul class="info-cont-list">
							<li><i class="icon icon-check"></i></li>
							<li>240Hz</li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="info-technical">
		<p class="info-list-title"><span class="view-title"><i class="icon icon-tab-minus"></i>Audio</span></p>
		<div class="info-list">
			<ul class="info-title">
				<li>Ultra HD (3840x2160)</li>
				<li>Refresh Rate</li>
				<li>LED Plus  (local dimming)</li>
				<li>Tru-4k Engine</li>
				<li>Tru-4k upscaler</li>
				<li>Triple xd engine</li>
			</ul>
			<div class="info-cont">
				<div class="info-view">
					<div class="info-cont-view" style="width:1236px;">
						<ul class="info-cont-list">
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li>12Hz</li>
							<li><i class="icon icon-check"></i></li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
						</ul>
						<ul class="info-cont-list">
							<li><i class="icon icon-check"></i></li>
							<li>240Hz</li>
							<li><img src="/lg4-common/img/mysearch/img_compare_info_none.png" alt="none" /></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
						</ul>
						<ul class="info-cont-list">
							<li><i class="icon icon-check"></i></li>
							<li>240Hz</li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
						</ul>
						<ul class="info-cont-list">
							<li><i class="icon icon-check"></i></li>
							<li>240Hz</li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
							<li><i class="icon icon-check"></i></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
-->
<script type="text/javascript">
// 2015-07-13 삭제 
</script>