<section class="contact">
	<div class="container">
		<div class="container-title">
			<h2> We've Got Your Back </h2>
			<p>Need help before, during or after your LG TV purchase? We've got you covered.</p>
		</div>
		<div class="three-column">
			<div class="content-block chat-block">
				<div class="center-content">
					<div class="icon-wrap"><i class="icon icon-chat"></i></div>
					<h4>Live Chat</h4>
					<p><a href="http://service.velaro.com/visitor/requestchat.aspx?siteid=4851&amp;showwhen=inqueue" data-url="http://service.velaro.com/visitor/requestchat.aspx?siteid=4851&amp;showwhen=inqueue" target="_blank" title="new window" class="popup-live-chat">Chat online</a> with LG Support <br>(Weekdays 8am-8pm CST) </p>
				</div>
			</div>
			<div class="content-block phone-block">
				<div class="center-content">
					<div class="icon-wrap"><i class="icon icon-support"></i></div>
					<h4>Call Us</h4><!-- 2015-07-23 -->
					<div class="call-row">
						<!-- 2015-07-07 DTM --><a data-sc-item="footer-contact-call-us" href="tel:8002430000" class="red-block">Consumer Support <strong>(800) 243-0000</strong></a><!-- 2015-08-05 edit text and href value -->
						<p>6am-midnight CST</p><!-- 2015-07-31 텍스트 수정 -->
					</div>
					<div class="call-row">
						<!-- 2015-07-07 DTM --><a data-sc-item="footer-contact-call-us" href="tel:8888653026" class="red-block">Commercial Support <strong>(888) 865-3026</strong></a><!-- 2015-08-05 edit text -->
						<p>8am-6pm CST</p><!-- 2015-07-31 텍스트 수정 -->
					</div>
				</div>
			</div>
			<div class="content-block email-block">
				<div class="center-content">
					<div class="icon-wrap"><i class="icon icon-email"></i></div>
					<h4>Email Us</h4>
					<!-- 2015-07-07 DTM --><p><a href="#" data-sc-item="footer-contact-email">Send an inquiry</a> to LG Support </p>
				</div>
			</div>
		</div>
	</div>
</section>
