

<section class="static-content legal copyright">
	<div class="row title-wrap">
		<h1 class="title">COPYRIGHT</h1>
	</div>
	<div class="row-group">
		<div class="legal-contents">
			<div class="content-block">
				<p>
				LG Electronics, Inc. and its affiliates (hereinafter "LGE"), respects the intellectual property rights of others. In doing so, LGE complies with the provisions of the Digital Millennium Copyright Act (DMCA) applicable to internet service providers (17 U.S.C. §512, as amended). 
				</p>
				<p>
				In appropriate circumstances and at the discretion of LGE, it is LGE's policy to disable and/or terminate the accounts of users who infringe, or are repeatedly charged with infringing the copyright(s) or other intellectual property rights of others. LGE may remove content that is alleged to infringe the copyright(s) or other intellectual property rights of third parties. 
				</p>
				<p>
				If you are a copyright owner or agent thereof, and believe that any content posted on any of LGE's websites (hereinafter "the Sites") infringes upon your copyright(s), you may submit a notification pursuant to the DMCA to our designated Copyright Agent at the following address:	
				</p>
			</div>
			<div class="content-block">
				<ul>
					<li>LGE Copyright Agent </li>
					<li>Office of the General Counsel</li>
					<li>LG Electronics U.S.A., Inc.</li>
					<li>1000 Sylvan Avenue</li>
					<li>Englewood Cliffs, NJ 07632 </li>
					<li>dmca.copyright@lge.com </li>				
				</ul>
			</div>
			<div class="content-block">
				<p>Any notice alleging that materials hosted by or distributed through the Sites infringe on intellectual property rights must include the following information:</p>
				<ol>
					<li>An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright(s) or other right being infringed;</li>
					<li>A description of the copyrighted work or other intellectual property that you claim has been infringed;</li>
					<li>A description of the material that you claim is infringing and where it is located on the Sites;</li>
					<li>Your address, telephone number, and email address;</li>
					<li>A statement by you that you have a good faith belief that the use of the materials on the Sites of which you are complaining is not authorized by the copyright owner, its agent, or the law; and</li>
					<li>A statement by you that the above information in your notice is accurate and that, under penalty of perjury, you are the copyright(s) or intellectual property owner or authorized to act on the copyright(s) or intellectual property owner's behalf.</li>
				</ol>
			</div>
			<div class="content-block">
				<p>Counter-Notice. If you are a user who provided the content and believe that any content that was removed or to which access was disabled is not infringing, or that you have authorization from the copyright owner, the copyright owner's agent, or pursuant to the law, to post and use the material in your content, you may send a counter-notice containing the following information to LGE's Copyright Agent:</p>
				<ol>
					<li>Your physical or electronic signature;</li>
					<li>Identification of the content that has been removed or to which access has been disabled and the location at which the content appeared before it was removed or disabled;</li>
					<li>A statement that you have good faith that the content was removed or disabled as a result of mistake or misidentification of the content; and</li>
					<li>Your name, address, telephone number, and email address, a statement that you consent to the jurisdiction of the State of New York and the federal or state courts located in New York County, New York, and a statement that you will accept service of process from the person who provided notification of the alleged infringement.</li>
				</ol>
			</div>
			<div class="content-block">
				<p>If a counter-notice is received by LGE's Copyright Agent, LGE may send a copy of the counter-notice to the original complaining party informing the party that the content removed or disabled may be replaced. Unless the copyright owner files an action seeking a court order against the user who provided the content, that content may be replaced, or access restored, at LGE’s discretion in 10 to 14 business days or more after receipt of the counter-notice.</p>
			</div>
		</div>
	</div>
	<!-- 2015-08-12 삭제 <div class="back-to-top"><a href="#top">BACK TO TOP</a></div> -->
</section>