<section class="filter refind-your-search dark-grey-background discontinued">
	<form action="/ajaxData/filter.lg.discontinued.html" method="post" class="filter">
		<input type="hidden" name="bvApiUrl" value="http://lg.ugc.bazaarvoice.com/static/7676-en_us/bvapi.js"/>
		<div class="column2">
			<h1>Discontinued TVs</h1>
			<div class="content-head-desc">
				With deeper, richer colors and stunning contrast, LG OLED is unlike any technology you've ever seen, and it delivers a picture that exceeds your wildest imagination.
			</div>
			<section class="grid">
				<div class="response">
					<div class="page-controls">
						<span class="sort">
							<label for="sortBy">Sort by:</label>
							<select id="sortBy" name="sort" class="sort-select">
								<option value="0">Newest Products</option>
								<option value="1">Most Popular</option>
								<option value="2">Price: Lowest to Highest</option>
								<option value="3">Price: Highest to Lowest</option>
								<option value="4">LG Picks</option>
								<option value="5">Consumer Rating</option>
							</select>
						</span>
						<span class="pages">
							<a href="#" class="prev"><i class="icon icon-arrow-prev"></i></a>
							<a href="#" data-uri="/ajaxData/filter.lg.discontinued.html?viewAll=all-tvs&mstId=CT10000021&subId=CT10000062&page=1&sort=0&bvApiUrl=http://lg.ugc.bazaarvoice.com/static/7676-en_us/bvapi.js&&SEARCH_FT05006506_31=FV05006507&SEARCH_FT00001085_min=&SEARCH_FT00001085_max="  class="active">1</a> |
							<a href="#" data-uri="/ajaxData/filter.lg.discontinued.html?viewAll=all-tvs&mstId=CT10000021&subId=CT10000062&page=2&sort=0&bvApiUrl=http://lg.ugc.bazaarvoice.com/static/7676-en_us/bvapi.js&&SEARCH_FT05006506_31=FV05006507&SEARCH_FT00001085_min=&SEARCH_FT00001085_max=" >2</a> |
							<a href="#" data-uri="/ajaxData/filter.lg.discontinued.html?viewAll=all-tvs&mstId=CT10000021&subId=CT10000062&page=3&sort=0&bvApiUrl=http://lg.ugc.bazaarvoice.com/static/7676-en_us/bvapi.js&&SEARCH_FT05006506_31=FV05006507&SEARCH_FT00001085_min=&SEARCH_FT00001085_max=" >3</a> |
							<a href="#" data-uri="/ajaxData/filter.lg.discontinued.html?viewAll=all-tvs&mstId=CT10000021&subId=CT10000062&page=4&sort=0&bvApiUrl=http://lg.ugc.bazaarvoice.com/static/7676-en_us/bvapi.js&&SEARCH_FT05006506_31=FV05006507&SEARCH_FT00001085_min=&SEARCH_FT00001085_max=" >4</a> |
							<a href="#" data-uri="/ajaxData/filter.lg.discontinued.html?viewAll=all-tvs&mstId=CT10000021&subId=CT10000062&page=5&sort=0&bvApiUrl=http://lg.ugc.bazaarvoice.com/static/7676-en_us/bvapi.js&&SEARCH_FT05006506_31=FV05006507&SEARCH_FT00001085_min=&SEARCH_FT00001085_max=" >5</a> |
							<a href="#" data-uri="/ajaxData/filter.lg.discontinued.html?viewAll=all-tvs&mstId=CT10000021&subId=CT10000062&page=6&sort=0&bvApiUrl=http://lg.ugc.bazaarvoice.com/static/7676-en_us/bvapi.js&&SEARCH_FT05006506_31=FV05006507&SEARCH_FT00001085_min=&SEARCH_FT00001085_max=" >6</a>
							<a href="#" class="next"><i class="icon icon-arrow-next"></i></a>
							<a href="/us/tvs/all-tvs/view-all"  data-uri="/ajaxData/filter.lg.discontinued.html?viewAll=tvs/all-tvs&mstId=CT10000018&subId=CT10000018&page=0&sort=0&bvApiUrl=http://lg.ugc.bazaarvoice.com/static/7676-en_us/bvapi.js&&SEARCH_FT00000003_min=&SEARCH_FT00000001_03=FV06942348&SEARCH_FT00000001_01=FV06942350&SEARCH_FT00000003_max=&SEARCH_FT00000001_02=FV06942347&SEARCH_FT00000005_max=&SEARCH_FT00000005_min=" class="view-all ">View All</a>
						</span>
					</div>
					<div class="apply-filters">
					</div>
					<div class="product-grid-header">
						<span class="total"><span>45</span> Total Results</span>
						<!-- 2015-06-19 재반영 -->
						<span class="compare-util">
							<a href="/compare_d.html" class="compare-state">Compare <span>(0)</span></a>
							<a href="#" class="compare-clear hide">Clear All</a>
						</span>
					</div>

					<div class="product-grid">
						<div class="product-list-wrap">
							<ul class="product-lists">
								<li itemscope itemtype="http://schema.org/Product">
									<a href="#" class="img-link">
										<!-- 2015-06-22 lazy load 적용 -->
										<img alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" style="opacity: 1;">
									</a>
									<div class="copy-area">
										<p class="model-name" itemprop="name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
										<p class="model-num"><a href="#">55EA9800</a></p>
										<!-- 2015-06-11 사이즈 두개 이상일때 추가 -->
										<!-- 2015-06-19 사이즈 컬러 주석처리
										<!-- <p class="model-size"><a href="#">Sizes:65"</a> | <a href="#">55"</a> |<a href="#" class="etcSize">105"</a></p> 
										<p class="model-color">
											<a href="#" class="active" data-disclaimer="stainless-steel">
												<span class="color_chip_cover"></span>
												<span class="swatch large stainless-steel"></span>
												
											</a>
											<a href="#" data-disclaimer="smooth-black"><span class="swatch large smooth-black"></span></a>
											<a href="#" data-disclaimer="smooth-white"><span class="swatch large smooth-white"></span></a>
										</p>
										-->
										<div class="details">
											<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" data-modelid="MD00001294">
												<!--
												<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
												<meta itemprop="bestRating" content="5" />
												<meta itemprop="worstRating" content="1" />
												<div class="points_wrap">
													<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
													<meta itemprop="ratingValue" content="2.5" />
												</div>
												<span itemprop="reviewCount" content="9"><a href="#">(9 Reviews)</a></span>
												-->
												<!-- review 없을 시 -->
												<a href="/product_d.html#reviews"><span class="no-review">Be the first to review</span></a>
												<!-- 모바일에서는 review 앖을 시 텍스트를 (Write a review) 로 사용해 주세요. -->
											</div>
											<p class="compare-check">
												<label>
													<input type="checkbox" class="compare" data-product-id="LRG3181ST" name="compare"><span>Add to Compare</span>
												</label>
												<span class="compare_y hide"><a href="/compare_d.html">COMPARE (<em>1</em>)</a></span>
											</p>
											<!-- 2015-06-09 Add to Cart, Buy Now 버튼 추가 -->
											<div class="cta cta-button">
												<!-- <a href="https://usstore.lg.com/store?Action=buy&Env=BASE&Locale=en_US&SiteID=lgus&productID=306352300&quantity=1" class="btn">Pre Order</a><br /> -->
												<a href="https://usstore.lg.com/store?Action=buy&Env=BASE&Locale=en_US&SiteID=lgus&productID=306352300&quantity=1 " class="btn" data-sc-item="add-to-cart" data-sc-value="{모델코드}">Add to Cart</a><br /><!-- 2015-06-04 br 추가 -->
												<!-- 2015-06-04 best buy 추가 -->
												<a href="javascript:void(0)" class="btn buynow" data-sku="3429088" data-partner-id="LG" value="buy now" title="Open New Window" data-sc-item="buy-now" data-sc-value="{모델코드}">Buy Now</a><br />
											</div>
											<div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
												<!-- 2015-06-01 promotional-price 가 있는 경우
												<div class="suggested-price">
													<p class="price">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
												</div>
												<div class="promotional-price">
													<p class="price">$1499.<span>99</span></p>
													<p class="legal">Promotional Price</p>
												</div>
												-->
												<div class="purchase-price"  itemprop="priceCurrency" content="USD">
													<p class="price" itemprop="price" content="3499.99">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
													<link itemprop="availability" href="http://schema.org/InStock" content="In stock" />
												</div>
												<div class="product-rebate">
													<!-- 2015-05-27 Ecorebates
														data-modelId : 제품 ID
														class : ecorebates-div 필수
													-->
													<div class="ecorebates-div" data-modelId="WM3170CW"></div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li itemscope itemtype="http://schema.org/Product">
									<a href="#" class="img-link">
										<!-- 2015-06-22 lazy load 적용 -->
										<img alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" style="opacity: 1;">
									</a>
									<div class="copy-area">
										<p class="model-name" itemprop="name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
										<p class="model-num"><a href="#">55EA9800</a></p>
										<!-- <p class="model-size"><a href="#">Sizes:65"</a> | <a href="#">55"</a> |<a href="#" class="etcSize">105"</a></p> -->
										<div class="details">
											<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" data-modelid="MD00001295">
												<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
												<meta itemprop="bestRating" content="5" />
												<meta itemprop="worstRating" content="1" />
												<div class="points_wrap">
													<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
													<meta itemprop="ratingValue" content="2.5" />
												</div>
												<span itemprop="reviewCount" content="9"><a href="#">(9 Reviews)</a></span><!-- 2015-06-02 link -->
											</div>
											<p class="compare-check">
												<label>
													<input type="checkbox" class="compare" data-product-id="LRG3088ST" name="compare"><span>Add to Compare</span>
												</label>
												<span class="compare_y hide"><a href="/compare_d.html">COMPARE (<em>1</em>)</a></span>
											</p>
											<div class="cta cta-button">
												<a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to buy</a>
											</div>
											<div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
												<!-- 2015-06-01 promotional-price 가 있는 경우
												<div class="suggested-price">
													<p class="price">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
												</div>
												<div class="promotional-price">
													<p class="price">$1499.<span>99</span></p>
													<p class="legal">Promotional Price</p>
												</div>
												-->
												<div class="purchase-price"  itemprop="priceCurrency" content="USD">
													<p class="price" itemprop="price" content="3499.99">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
													<link itemprop="availability" href="http://schema.org/InStock" content="In stock" />
												</div>
												<div class="product-rebate">
													<!-- 2015-05-27 Ecorebates
														data-modelId : 제품 ID
														class : ecorebates-div 필수
													-->
													<div class="ecorebates-div" data-modelId="WM3170CW"></div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li itemscope itemtype="http://schema.org/Product">
									<a href="#" class="img-link">
										<!-- 2015-06-22 lazy load 적용 -->
										<img alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" style="opacity: 1;">
									</a>
									<div class="copy-area">
										<p class="model-name" itemprop="name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
										<p class="model-num"><a href="#">55EA9800</a></p>
										<!-- <p class="model-size"><a href="#">Sizes:65"</a></p> -->
										<div class="details">
											<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" data-modelid="MD00001296">
												<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
												<meta itemprop="bestRating" content="5" />
												<meta itemprop="worstRating" content="1" />
												<div class="points_wrap">
													<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
													<meta itemprop="ratingValue" content="2.5" />
												</div>
												<span itemprop="reviewCount" content="9"><a href="#">(9 Reviews)</a></span><!-- 2015-06-02 link -->
											</div>
											<p class="compare-check">
												<label>
													<input type="checkbox" class="compare" data-product-id="LRG3082ST" name="compare"><span>Add to Compare</span>
												</label>
												<span class="compare_y hide"><a href="/compare_d.html">COMPARE (<em>1</em>)</a></span>
											</p>
											<div class="cta cta-button">
												<a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to buy</a>
											</div>
											<div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
												<!-- 2015-06-01 promotional-price 가 있는 경우
												<div class="suggested-price">
													<p class="price">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
												</div>
												<div class="promotional-price">
													<p class="price">$1499.<span>99</span></p>
													<p class="legal">Promotional Price</p>
												</div>
												-->
												<div class="purchase-price"  itemprop="priceCurrency" content="USD">
													<p class="price" itemprop="price" content="3499.99">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
													<link itemprop="availability" href="http://schema.org/InStock" content="In stock" />
												</div>
												<div class="product-rebate">
													<!-- 2015-05-27 Ecorebates
														data-modelId : 제품 ID
														class : ecorebates-div 필수
													-->
													<div class="ecorebates-div" data-modelId="WM3170CW"></div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li itemscope itemtype="http://schema.org/Product">
									<a href="#" class="img-link">
										<!-- 2015-06-22 lazy load 적용 -->
										<img alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" style="opacity: 1;">
									</a>
									<div class="copy-area">
										<p class="model-name" itemprop="name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
										<p class="model-num"><a href="#">55EA9800</a></p>
										<!-- <p class="model-size"><a href="#">Sizes:65"</a></p> -->
										<div class="details">
											<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" data-modelid="MD00001297">
												<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
												<meta itemprop="bestRating" content="5" />
												<meta itemprop="worstRating" content="1" />
												<div class="points_wrap">
													<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
													<meta itemprop="ratingValue" content="2.5" />
												</div>
												<span itemprop="reviewCount" content="9"><a href="#">(9 Reviews)</a></span><!-- 2015-06-02 link -->
											</div>
											<p class="compare-check">
												<label>
													<input type="checkbox" class="compare" data-product-id="LRG3083ST" name="compare"><span>Add to Compare</span>
												</label>
												<span class="compare_y hide"><a href="/compare_d.html">COMPARE (<em>1</em>)</a></span>
											</p>
											<div class="cta cta-button">
												<a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to buy</a>
											</div>
											<div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
												<!-- 2015-06-01 promotional-price 가 있는 경우
												<div class="suggested-price">
													<p class="price">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
												</div>
												<div class="promotional-price">
													<p class="price">$1499.<span>99</span></p>
													<p class="legal">Promotional Price</p>
												</div>
												-->
												<div class="purchase-price"  itemprop="priceCurrency" content="USD">
													<p class="price" itemprop="price" content="3499.99">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
													<link itemprop="availability" href="http://schema.org/InStock" content="In stock" />
												</div>
												<div class="product-rebate">
													<!-- 2015-05-27 Ecorebates
														data-modelId : 제품 ID
														class : ecorebates-div 필수
													-->
													<div class="ecorebates-div" data-modelId="WM3170CW"></div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li itemscope itemtype="http://schema.org/Product">
									<a href="#" class="img-link">
										<!-- 2015-06-22 lazy load 적용 -->
										<img alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" style="opacity: 1;">
									</a>
									<div class="copy-area">
										<p class="model-name" itemprop="name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
										<p class="model-num"><a href="#">55EA9800</a></p>
										<!-- <p class="model-size"><a href="#">Sizes:65"</a></p> -->
										<div class="details">
											<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" data-modelid="MD00001298">
												<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
												<meta itemprop="bestRating" content="5" />
												<meta itemprop="worstRating" content="1" />
												<div class="points_wrap">
													<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
													<meta itemprop="ratingValue" content="2.5" />
												</div>
												<span itemprop="reviewCount" content="9"><a href="#">(9 Reviews)</a></span><!-- 2015-06-02 link -->
											</div>
											<p class="compare-check">
												<label>
													<input type="checkbox" class="compare" data-product-id="LRG3084ST" name="compare"><span>Add to Compare</span>
												</label>
												<span class="compare_y hide"><a href="/compare_d.html">COMPARE (<em>1</em>)</a></span>
											</p>
											<div class="cta cta-button">
												<a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to buy</a>
											</div>
											<div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
												<!-- 2015-06-01 promotional-price 가 있는 경우
												<div class="suggested-price">
													<p class="price">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
												</div>
												<div class="promotional-price">
													<p class="price">$1499.<span>99</span></p>
													<p class="legal">Promotional Price</p>
												</div>
												-->
												<div class="purchase-price"  itemprop="priceCurrency" content="USD">
													<p class="price" itemprop="price" content="3499.99">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
													<link itemprop="availability" href="http://schema.org/InStock" content="In stock" />
												</div>
												<div class="product-rebate">
													<!-- 2015-05-27 Ecorebates
														data-modelId : 제품 ID
														class : ecorebates-div 필수
													-->
													<div class="ecorebates-div" data-modelId="WM3170CW"></div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li itemscope itemtype="http://schema.org/Product">
									<a href="#" class="img-link">
										<!-- 2015-06-22 lazy load 적용 -->
										<img alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" style="opacity: 1;">
									</a>
									<div class="copy-area">
										<p class="model-name" itemprop="name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
										<p class="model-num"><a href="#">55EA9800</a></p>
										<!-- <p class="model-size"><a href="#">Sizes:65"</a></p> -->
										<div class="details">
											<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" data-modelid="MD00001299">
												<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
												<meta itemprop="bestRating" content="5" />
												<meta itemprop="worstRating" content="1" />
												<div class="points_wrap">
													<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
													<meta itemprop="ratingValue" content="2.5" />
												</div>
												<span itemprop="reviewCount" content="9"><a href="#">(9 Reviews)</a></span><!-- 2015-06-02 link -->
											</div>
											<p class="compare-check">
												<label>
													<input type="checkbox" class="compare" data-product-id="LRG3085ST" name="compare"><span>Add to Compare</span>
												</label>
												<span class="compare_y hide"><a href="/compare_d.html">COMPARE (<em>1</em>)</a></span>
											</p>
											<div class="cta cta-button">
												<a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to buy</a>
											</div>
											<div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
												<!-- 2015-06-01 promotional-price 가 있는 경우
												<div class="suggested-price">
													<p class="price">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
												</div>
												<div class="promotional-price">
													<p class="price">$1499.<span>99</span></p>
													<p class="legal">Promotional Price</p>
												</div>
												-->
												<div class="purchase-price"  itemprop="priceCurrency" content="USD">
													<p class="price" itemprop="price" content="3499.99">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
													<link itemprop="availability" href="http://schema.org/InStock" content="In stock" />
												</div>
												<div class="product-rebate">
													<!-- 2015-05-27 Ecorebates
														data-modelId : 제품 ID
														class : ecorebates-div 필수
													-->
													<div class="ecorebates-div" data-modelId="WM3170CW"></div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li itemscope itemtype="http://schema.org/Product">
									<a href="#" class="img-link">
										<!-- 2015-06-22 lazy load 적용 -->
										<img alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" style="opacity: 1;">
									</a>
									<div class="copy-area">
										<p class="model-name" itemprop="name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
										<p class="model-num"><a href="#">55EA9800</a></p>
										<!-- <p class="model-size"><a href="#">Sizes:65"</a></p> -->
										<div class="details">
											<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" data-modelid="MD00001300">
												<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
												<meta itemprop="bestRating" content="5" />
												<meta itemprop="worstRating" content="1" />
												<div class="points_wrap">
													<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
													<meta itemprop="ratingValue" content="2.5" />
												</div>
												<span itemprop="reviewCount" content="9"><a href="#">(9 Reviews)</a></span><!-- 2015-06-02 link -->
											</div>
											<p class="compare-check">
												<label>
													<input type="checkbox" class="compare" data-product-id="LRG3086ST" name="compare"><span>Add to Compare</span>
												</label>
												<span class="compare_y hide"><a href="/compare_d.html">COMPARE (<em>1</em>)</a></span>
											</p>
											<div class="cta cta-button">
												<a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to buy</a>
											</div>
											<div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
												<!-- 2015-06-01 promotional-price 가 있는 경우
												<div class="suggested-price">
													<p class="price">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
												</div>
												<div class="promotional-price">
													<p class="price">$1499.<span>99</span></p>
													<p class="legal">Promotional Price</p>
												</div>
												-->
												<div class="purchase-price"  itemprop="priceCurrency" content="USD">
													<p class="price" itemprop="price" content="3499.99">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
													<link itemprop="availability" href="http://schema.org/InStock" content="In stock" />
												</div>
												<div class="product-rebate">
													<!-- 2015-05-27 Ecorebates
														data-modelId : 제품 ID
														class : ecorebates-div 필수
													-->
													<div class="ecorebates-div" data-modelId="WM3170CW"></div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li itemscope itemtype="http://schema.org/Product">
									<a href="#" class="img-link">
										<!-- 2015-06-22 lazy load 적용 -->
										<img alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" style="opacity: 1;">
									</a>
									<div class="copy-area">
										<p class="model-name" itemprop="name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
										<p class="model-num"><a href="#">55EA9800</a></p>
										<!-- <p class="model-size"><a href="#">Sizes:65"</a></p> -->
										<div class="details">
											<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" data-modelid="MD00001301">
												<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
												<meta itemprop="bestRating" content="5" />
												<meta itemprop="worstRating" content="1" />
												<div class="points_wrap">
													<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
													<meta itemprop="ratingValue" content="2.5" />
												</div>
												<span itemprop="reviewCount" content="9"><a href="#">(9 Reviews)</a></span><!-- 2015-06-02 link -->
											</div>
											<p class="compare-check">
												<label>
													<input type="checkbox" class="compare" data-product-id="LRG3087ST" name="compare"><span>Add to Compare</span>
												</label>
												<span class="compare_y hide"><a href="/compare_d.html">COMPARE (<em>1</em>)</a></span>
											</p>
											<div class="cta cta-button">
												<a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to buy</a>
											</div>
											<div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
												<!-- 2015-06-01 promotional-price 가 있는 경우
												<div class="suggested-price">
													<p class="price">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
												</div>
												<div class="promotional-price">
													<p class="price">$1499.<span>99</span></p>
													<p class="legal">Promotional Price</p>
												</div>
												-->
												<div class="purchase-price"  itemprop="priceCurrency" content="USD">
													<p class="price" itemprop="price" content="3499.99">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
													<link itemprop="availability" href="http://schema.org/InStock" content="In stock" />
												</div>
												<div class="product-rebate">
													<!-- 2015-05-27 Ecorebates
														data-modelId : 제품 ID
														class : ecorebates-div 필수
													-->
													<div class="ecorebates-div" data-modelId="WM3170CW"></div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li itemscope itemtype="http://schema.org/Product">
									<a href="#" class="img-link">
										<!-- 2015-06-22 lazy load 적용 -->
										<img alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" style="opacity: 1;">
									</a>
									<div class="copy-area">
										<p class="model-name" itemprop="name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
										<p class="model-num"><a href="#">55EA9800</a></p>
										<!-- <p class="model-size"><a href="#">Sizes:65"</a></p> -->
										<div class="details">
											<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" data-modelid="MD00001302">
												<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
												<meta itemprop="bestRating" content="5" />
												<meta itemprop="worstRating" content="1" />
												<div class="points_wrap">
													<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
													<meta itemprop="ratingValue" content="2.5" />
												</div>
												<span itemprop="reviewCount" content="9"><a href="#">(9 Reviews)</a></span><!-- 2015-06-02 link -->
											</div>
											<p class="compare-check">
												<label>
													<input type="checkbox" class="compare" data-product-id="LRG3088ST" name="compare"><span>Add to Compare</span>
												</label>
												<span class="compare_y hide"><a href="/compare_d.html">COMPARE (<em>1</em>)</a></span>
											</p>
											<div class="cta cta-button">
												<a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to buy</a>
											</div>
											<div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
												<!-- 2015-06-01 promotional-price 가 있는 경우
												<div class="suggested-price">
													<p class="price">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
												</div>
												<div class="promotional-price">
													<p class="price">$1499.<span>99</span></p>
													<p class="legal">Promotional Price</p>
												</div>
												-->
												<div class="purchase-price"  itemprop="priceCurrency" content="USD">
													<p class="price" itemprop="price" content="3499.99">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
													<link itemprop="availability" href="http://schema.org/InStock" content="In stock" />
												</div>
												<div class="product-rebate">
													<!-- 2015-05-27 Ecorebates
														data-modelId : 제품 ID
														class : ecorebates-div 필수
													-->
													<div class="ecorebates-div" data-modelId="WM3170CW"></div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li itemscope itemtype="http://schema.org/Product">
									<a href="#" class="img-link">
										<!-- 2015-06-22 lazy load 적용 -->
										<img alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" style="opacity: 1;">
									</a>
									<div class="copy-area">
										<p class="model-name" itemprop="name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
										<p class="model-num"><a href="#">55EA9800</a></p>
										<!-- <p class="model-size"><a href="#">Sizes:65"</a></p> -->
										<div class="details">
											<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" data-modelid="MD00001303">
												<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
												<meta itemprop="bestRating" content="5" />
												<meta itemprop="worstRating" content="1" />
												<div class="points_wrap">
													<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
													<meta itemprop="ratingValue" content="2.5" />
												</div>
												<span itemprop="reviewCount" content="9"><a href="#">(9 Reviews)</a></span><!-- 2015-06-02 link -->
											</div>
											<p class="compare-check">
												<label>
													<input type="checkbox" class="compare" data-product-id="LRG3082ST" name="compare"><span>Add to Compare</span>
												</label>
												<span class="compare_y hide"><a href="/compare_d.html">COMPARE (<em>1</em>)</a></span>
											</p>
											<div class="cta cta-button">
												<a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to buy</a>
											</div>
											<div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
												<!-- 2015-06-01 promotional-price 가 있는 경우
												<div class="suggested-price">
													<p class="price">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
												</div>
												<div class="promotional-price">
													<p class="price">$1499.<span>99</span></p>
													<p class="legal">Promotional Price</p>
												</div>
												-->
												<div class="purchase-price"  itemprop="priceCurrency" content="USD">
													<p class="price" itemprop="price" content="3499.99">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
													<link itemprop="availability" href="http://schema.org/InStock" content="In stock" />
												</div>
												<div class="product-rebate">
													<!-- 2015-05-27 Ecorebates
														data-modelId : 제품 ID
														class : ecorebates-div 필수
													-->
													<div class="ecorebates-div" data-modelId="WM3170CW"></div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li itemscope itemtype="http://schema.org/Product">
									<a href="#" class="img-link">
										<!-- 2015-06-22 lazy load 적용 -->
										<img alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" style="opacity: 1;">
									</a>
									<div class="copy-area">
										<p class="model-name" itemprop="name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
										<p class="model-num"><a href="#">55EA9800</a></p>
										<!-- <p class="model-size"><a href="#">Sizes:65"</a></p> -->
										<div class="details">
											<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" data-modelid="MD00001304">
												<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
												<meta itemprop="bestRating" content="5" />
												<meta itemprop="worstRating" content="1" />
												<div class="points_wrap">
													<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
													<meta itemprop="ratingValue" content="2.5" />
												</div>
												<span itemprop="reviewCount" content="9"><a href="#">(9 Reviews)</a></span><!-- 2015-06-02 link -->
											</div>
											<p class="compare-check">
												<label>
													<input type="checkbox" class="compare" data-product-id="LRG3083ST" name="compare"><span>Add to Compare</span>
												</label>
												<span class="compare_y hide"><a href="/compare_d.html">COMPARE (<em>1</em>)</a></span>
											</p>
											<div class="cta cta-button">
												<a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to buy</a>
											</div>
											<div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
												<!-- 2015-06-01 promotional-price 가 있는 경우
												<div class="suggested-price">
													<p class="price">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
												</div>
												<div class="promotional-price">
													<p class="price">$1499.<span>99</span></p>
													<p class="legal">Promotional Price</p>
												</div>
												-->
												<div class="purchase-price"  itemprop="priceCurrency" content="USD">
													<p class="price" itemprop="price" content="3499.99">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
													<link itemprop="availability" href="http://schema.org/InStock" content="In stock" />
												</div>
												<div class="product-rebate">
													<!-- 2015-05-27 Ecorebates
														data-modelId : 제품 ID
														class : ecorebates-div 필수
													-->
													<div class="ecorebates-div" data-modelId="WM3170CW"></div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li itemscope itemtype="http://schema.org/Product">
									<a href="#" class="img-link">
										<!-- 2015-06-22 lazy load 적용 -->
										<img alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" style="opacity: 1;">
									</a>
									<div class="copy-area">
										<p class="model-name" itemprop="name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
										<p class="model-num"><a href="#">55EA9800</a></p>
										<!-- <p class="model-size"><a href="#">Sizes:65"</a></p> -->
										<div class="details">
											<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" data-modelid="MD00001305">
												<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
												<meta itemprop="bestRating" content="5" />
												<meta itemprop="worstRating" content="1" />
												<div class="points_wrap">
													<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
													<meta itemprop="ratingValue" content="2.5" />
												</div>
												<span itemprop="reviewCount" content="9"><a href="#">(9 Reviews)</a></span><!-- 2015-06-02 link -->
											</div>
											<p class="compare-check">
												<label>
													<input type="checkbox" class="compare" data-product-id="LRG3084ST" name="compare"><span>Add to Compare</span>
												</label>
												<span class="compare_y hide"><a href="/compare_d.html">COMPARE (<em>1</em>)</a></span>
											</p>
											<div class="cta cta-button">
												<a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to buy</a>
											</div>
											<div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
												<!-- 2015-06-01 promotional-price 가 있는 경우
												<div class="suggested-price">
													<p class="price">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
												</div>
												<div class="promotional-price">
													<p class="price">$1499.<span>99</span></p>
													<p class="legal">Promotional Price</p>
												</div>
												-->
												<div class="purchase-price"  itemprop="priceCurrency" content="USD">
													<p class="price" itemprop="price" content="3499.99">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
													<link itemprop="availability" href="http://schema.org/InStock" content="In stock" />
												</div>
												<div class="product-rebate">
													<!-- 2015-05-27 Ecorebates
														data-modelId : 제품 ID
														class : ecorebates-div 필수
													-->
													<div class="ecorebates-div" data-modelId="WM3170CW"></div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li itemscope itemtype="http://schema.org/Product">
									<a href="#" class="img-link">
										<!-- 2015-06-22 lazy load 적용 -->
										<img alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" style="opacity: 1;">
									</a>
									<div class="copy-area">
										<p class="model-name" itemprop="name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
										<p class="model-num"><a href="#">55EA9800</a></p>
										<!-- <p class="model-size"><a href="#">Sizes:65"</a></p> -->
										<div class="details">
											<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" data-modelid="MD00001306">
												<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
												<meta itemprop="bestRating" content="5" />
												<meta itemprop="worstRating" content="1" />
												<div class="points_wrap">
													<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
													<meta itemprop="ratingValue" content="2.5" />
												</div>
												<span itemprop="reviewCount" content="9"><a href="#">(9 Reviews)</a></span><!-- 2015-06-02 link -->
											</div>
											<p class="compare-check">
												<label>
													<input type="checkbox" class="compare" data-product-id="LRG3085ST" name="compare"><span>Add to Compare</span>
												</label>
												<span class="compare_y hide"><a href="/compare_d.html">COMPARE (<em>1</em>)</a></span>
											</p>
											<div class="cta cta-button">
												<a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to buy</a>
											</div>
											<div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
												<!-- 2015-06-01 promotional-price 가 있는 경우
												<div class="suggested-price">
													<p class="price">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
												</div>
												<div class="promotional-price">
													<p class="price">$1499.<span>99</span></p>
													<p class="legal">Promotional Price</p>
												</div>
												-->
												<div class="purchase-price"  itemprop="priceCurrency" content="USD">
													<p class="price" itemprop="price" content="3499.99">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
													<link itemprop="availability" href="http://schema.org/InStock" content="In stock" />
												</div>
												<div class="product-rebate">
													<!-- 2015-05-27 Ecorebates
														data-modelId : 제품 ID
														class : ecorebates-div 필수
													-->
													<div class="ecorebates-div" data-modelId="WM3170CW"></div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li itemscope itemtype="http://schema.org/Product">
									<a href="#" class="img-link">
										<!-- 2015-06-22 lazy load 적용 -->
										<img alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" style="opacity: 1;">
									</a>
									<div class="copy-area">
										<p class="model-name" itemprop="name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
										<p class="model-num"><a href="#">55EA9800</a></p>
										<!-- <p class="model-size"><a href="#">Sizes:65"</a></p> -->
										<div class="details">
											<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" data-modelid="MD00001307">
												<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
												<meta itemprop="bestRating" content="5" />
												<meta itemprop="worstRating" content="1" />
												<div class="points_wrap">
													<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
													<meta itemprop="ratingValue" content="2.5" />
												</div>
												<span itemprop="reviewCount" content="9"><a href="#">(9 Reviews)</a></span><!-- 2015-06-02 link -->
											</div>
											<p class="compare-check">
												<label>
													<input type="checkbox" class="compare" data-product-id="LRG3086ST" name="compare"><span>Add to Compare</span>
												</label>
												<span class="compare_y hide"><a href="/compare_d.html">COMPARE (<em>1</em>)</a></span>
											</p>
											<div class="cta cta-button">
												<a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to buy</a>
											</div>
											<div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
												<!-- 2015-06-01 promotional-price 가 있는 경우
												<div class="suggested-price">
													<p class="price">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
												</div>
												<div class="promotional-price">
													<p class="price">$1499.<span>99</span></p>
													<p class="legal">Promotional Price</p>
												</div>
												-->
												<div class="purchase-price"  itemprop="priceCurrency" content="USD">
													<p class="price" itemprop="price" content="3499.99">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
													<link itemprop="availability" href="http://schema.org/InStock" content="In stock" />
												</div>
												<div class="product-rebate">
													<!-- 2015-05-27 Ecorebates
														data-modelId : 제품 ID
														class : ecorebates-div 필수
													-->
													<div class="ecorebates-div" data-modelId="WM3170CW"></div>
												</div>
											</div>
										</div>
									</div>
								</li>
								<li itemscope itemtype="http://schema.org/Product">
									<a href="#" class="img-link">
										<!-- 2015-06-22 lazy load 적용 -->
										<img alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" style="opacity: 1;">
									</a>
									<div class="copy-area">
										<p class="model-name" itemprop="name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
										<p class="model-num"><a href="#">55EA9800</a></p>
										<!-- <p class="model-size"><a href="#">Sizes:65"</a></p> -->
										<div class="details">
											<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating" data-modelid="MD00001308">
												<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
												<meta itemprop="bestRating" content="5" />
												<meta itemprop="worstRating" content="1" />
												<div class="points_wrap">
													<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
													<meta itemprop="ratingValue" content="2.5" />
												</div>
												<span itemprop="reviewCount" content="9"><a href="#">(9 Reviews)</a></span><!-- 2015-06-02 link -->
											</div>
											<p class="compare-check">
												<label>
													<input type="checkbox" class="compare" data-product-id="LRG3087ST" name="compare"><span>Add to Compare</span>
												</label>
												<span class="compare_y hide"><a href="/compare_d.html">COMPARE (<em>1</em>)</a></span>
											</p>
											<div class="cta cta-button">
												<a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}">Where to buy</a>
											</div>
											<div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
												<!-- 2015-06-01 promotional-price 가 있는 경우
												<div class="suggested-price">
													<p class="price">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
												</div>
												<div class="promotional-price">
													<p class="price">$1499.<span>99</span></p>
													<p class="legal">Promotional Price</p>
												</div>
												-->
												<div class="purchase-price"  itemprop="priceCurrency" content="USD">
													<p class="price" itemprop="price" content="3499.99">$3499.<span>99</span></p>
													<p class="legal">Suggested Price</p>
													<link itemprop="availability" href="http://schema.org/InStock" content="In stock" />
												</div>
												<div class="product-rebate">
													<!-- 2015-05-27 Ecorebates
														data-modelId : 제품 ID
														class : ecorebates-div 필수
													-->
													<div class="ecorebates-div" data-modelId="WM3170CW"></div>
												</div>
											</div>
										</div>
									</div>
								</li>
							</ul>
						</div>
					</div>
					<!-- 2015-05-17 bottom 클래스 추가 -->
					<div class="page-controls bottom">
						<span class="sort">
							<!-- 2015-05-21 id변경, sort-select 클래스 추가 name 속성 추가 // -->
							<label for="sortBy2">Sort by:</label>
							<select id="sortBy2" class="sort-select">
								<option value="0">Newest Products</option>
								<option value="1">Most Popular</option>
								<option value="2">Price: Lowest to Highest</option>
								<option value="3">Price: Highest to Lowest</option>
								<option value="4">LG Picks</option>
								<option value="5">Consumer Rating</option>
							</select>
						</span>
						<span class="pages">
							<a href="#" class="prev"><i class="icon icon-arrow-prev"></i></a>
							<a href="#" class="active">1</a>
							<a href="#">2</a>
							<a href="#">3</a>
							<a href="#">4</a>
							<a href="#" class="next"><i class="icon icon-arrow-next"></i></a>
							<a href="/us/tvs/all-tvs/view-all"  data-uri="/us/facet/filter.lg?viewAll=tvs/all-tvs&mstId=CT10000018&subId=CT10000018&page=0&sort=0&bvApiUrl=http://lg.ugc.bazaarvoice.com/static/7676-en_us/bvapi.js&&SEARCH_FT00000003_min=&SEARCH_FT00000001_03=FV06942348&SEARCH_FT00000001_01=FV06942350&SEARCH_FT00000003_max=&SEARCH_FT00000001_02=FV06942347&SEARCH_FT00000005_max=&SEARCH_FT00000005_min=" class="view-all ">View All</a>
						</span>
					</div>
				</div>
			</section>
		</div>
	</form>
</section>