<div class="error-page"><!-- 2015-08-31 -->
	<div class="error-wrap">
		<div class="error-image">
			<div class="table-box">
				<span><img src="/lg4-common/img/global/error/error-logo.jpg" alt="LG" /></span>
			</div>
		</div>
		<div class="error-comment">
			<h1>
				We're sorry. <span>The page you requested does not exist</span>
			</h1>
			<p>
				The page you requested is not available. If you're still having problems finding a destination on our site, please go to our home page or view our site map.
			</p>
			<p>
				We want to help you find what you are looking for.
			</p>
			<p>
				<a href="#">Click here to go to LG Electronics immediately.</a>
			</p>
		</div>
	</div>
</div>
