<!-- 2015-06-10 class 중 read-more 삭제됨 -->
<section class="footer-seo grey-background" data-characters-to-show="189">
	<div class="content-container">
		<!-- 2015-05-20 추가됨 -->
		<!-- PDP 페이지에서만 출력됩니다. -->
		<p class="text-full"><sup>1</sup> Fast Charge supported when using the 15W wall charger included in the box with G Flex2.<br><sup>2</sup> When compared to 800 and 801 series processors.</p>
		<hr>
		<!-- 2015-08-18 p 태그가 div.p로 수정됨. -->
		<div class="p"><p><h1>Electronics & Appliances</h1> Life's more than having the latest technology. It's about the experiences technology creates. From <a href="#">TVs</a> and <a href="#">home appliances</a> to <a href="#">cell phones</a> and <a href="#">computer products</a>, LG delivers consumer electronics that allow you to embrace life and prepare you for its greatest moments.  LG electronics are designed to be intuitive, responsive and <a href="#">energy efficient</a> so you can spend wisely, be more productive and lessen the impact on the world around you. We're committed to providing electronics that work best for the way you live and to keeping you updated with the latest technological advances. After all, life's better when you're prepared.</p></div>
		<hr />
		<div class="p"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec at nisl vehicula, posuere lectus ut, ultrices massa. Aliquam faucibus neque ut mauris luctus commodo. Curabitur scelerisque vehicula purus, vitae vulputate lorem convallis sed. Aenean leo ante, tempus vel quam non, congue porta quam. Maecenas in ultrices elit, tincidunt vestibulum ante. Aenean bibendum scelerisque eleifend. Donec laoreet est est, sed tinc.</div>
	</div>
</section>