<div class="key-feature">
	<div class="feature-wrap">
		<div class="feature-box">
			<h4>Key Features</h4>
			<ul class="features">
				<li>Highest Color Fidelity of Any TV</li>
				<li>Curved Display for Maximum Immersion</li>
				<li>Works for Many Room Types</li>
				<li>Pencil Thin</li>
			</ul>
		</div>
		<div class="feature-box sizes">
			<h5>AVAILABLE SIZES:</h5>
			<ul class="list-sizes">
				<li class="active"><a href="#">55&rdquo;</a></li>
				<li><a href="#">60&rdquo;</a></li>
				<li><a href="#">65&rdquo;</a></li>
			</ul>
		</div>
		<div class="feature-box colors">
			<h5>AVAILABLE COLORS:</h5>
			<ul class="list_colors">
				<!-- 2015-06-04 -->
				<li itemprop="color" class="active"><a href="#"><span class="color_chip_cover"></span><span class="swatch large stainless-steel"></span>Real Stainless Steel</a></li>
				<li itemprop="color" ><a href="#"><span class="swatch large smooth-black"></span>Smooth Black</a></li>
				<li itemprop="color" ><a href="#"><span class="swatch large smooth-white"></span>Smooth White</a></li>
				<!-- 2015-06-04 -->
			</ul>
		</div>
	</div>
</div>