<!-- M01A -->
<!--
	Requred Class : .module .m01
	Options : 
	- Light/Dark text : .text-light / .text-dark
	- Top/Bottom text placement : .text-top / .text-bottom
-->
<section class="module m01 text-dark text-top">
	<!-- 5. Full Bleed Background -->
	<div class="background-image">
		<!-- 개발시에는, 이미지에 only-mobile, only-desktop 클래스를 삭제 해 주시고(lazy는 유지), Desktop/Mobile 여부에 따라, 이미지는 1개만 출력 시켜주세요. -->
		<img class="lazy only-mobile" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/M01_01_m.jpg" alt="OLED TVs - Unmatched Color Realism" />
		<img class="lazy only-desktop" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/M01_01.jpg" alt="OLED TVs - Unmatched Color Realism" />
	</div>
	<div class="text-block">
		<!-- 1. Eyebrow --><h4>LOREM IPSUM DOLOR SIT AMET, CONSECTET 40</h4>
		<!-- 2. Headline --><h3>Lorem ipsum dolor sit amet, co 33</h3>
		<!-- 3. Body Copy -->
		<p>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nost 162
		</p>
		<!-- 4. CTA (링크가 1개일때) -->
		<div class="cta cta-button">
			<a href="#" class="btn">Learn More</a>
		</div>
	</div>
</section>
<section class="module m01 text-dark text-top">
	<!-- 5. Full Bleed Background -->
	<div class="background-image">
		<!-- 개발시에는, 이미지에 only-mobile, only-desktop 클래스를 삭제 해 주시고(lazy는 유지), Desktop/Mobile 여부에 따라, 이미지는 1개만 출력 시켜주세요. -->
		<img class="lazy only-mobile" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/M01_01_m.jpg" alt="OLED TVs - Unmatched Color Realism" />
		<img class="lazy only-desktop" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/M01_01.jpg" alt="OLED TVs - Unmatched Color Realism" />
	</div>
	<div class="text-block">
		<!-- 1. Eyebrow --><h4>OLED TVS</h4>
		<!-- 2. Headline --><h3>Unmatched Color Realism</h3>
		<!-- 3. Body Copy -->
		<p>
			LG OLED TVs have an infinite contrast ratio that displays the whitest whites to the deepest blacks for the ultimate sense of realism.
		</p>
		<!-- 4. CTA (링크가 2개 이상일때) -->
		<div class="cta cta-text">
			<a href="#">Learn More <i class="icon icon-arrow-link"></i></a>
			<a href="#">Shop OLED TVs <i class="icon icon-arrow-link"></i></a>
		</div>
	</div>
</section>