<!-- M04A -->
<!--
	Requred Class : .module .m04 .text-banner .one-column
-->
<!-- 모듈 구분을 위해 .module .m04  추가함. -->
<section class="module m04 text-banner one-column">
	<div>
		<div class="content-container">
			<!-- 3. Inset Image --><div class="inset"><img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/M04_02.jpg" alt="Thoughtful Design Details"></div><!-- 2015-04-29 add inset div -->
			<!-- 2015-04-29
				Inset Image Size 
				가로 150~240 px, 세로 150px 
			-->
			<!-- 1. Headline --><h3>Thoughtful Design Details</h3>
			<!-- 2. Body Copy --><p>For those quick trips to the fridge, the Door-in-Door is a magnetically sealed section that allows you to access the door bin for easy access to your favorite snacks without opening the entire refrigerator. Whether it's a refreshing drink or a healthy snack, the Door-in-Door is the ideal space for your family's go-to foods such as canned or bottled drinks. Luxe features like contoured doors, hidden buttons and hinges, and LED lighting make the LG Dual Door-in-Door a pleasure to see and touch.</p>
		</div>
	</div>
</section>