<!-- M04B -->
<!--
	Requred Class : .module .m04 .text-banner .two-column
-->
<!-- 모듈 구분을 위해 .module .m04  추가함. -->
<section class="module m04 text-banner two-column">
	<ul>
		<li>
			<!-- 1. Headline --><h3>ENERGY STAR&reg; Qualified</h3>
			<!-- 3. Inset Image --><div class="inset"><img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/M01_05.jpg" alt="ENERGY STAR" /></div><!-- 2015-04-29 add .inset div -->
			<!-- 2015-04-29
				Inset Image Size
				가로 150~240 px, 세로 150px 
			-->
			<!-- 2. Body Copy --><p>Earning the ENERGY STAR&reg; means a product meets strict energy efficiency guidelines set by the US Environmental Protection Agency and the Department of Energy. ENERGY STAR® certified televisions are on average, over 25 percent more energy efficient.</p>
		</li>
		<li>
			<!-- 4. Headline 2 --><h3>Built-in WiFi&reg;</h3>
			<!-- 6. Inset Image 2 --><div class="inset"><img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/M04_01.jpg" alt="Wi-Fi" /></div><!-- 2015-04-29 add .inset div -->
			<!-- 5. Body Copy 2 --><p>Less clutter. More possibilities. Cut loose from messy wires. Integrated Wi-Fi Connectivity allows you to take advantage of Internet Entertainment Access from any available Wi-Fi connection, anywhere in its range.</p>
		</li>
	</ul>
</section>