<!-- M04C -->
<!--
	Requred Class : .module .m04 .text-banner .three-column
-->
<!-- 모듈 구분을 위해 .module .m04  추가함. -->
<section class="module m04 text-banner three-column">
	<ul>
		<li>
			<!-- 1. Headline --><h3>Energy Star<sup>&reg;</sup> Qualified</h3>
			<!-- 3. Inset Image --><div class="inset"><img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/M04_02.png" alt="Energy Star Qualified" /></div><!-- 2015-04-29 add .inset div -->
			<!-- 2015-04-29
				Inset Image Size
				가로 150~240 px, 세로 150px 
			--> 
			<!-- 2. Body Copy -->
			<div class="desc">
				<div class="more"><button type="button"><span>See More Energy Star Qualified</span><i class="icon icon-menu-plus"></i></button></div>
				<p>At least 20% more energy-efficient than government standards.</p>
			</div>
		</li>
		<li>
			<!-- 4. Headline 2 --><h3>10-Year Warranty</h3>
			<!-- 6. Inset Image 2 --><div class="inset"><img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/M01_05.jpg" alt="10-Year Warranty" /></div><!-- 2015-04-29 add .inset div -->
			<!-- 5. Body Copy 2 -->
			<div class="desc">
				<div class="more"><button type="button"><span>See More 10-Year Warranty</span><i class="icon icon-menu-plus"></i></button></div>
				<p>The Inverter Linear Compressor is so reliable that we back it with a 10-year limited warranty.</p>
			</div>
		</li>
		<li>
			<!-- 7. Headline 3 --><h3>Seal of Approval</h3>
			<!-- 9. Inset Image 3 --><div class="inset"><img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/M04_02.png" alt="Seal of Approval" /></div><!-- 2015-04-29 add .inset div -->
			<!-- 8. Body Copy 3 -->
			<div class="desc">
				<div class="more"><button type="button"><span>See More Seal of Approval</span><i class="icon icon-menu-plus"></i></button></div>
				<p>Good Housekeeping is so confident in LG quality that it has awarded this refrigerator its Seal of Approval.</p>
			</div>
		</li>
	</ul>
</section>