<!-- M05 -->
<!--
	Requred Class : .module .m05 .call-to-action, .with-carousel .dot-line
-->
<!-- 모듈 구분을 위해 .module .m05  추가함. -->
<!-- single item -->
<section class="module m05 call-to-action with-carousel dot-line">
	<div class="slide">
		<!-- 1. Headline --><h3>What the Experts are Saying</h3>
		<div class="slide-content">
			<div class="image-area">
				<!-- 4. Inset Image --><img data-lazy="/img_sample/M05_01.png" data-src="" alt="Measure First">
			</div>
			<div class="text-area">
				<!-- 2. Body Copy --><p>Follow the tips below to make sure your LG product will fit in the space intended.</p>
			</div>
		</div>
		<div class="cta">
			<!-- 3. CTA -->
			<a href="#" class="btn">Measure First</a>
		</div>
	</div>
</section>
<section class="module m05 call-to-action with-carousel dot-line"><!-- 타이틀이 없는 경우 -->
	<div class="slide">
		<div class="image-area">
			<!-- 4. Inset Image --><img data-lazy="/img_sample/M05_01.png" data-src="" alt="Measure First">
		</div>
		<div class="slide-content">
			<div class="text-area">
				<!-- 2. Body Copy --><p>Follow the tips below to make sure your LG product will fit in the space intended. Follow the tips below to make sure your LG product will fit in the space intended.</p>
			</div>
		</div>
		<div class="cta">
			<!-- 3. CTA -->
			<a href="#">Learn More <i class="icon icon-arrow-link"></i></a>
			<a href="#">Shop OLED TVs <i class="icon icon-arrow-link"></i></a>
		</div>
	</div>
</section>
<!-- multiple item -->
<section class="module m05 call-to-action with-carousel dot-line">
	<div class="slide">
		<!-- 1. Headline --><h3>What the Experts are Saying</h3>
		<div class="slide-content">
			<div class="image-area">
				<!-- 4. Inset Image --><img data-lazy="/img_sample/M05_02.png" data-src="" alt="Measure First">
			</div>
			<div class="text-area">
				<!-- 2. Body Copy --><p>Follow the tips below to make sure your LG product will fit in the space intended.</p>
			</div>
		</div>
		<div class="cta">
			<!-- 3. CTA -->
			<a href="#">Learn More <i class="icon icon-arrow-link"></i></a>
			<a href="#">Shop OLED TVs <i class="icon icon-arrow-link"></i></a>
		</div>
	</div>
	<div class="slide"><!-- 타이틀이 없는 경우 -->
		<div class="image-area">
			<!-- 4. Inset Image --><img data-lazy="/img_sample/M05_01.png" data-src="" alt="Measure First">
		</div>
		<div class="slide-content">
			<div class="text-area">
				<!-- 2. Body Copy --><p>Follow the tips below to make sure your LG product will fit in the space intended. Follow the tips below to make sure your LG product will fit in the space intended.</p>
			</div>
		</div>
		<div class="cta">
			<!-- 3. CTA -->
			<a href="#">Learn More <i class="icon icon-arrow-link"></i></a>
			<a href="#">Shop OLED TVs <i class="icon icon-arrow-link"></i></a>
		</div>
	</div>
	<div class="slide">
		<!-- 1. Headline --><h3>What the Experts are Saying</h3>
		<div class="slide-content">
			<div class="image-area">
				<!-- 4. Inset Image --><img data-lazy="/img_sample/M05_03.png" data-src="" alt="Measure First">
			</div>
			<div class="text-area">
				<!-- 2. Body Copy --><p>Follow the tips below to make sure your LG product will fit in the space intended.</p>
			</div>
		</div>
		<div class="cta">
			<!-- 3. CTA -->
			<a href="#" class="btn">Measure First</a>
		</div>
	</div>
</section>
