<!-- M06 -->
<!--
	Requred Class : .module .m06
	Options : 
	- Light/Dark text : .text-light / .text-dark
	- Large Block on Left/Right : .large-left / .large-right
-->
<section class="module m06 text-light large-right">
	<div class="column module-block large-block">
		<!-- 5. Full Bleed Background -->
		<div class="background-image">
			<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/M06_01.jpg" alt="" />
		</div>
		<div class="text-block vertical-middle">
			<div class="vertical-align-wrap">
				<div class="inner-wrap">
					<!-- 1. Headline --><h3>Lorem ipsum dolor sit amet, consectetuer</h3>
					<!-- 2. Body Copy -->
					<p>
						Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo li
					</p>
					<!-- 3. Inset Image -->
					<div class="inset-image visible-mobile">
						<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/M06_04.png" alt="" />
					</div>
					<!-- 8. CTA (링크가 2개일때) 
					<div class="cta cta-text">
						<a href="#">Learn More <i class="icon icon-arrow-link"></i></a>
						<a href="#">Shop OLED TVs <i class="icon icon-arrow-link"></i></a>
					</div>-->
					<div class="cta cta-button">
						<a href="#" class="btn">Learn More</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="column large-block">
		<div class="module-block">
			<!-- 9. Full Bleed Background -->
			<div class="background-image">
				<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/M06_02.jpg" alt="" />
			</div>
			<div class="text-block vertical-middle">
				<div class="vertical-align-wrap">
					<div class="inner-wrap">
						<!-- 6. Headline --><h3>Lorem ipsum </h3>
						<!-- 7. Body Copy -->
						<p>
							Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo li
						</p>
						<!-- 8. CTA (링크가 2개일때) 
						<div class="cta cta-text">
							<a href="#">Learn More <i class="icon icon-arrow-link"></i></a>
							<a href="#">Shop OLED TVs <i class="icon icon-arrow-link"></i></a>
						</div>-->
						<div class="cta cta-button">
							<a href="#" class="btn">Learn More</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="module-block">
			<!-- 13. Full Bleed Background -->
			<div class="background-image">
				<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/M06_03.jpg" alt="" />
			</div>
			<div class="text-block vertical-middle">
				<div class="vertical-align-wrap">
					<div class="inner-wrap">
						<!-- 10. Headline --><h3>Lorem ipsum dolor sit amet, consectetuer</h3>
						<!-- 11. Body Copy -->
						<p>
							Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo li
						</p>
						<!-- 12. CTA (링크가 1개일때) -->
						<div class="cta cta-button">
							<a href="#" class="btn">Learn More</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>