<!-- M07 -->
<!--
	Requred Class : .module .m07 .feature-explorer-carousel .fe-carousel
-->
<section class="module m07 feature-explorer-carousel fe-carousel" data-slides-to-show="4">
	<!-- 1. Eyebrow --><h3>LG REFRIGERATORS</h3>
	<!-- 2. Headline --><p>Explore By Feature</p>
	<div class="carousel-wrap">
		<div class="contents ex-carousel">		
			<div class="slide item">
				<div class="item-image">
					<!-- 2015-06-12 Pre-Filter 예제 링크 -->
					<a href="http://test.lg.com/filter-redirect.html?redirectUrl=/us/tvs&param=sizeMax%3AFV05000008|FV06942312">
						<!-- 4. Image #1 --><img data-lazy="/img_sample/M07-feature-item-01.jpg" data-src="" alt="" />
						<!-- 3. Label #1 --><span class="item-caption">Door-in-Door<sup>&trade;</sup></span>
					</a>
				</div>
			</div>
			<div class="slide item">
				<div class="item-image">
					<a href="#">
						<!-- 4. Image #1 --><img data-lazy="/img_sample/M07-feature-item-02.jpg" data-src="" alt="" />
						<!-- 3. Label #1 --><span class="item-caption">Ice &amp; Water Dispenser</span>
					</a>
				</div>
			</div>
			<div class="slide item">
				<div class="item-image">
					<a href="#">
						<!-- 4. Image #1 --><img data-lazy="/img_sample/M07-feature-item-01.jpg" data-src="" alt="" />
						<!-- 3. Label #1 --><span class="item-caption">Counter Depth</span>
					</a>
				</div>
				
			</div>
			<div class="slide item">
				<div class="item-image">
					<a href="#">
						<!-- 4. Image #1 --><img data-lazy="/img_sample/M07-feature-item-02.jpg" data-src="" alt="" />
						<!-- 3. Label #1 --><span class="item-caption">SmartThinQ</span>
					</a>
				</div>
			</div>
			<div class="slide item">
				<div class="item-image">
					<a href="#">
						<!-- 4. Image #1 --><img data-lazy="/img_sample/M07-feature-item-01.jpg" data-src="" alt="" />
						<!-- 3. Label #1 --><span class="item-caption">Door-in-Door<sup>&trade;</sup></span>
					</a>
				</div>
			</div>
			<div class="slide item">
				<div class="item-image">
					<a href="#">
						<!-- 4. Image #1 --><img data-lazy="/img_sample/M07-feature-item-02.jpg" data-src="" alt="" />
						<!-- 3. Label #1 --><span class="item-caption">Ice &amp; Water Dispenser</span>
					</a>
				</div>
			</div>
			<div class="slide item">
				<div class="item-image">
					<a href="#">
						<!-- 4. Image #1 --><img data-lazy="/img_sample/M07-feature-item-01.jpg" data-src="" alt="" />
						<!-- 3. Label #1 --><span class="item-caption">Counter Depth</span>
					</a>
				</div>
				
			</div>
			<div class="slide item">
				<div class="item-image">
					<a href="#">
						<!-- 4. Image #1 --><img data-lazy="/img_sample/M07-feature-item-02.jpg" data-src="" alt="" />
						<!-- 3. Label #1 --><span class="item-caption">SmartThinQ</span>
					</a>
				</div>
			</div>
		</div>
	</div>
	<!-- 5. CTA (링크가 1개일때) -->
	<div class="cta">
		<!-- <button class="btn">View All Refrigerators</button> -->
		<a href="#" class="btn">View All Refrigerators</a>
	</div>
	<!-- 5. CTA (링크가 2개일때) 
	<div class="cta more-links">
		<a href="#" class="more-links-btn">View All Refrigerators<i class="icon icon-arrow-link"></i></a>
		<a href="#" class="more-links-btn">View All Refrigerators<i class="icon icon-arrow-link"></i></a>
	</div>
	-->
</section>

