<!-- M08 -->
<!--
	Requred Class : .module .m08 .with-carousel .lists .dot-line
-->
<section class="module m08 with-carousel lists dot-line" data-slides-to-show="4" itemscope itemtype="http://schema.org/SiteNavigationElement"><!-- 2015-08-26 add itemscope, itemtype -->
	<div class="container">
		<div class="title">
			<!-- 1. Headline -->
			<h3>Head line Area</h3>
		</div>
		<div class="carousel light-background">
			<div class="slide">
				<div class="slide-inner">
					<!-- 2015-06-12 a 요소 href에 각각 Pre-Filter 예제 링크 적용됨 -->
					<div class="copy-area">
						<!-- 2. Tile Tile Headline -->
						<p class="name" itemprop="name"><a itemprop="url" href="http://test.lg.com/filter-redirect.html?redirectUrl=/us/tvs&param=FV06942345|FV06942332|sizeMin%3AFV05000005|sizeMax%3AFV05000018">Lorem ipsum dolor sit ame<i class="icon icon-arrow-next"></i></a></p><!-- 2015-08-26 add itemprop : Tile Headline이 있는 경우 -->
						<!-- 4. Tile Image -->
						<p class="image">
							<a class="img-link" href="http://test.lg.com/filter-redirect.html?redirectUrl=/us/tvs&param=FV06942345|FV06942332|sizeMin%3AFV05000005|sizeMax%3AFV05000018">
								<img data-lazy="/img_sample/sample_thumbnail.jpg" src="/lg4-common/img/placeholder.gif" alt="For the ultimate color realism when viewed from any angle" /> 
							</a>
							<!-- 2015-07-28 src="/lg4-common/img/placeholder.gif" 추가 -->
						</p>
						<!-- 2. Tile Body Copy -->
						<p class="desc"><a href="http://test.lg.com/filter-redirect.html?redirectUrl=/us/tvs&param=FV06942345|FV06942332|sizeMin%3AFV05000005|sizeMax%3AFV05000018">For the ultimate color realism when viewed from any angle</a></p>
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Tile Tile Headline -->
						<p class="name" itemprop="name"><a href="#" itemprop="url">Ultra HD 4K TVs <i class="icon icon-arrow-next"></i></a></p>
						<!-- 4. Tile Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/sample_thumbnail.jpg" src="/lg4-common/img/placeholder.gif" alt="Four times the picture quality of Full HD 1080p " />
							</a>
						</p>
						<!-- 2. Tile Body Copy -->
						<p class="desc"><a href="#">Four times the picture quality of Full HD 1080p</a></p>
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Tile Tile Headline -->
						<p class="name" itemprop="name"><a href="#" itemprop="url">LED TVs <i class="icon icon-arrow-next"></i></a></p>
						<!-- 4. Tile Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/sample_thumbnail.jpg" src="/lg4-common/img/placeholder.gif" alt="A full range of sizes at many price points, all THX-certified" />
							</a>
						</p>
						<!-- 2. Tile Body Copy -->
						<p class="desc"><a href="#">A full range of sizes at many price points, all THX-certified</a></p>
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Tile Tile Headline -->
						<p class="name" itemprop="name"><a href="#" itemprop="url">Plasma TVs <i class="icon icon-arrow-next"></i></a></p>
						<!-- 4. Tile Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/sample_thumbnail.jpg" src="/lg4-common/img/placeholder.gif" alt="High screen refresh, you'll never miss a single HD frame" />
							</a>
						</p>
						<!-- 2. Tile Body Copy -->
						<p class="desc"><a href="#">High screen refresh, you'll never miss a single HD frame</a></p>
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Tile Tile Headline -->
						<p class="name" itemprop="name"><a href="#" itemprop="url">Ultra HD 4K TVs <i class="icon icon-arrow-next"></i></a></p>
						<!-- 4. Tile Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/sample_thumbnail.jpg" src="/lg4-common/img/placeholder.gif" alt="49.6” Diagonal 1080p Smart 3D Curved OLED TV" />
							</a>
						</p>
						<!-- 2. Tile Body Copy -->
						<p class="desc"><a href="#">49.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
					</div>
				</div>
			</div>
		</div>
		<!-- 5. CTA -->
		<div class="cta cta-button">
			<a href="#" class="btn">CTA button Area</a>
		</div>
	</div>
</section>
<section class="module m08 with-carousel lists dot-line" data-slides-to-show="4" itemscope itemtype="http://schema.org/SiteNavigationElement">
	<div class="container">
		<div class="carousel light-background">
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Tile Tile Headline -->
						<p class="name" itemprop="name"><a itemprop="url" href="#">Lorem ipsum dolor sit ame<i class="icon icon-arrow-next"></i></a></p>
						<!-- 4. Tile Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/img/category/tvs/sub-category-OLED-tvs.jpg" src="/lg4-common/img/placeholder.gif" alt="For the ultimate color realism when viewed from any angle" /> 
							</a>
						</p>
						<!-- 2. Tile Body Copy -->
						<p class="desc"><a href="#">For the ultimate color realism when viewed from any angle</a></p>
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Tile Tile Headline -->
						<p class="name" itemprop="name"><a itemprop="url" href="#">Ultra HD 4K TVs <i class="icon icon-arrow-next"></i></a></p>
						<!-- 4. Tile Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/img/category/tvs/sub-category-ultra-HD-4K-tvs.jpg" src="/lg4-common/img/placeholder.gif" alt="Four times the picture quality of Full HD 1080p " />
							</a>
						</p>
						<!-- 2. Tile Body Copy -->
						<p class="desc"><a href="#">Four times the picture quality of Full HD 1080p</a></p>
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Tile Tile Headline -->
						<p class="name" itemprop="name"><a itemprop="url" href="#">LED TVs <i class="icon icon-arrow-next"></i></a></p>
						<!-- 4. Tile Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/img/category/tvs/sub-category-LED-tvs.jpg" src="/lg4-common/img/placeholder.gif" alt="A full range of sizes at many price points, all THX-certified" />
							</a>
						</p>
						<!-- 2. Tile Body Copy -->
						<p class="desc"><a href="#">A full range of sizes at many price points, all THX-certified</a></p>
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Tile Tile Headline -->
						<p class="name" itemprop="name"><a itemprop="url" href="#">Plasma TVs <i class="icon icon-arrow-next"></i></a></p>
						<!-- 4. Tile Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/img/category/tvs/sub-category-plasma-tvs.jpg" src="/lg4-common/img/placeholder.gif" alt="High screen refresh, you'll never miss a single HD frame" />
							</a>
						</p>
						<!-- 2. Tile Body Copy -->
						<p class="desc"><a href="#">High screen refresh, you'll never miss a single HD frame</a></p>
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Tile Tile Headline -->
						<p class="name" itemprop="name"><a itemprop="url" href="#">Ultra HD 4K TVs <i class="icon icon-arrow-next"></i></a></p>
						<!-- 4. Tile Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/img/category/tvs/sub-category-ultra-HD-4K-tvs.jpg" src="/lg4-common/img/placeholder.gif" alt="49.6” Diagonal 1080p Smart 3D Curved OLED TV" />
							</a>
						</p>
						<!-- 2. Tile Body Copy -->
						<p class="desc"><a href="#">49.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="module m08 with-carousel shop-lists dot-line" data-slides-to-show="4" itemscope itemtype="http://schema.org/SiteNavigationElement">
	<div class="container">
		<div class="title">
			<!-- 1. Headline -->
			<h3>Shop By Cell Phone Carriers</h3>
		</div>
		<div class="carousel light-background">
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 4. Tile Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/img/category/mobile/shop-by-atat.jpg" src="/lg4-common/img/placeholder.gif" alt="" /> 
							</a>
						</p>
						<!-- 2. Tile Body Copy -->
						<p class="desc" itemprop="name"><a itemprop="url" href="#">AT&amp;T</a></p><!-- 2015-08-26 add itemprop : Tile Headline이 없는 경우 -->
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 4. Tile Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/img/category/mobile/shop-by-sprint.jpg" src="/lg4-common/img/placeholder.gif" alt="" /> 
							</a>
						</p>
						<!-- 2. Tile Body Copy -->
						<p class="desc" itemprop="name"><a itemprop="url" href="#">Sprint</a></p>
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 4. Tile Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/img/category/mobile/shop-by-t-mobile.jpg" src="/lg4-common/img/placeholder.gif" alt="" /> 
							</a>
						</p>
						<!-- 2. Tile Body Copy -->
						<p class="desc" itemprop="name"><a itemprop="url" href="#">T-Mobile</a></p>
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 4. Tile Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/img/category/mobile/shop-by-verizon.jpg" src="/lg4-common/img/placeholder.gif" alt="" /> 
							</a>
						</p>
						<!-- 2. Tile Body Copy -->
						<p class="desc" itemprop="name"><a itemprop="url" href="#">Verizon</a></p>
					</div>
				</div>
			</div>
		</div>
		<!-- 5. CTA -->
		<div class="cta cta-button">
			<a href="#" class="btn">See Additional Carriers</a>
		</div>
	</div>
</section>