<!-- M09 Mobile -->
<!--
	Requred Class : .module .m09 .step-up-chart-m
-->
<!-- 4개 입력시 샘플 -->
<section class="module m09 step-up-chart-m">
	<div class="chart-headline">
		<!-- 1. Headline --><h3>TVS FOR EVERY TASTE</h3>
		<!-- 2. Sub-Headline --><p class="sub-header">Your needs are behind every LG innovation.</p>
	</div>
	<div class="chart-table">
		<table border="0" class="item-list">
			<caption>chart item lists</caption>
			<tbody>
				<tr>
					<td>
						<div class="product-flag basic">
							BASIC
						</div>
						<div class="product-box">
							<a href="#">
								<div class="box-image">
									<div class="wrap">
										<!-- 2015-06-22 lazy load 적용 -->
										<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/chart-1.png" alt="" />
									</div>
								</div>
								<div class="box-info">
									<div class="wrap">
										<!-- 3. Series/Product Name --><!-- <strong>UF9500 </strong> --> 
										<!-- 3.1 Series/Product Description --><span>UF9500 FULL HD SMART TV</span>
									</div>
								</div>
							</a>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div class="product-flag mid">
							MID-RANGE
						</div>
						<div class="product-box">
							<a href="#">
								<div class="box-image">
									<div class="wrap">
										<!-- 2015-06-22 lazy load 적용 -->
										<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/chart-2.png" alt="" />
									</div>
								</div>
								<div class="box-info">
									<div class="wrap">
										<!-- 3. Series/Product Name --><!-- <strong>UF9500 </strong> --> 
										<!-- 3.1 Series/Product Description --><span>UF9500 FULL HD SMART TV</span>
									</div>
								</div>
							</a>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div class="product-flag high">
							HIGH-END
						</div>
						<div class="product-box">
							<a href="#">
								<div class="box-image">
									<div class="wrap">
										<!-- 2015-06-22 lazy load 적용 -->
										<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/chart-3.png" alt="" />
									</div>
								</div>
								<div class="box-info">
									<div class="wrap">
										<!-- 3. Series/Product Name --><!-- <strong>UF9500 </strong> --> 
										<!-- 3.1 Series/Product Description --><span>UF9500 FULL HD SMART TV</span>
									</div>
								</div>
							</a>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div class="product-flag premium">
							PREMIUM
						</div>
						<div class="product-box">
							<a href="#">
								<div class="box-image">
									<div class="wrap">
										<!-- 2015-06-22 lazy load 적용 -->
										<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/chart-4.png" alt="" />
									</div>
								</div>
								<div class="box-info">
									<div class="wrap">
										<!-- 3. Series/Product Name --><!-- <strong>UF9500 </strong> --> 
										<!-- 3.1 Series/Product Description --><span>UF9500 FULL HD SMART TV</span>
									</div>
								</div>
							</a>
						</div>
					</td>
				</tr>
			</tbody>
		</table>

		<div class="hidden-chart-table">
			<!-- 2015-06-18 arrow btn -->
			<div class="toggle-btn-wrap"><button class="chart-toggle"><i class="icon icon-arrow-btn"></i></button></div>
			<div class="chart-scroll-box">
				<div class="chart-box">
					<table border="0" class="chart-section" data-check='0'>
						<caption>product spec lists</caption>
						<thead class="product-caption">
							<tr>
								<!-- 4. Feature --><th scope="col">SIZES (DIAGONAL)</th>
								<!-- 4. Feature --><th scope="col">DISPLAY TYPE</th>
								<!-- 4. Feature --><th scope="col">RESOLUTION</th>
								<!-- 4. Feature --><th scope="col">SMART TV PLATFORM</th>
								<!-- 4. Feature --><th scope="col">BACKLIGHTING</th>
								<!-- 4. Feature --><th scope="col">AUDIO</th>
								<!-- 4. Feature --><th scope="col">MAGIC REMOTE</th>
								<!-- 4. Feature --><th scope="col">REFRESH RATES</th>
								<!-- 4. Feature --><th scope="col">HDMI</th>
								<!-- 4. Feature --><th scope="col">PRODUCT THINNESS</th>
							</tr>	
						</thead>
						<tbody class="product-spec-list">
							<tr>
								<!-- 4.1 Feature Spec --><td>43”, 49”, 55”</td>
								<!-- 4.1 Feature Spec --><td>LED</td>
								<!-- 4.1 Feature Spec --><td>Full HD 1080p</td>
								<!-- 4.1 Feature Spec --><td>WebOS 2.0</td>
								<!-- 4.1 Feature Spec --><td>Ultra HD 4K</td>
								<!-- 4.1 Feature Spec --><td>Virtual Surround Plus</td>
								<!-- 4.1 Feature Spec --><td>&nbsp;</td>
								<!-- 4.1 Feature Spec --><td>120Hz</td>
								<!-- 4.1 Feature Spec --><td>2 (rear)</td>
								<!-- 4.1 Feature Spec --><td>20mm thin</td>
								
							</tr>
							<tr>
								<!-- 4.1 Feature Spec --><td>43”, 49”, 55”</td>
								<!-- 4.1 Feature Spec --><td>LED</td>
								<!-- 4.1 Feature Spec --><td>Full HD 1080p</td>
								<!-- 4.1 Feature Spec --><td>WebOS 2.0</td>
								<!-- 4.1 Feature Spec --><td>Ultra HD 4K</td>
								<!-- 4.1 Feature Spec --><td>Virtual Surround Plus</td>
								<!-- 4.1 Feature Spec --><td>&nbsp;</td>
								<!-- 4.1 Feature Spec --><td>120Hz</td>
								<!-- 4.1 Feature Spec --><td>2 (rear)</td>
								<!-- 4.1 Feature Spec --><td>20mm thin</td>
								
							</tr>
							<tr>
								<!-- 4.1 Feature Spec --><td>43”, 49”, 55”</td>
								<!-- 4.1 Feature Spec --><td>LED</td>
								<!-- 4.1 Feature Spec --><td>Full HD 1080p</td>
								<!-- 4.1 Feature Spec --><td>WebOS 2.0</td>
								<!-- 4.1 Feature Spec --><td>Ultra HD 4K</td>
								<!-- 4.1 Feature Spec --><td>Virtual Surround Plus</td>
								<!-- 4.1 Feature Spec --><td><span class="check-icon"><i class="icon icon-check"></i></span></td>
								<!-- 4.1 Feature Spec --><td>120Hz</td>
								<!-- 4.1 Feature Spec --><td>2 (rear)</td>
								<!-- 4.1 Feature Spec --><td>20mm thin</td>
								
							</tr>
							<tr>
								<!-- 4.1 Feature Spec --><td>Direct Lighting w/Quantum Dots</td>
								<!-- 4.1 Feature Spec --><td>LED</td>
								<!-- 4.1 Feature Spec --><td>Full HD 1080p</td>
								<!-- 4.1 Feature Spec --><td>WebOS 2.0</td>
								<!-- 4.1 Feature Spec --><td>Ultra HD 4K</td>
								<!-- 4.1 Feature Spec --><td>Virtual Surround Plus</td>
								<!-- 4.1 Feature Spec --><td><span class="check-icon"><i class="icon icon-check"></i></span></td>
								<!-- 4.1 Feature Spec --><td>120Hz</td>
								<!-- 4.1 Feature Spec --><td>2 (rear)</td>
								<!-- 4.1 Feature Spec --><td>20mm thin</td>
								
							</tr>
						</tbody>
						
					</table>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- 1개 입력시 샘플 -->
<section class="module m09 step-up-chart-m">
	<div class="chart-headline">
		<!-- 1. Headline --><h3>TVS FOR EVERY TASTE</h3>
		<!-- 2. Sub-Headline --><p class="sub-header">Your needs are behind every LG innovation.</p>
	</div>
	<div class="chart-table">
		<table border="0" class="item-list">
			<caption>chart item lists</caption>
			<tbody>
				<tr>
					<td>
						<div class="product-flag basic">
							BASIC
						</div>
						<div class="product-box">
							<a href="#">
								<div class="box-image">
									<div class="wrap">
										<!-- 2015-06-22 lazy load 적용 -->
										<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/chart-1.png" alt="" />
									</div>
								</div>
								<div class="box-info">
									<div class="wrap">
										<!-- 3. Series/Product Name --><!-- <strong>UF9500 </strong> --> 
										<!-- 3.1 Series/Product Description --><span>UF9500 FULL HD SMART TV</span>
									</div>
								</div>
							</a>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div class="product-flag mid">
							&nbsp;
						</div>
						<div class="product-box">
							<a href="#">
								<div class="box-image">
									<div class="wrap">
										&nbsp;
									</div>
								</div>
								<div class="box-info">
									<div class="wrap">
										&nbsp;
									</div>
								</div>
							</a>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div class="product-flag high">
							&nbsp;
						</div>
						<div class="product-box">
							<a href="#">
								<div class="box-image">
									<div class="wrap">
										&nbsp;
									</div>
								</div>
								<div class="box-info">
									<div class="wrap">
										&nbsp;
									</div>
								</div>
							</a>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div class="product-flag premium">
							&nbsp;
						</div>
						<div class="product-box">
							<a href="#">
								<div class="box-image">
									<div class="wrap">
										&nbsp;
									</div>
								</div>
								<div class="box-info">
									<div class="wrap">
										&nbsp;
									</div>
								</div>
							</a>
						</div>
					</td>
				</tr>
			</tbody>
		</table>

		<div class="hidden-chart-table">
			<!-- 2015-06-18 arrow btn -->
			<div class="toggle-btn-wrap"><button class="chart-toggle"><i class="icon icon-arrow-btn"></i></button></div>
			<div class="chart-scroll-box">
				<div class="chart-box">
					<table border="0" class="chart-section" data-check='0'>
						<caption>product spec lists</caption>
						<thead class="product-caption">
							<tr>
								<!-- 4. Feature --><th scope="col">SIZES (DIAGONAL)</th>
								<!-- 4. Feature --><th scope="col">DISPLAY TYPE</th>
								<!-- 4. Feature --><th scope="col">RESOLUTION</th>
								<!-- 4. Feature --><th scope="col">SMART TV PLATFORM</th>
								<!-- 4. Feature --><th scope="col">BACKLIGHTING</th>
								<!-- 4. Feature --><th scope="col">AUDIO</th>
								<!-- 4. Feature --><th scope="col">MAGIC REMOTE</th>
								<!-- 4. Feature --><th scope="col">REFRESH RATES</th>
								<!-- 4. Feature --><th scope="col">HDMI</th>
								<!-- 4. Feature --><th scope="col">PRODUCT THINNESS</th>
							</tr>	
						</thead>
						<tbody class="product-spec-list">
							<tr>
								<!-- 4.1 Feature Spec --><td>43”, 49”, 55”</td>
								<!-- 4.1 Feature Spec --><td>LED</td>
								<!-- 4.1 Feature Spec --><td>Full HD 1080p</td>
								<!-- 4.1 Feature Spec --><td>WebOS 2.0</td>
								<!-- 4.1 Feature Spec --><td>Ultra HD 4K</td>
								<!-- 4.1 Feature Spec --><td>Virtual Surround Plus</td>
								<!-- 4.1 Feature Spec --><td><span class="check-icon"><i class="icon icon-check"></i></span></td>
								<!-- 4.1 Feature Spec --><td>120Hz</td>
								<!-- 4.1 Feature Spec --><td>2 (rear)</td>
								<!-- 4.1 Feature Spec --><td>20mm thin</td>
								
							</tr>
							<tr>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								
							</tr>
							<tr>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								
							</tr>
							<tr>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								<!-- 4.1 Feature Spec --><td></td>
								
							</tr>
						</tbody>
						
					</table>
				</div>
			</div>
		</div>
	</div>
</section>