<!-- M09 Desktop -->
<!--
	Requred Class : .module .m09 .step-up-chart
-->
<!-- 4개 입력시 샘플 -->
<section class="module m09 step-up-chart">
	<div class="chart-headline">
		<!-- 1. Headline --><h3>TVS FOR EVERY TASTE</h3>
		<!-- 2. Sub-Headline --><p class="sub-header">Your needs are behind every LG innovation.</p>
		<button class="expand-button"><i class="icon icon-tab-plus"></i><span>EXPAND ALL</span></button>
	</div>
	<div class="chart-table">
		
		<table border="0">
			<caption>Use to compare different products or product lines to clearly show them in ascending order from good to best</caption>
			<thead class="step-header">
				<tr>
					<th class="first" scope="col">
						Features
					</th>
					<th scope="col">
						<div class="product-box">
							<div class="product-flag basic">BASIC</div>
							<!-- 2015-06-22 lazy load 적용 -->
							<div class="product-image"><img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/chart-1.png" alt="" /></div>
							<div class="product-name">
								<!-- 3. Series/Product Name -->UF9500 
								<!-- 3.1 Series/Product Description --><span>FULL HD SMART TV</span>
							</div>
						</div>
					</th>
					<th scope="col">
						<div class="product-box">
							<div class="product-flag mid">MID-RANGE</div>
							<!-- 2015-06-22 lazy load 적용 -->
							<div class="product-image"><img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/chart-2.png" alt="" /></div>
							<div class="product-name">
								<!-- 3. Series/Product Name -->UF8500 
								<!-- 3.1 Series/Product Description --><span>3D UHD WITH CINEMA SCREEN</span>
							</div>
						</div>
					</th>
					<th scope="col">
						<div class="product-box">
							<div class="product-flag high">HIGH-END</div>
							<!-- 2015-06-22 lazy load 적용 -->
							<div class="product-image"><img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/chart-3.png" alt="" /></div>
							<div class="product-name">
								<!-- 3. Series/Product Name -->UF9500 
								<!-- 3.1 Series/Product Description --><span>FULL HD SMART TV</span>
							</div>
						</div>
					</th>
					<th scope="col">
						<div class="product-box">
							<div class="product-flag premium">PREMIUM</div>
							<!-- 2015-06-22 lazy load 적용 -->
							<div class="product-image"><img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/chart-4.png" alt="" /></div>
							<div class="product-name">
								<!-- 3. Series/Product Name -->UF9500 
								<!-- 3.1 Series/Product Description --><span>FULL HD SMART TV</span>
							</div>
						</div>
					</th>
				</tr>
			</thead>
			<tbody class="expand-area">
				<tr>
					<!-- 4. Feature --><td class="first">SIZE (DIAGONAL)</td>
					<!-- 4.1 Feature Spec --><td>43”, 49”, 55”</td>
					<!-- 4.1 Feature Spec --><td>55”, 65”</td>
					<!-- 4.1 Feature Spec --><td>43”, 49”, 55”</td>
					<!-- 4.1 Feature Spec --><td>55”, 65”</td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">DISPLAY TYPE</td>
					<!-- 4.1 Feature Spec --><td>LED</td>
					<!-- 4.1 Feature Spec --><td>LED</td>
					<!-- 4.1 Feature Spec --><td>LED</td>
					<!-- 4.1 Feature Spec --><td>LED</td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">RESOLUTION</td>
					<!-- 4.1 Feature Spec --><td>Full HD 1080p</td>
					<!-- 4.1 Feature Spec --><td>Ultra HD 4K</td>
					<!-- 4.1 Feature Spec --><td>Full HD 1080p</td>
					<!-- 4.1 Feature Spec --><td>Ultra HD 4K</td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">SMART TV PLATFORM</td>
					<!-- 4.1 Feature Spec --><td>WebOS 2.0</td>
					<!-- 4.1 Feature Spec --><td>WebOS 2.0</td>
					<!-- 4.1 Feature Spec --><td>WebOS 2.0</td>
					<!-- 4.1 Feature Spec --><td>WebOS 2.0</td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">BACKLIGHTING</td>
					<!-- 4.1 Feature Spec --><td>Edge-Lit LED</td>
					<!-- 4.1 Feature Spec --><td>Direct Lighting w/Quantum Dots</td>
					<!-- 4.1 Feature Spec --><td>Edge-Lit LED</td>
					<!-- 4.1 Feature Spec --><td>Direct Lighting w/Quantum Dots</td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">AUDIO</td>
					<!-- 4.1 Feature Spec --><td>Virtual Surround Plus</td>
					<!-- 4.1 Feature Spec --><td>Enhanced Audio by harman/kardon</td>
					<!-- 4.1 Feature Spec --><td>Virtual Surround Plus</td>
					<!-- 4.1 Feature Spec --><td>Enhanced Audio by harman/kardon</td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">MAGIC REMOTE</td>
					<!-- 4.1 Feature Spec --><td>&nbsp;</td>
					<!-- 4.1 Feature Spec --><td>&nbsp;</td>
					<!-- 4.1 Feature Spec --><td><span class="check-icon"><i class="icon icon-check"></i></span></td>
					<!-- 4.1 Feature Spec --><td><span class="check-icon"><i class="icon icon-check"></i></span></td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">REFRESH RATES</td>
					<!-- 4.1 Feature Spec --><td>120Hz</td>
					<!-- 4.1 Feature Spec --><td>240Hz</td>
					<!-- 4.1 Feature Spec --><td>120Hz</td>
					<!-- 4.1 Feature Spec --><td>240Hz</td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">HDMI</td>
					<!-- 4.1 Feature Spec --><td>2 (rear)</td>
					<!-- 4.1 Feature Spec --><td>4 (rear), 2 (side)</td>
					<!-- 4.1 Feature Spec --><td>2 (rear)</td>
					<!-- 4.1 Feature Spec --><td>4 (rear), 2 (side)</td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">PRODUCT THINNESS</td>
					<!-- 4.1 Feature Spec --><td>20mm thin</td>
					<!-- 4.1 Feature Spec --><td>8.5mm thin</td>
					<!-- 4.1 Feature Spec --><td>20mm thin</td>
					<!-- 4.1 Feature Spec --><td>8.5mm thin</td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first"><span class="empty">buttons</span></td>
					<!-- 4.1 Feature Spec --><td><a href="#" class="btn">View Products</a></td>
					<!-- 4.1 Feature Spec --><td><a href="#" class="btn">View Products</a></td>
					<!-- 4.1 Feature Spec --><td><a href="#" class="btn">View Products</a></td>
					<!-- 4.1 Feature Spec --><td><a href="#" class="btn">View Products</a></td>
				</tr>
			</tbody>
		</table>
	</div>
</section>
<!-- 1개 입력시 샘플 -->
<section class="module m09 step-up-chart">
	<div class="chart-headline">
		<!-- 1. Headline --><h3>TVS FOR EVERY TASTE</h3>
		<!-- 2. Sub-Headline --><p class="sub-header">Your needs are behind every LG innovation.</p>
		<button class="expand-button"><i class="icon icon-tab-plus"></i><span>EXPAND ALL</span></button>
	</div>
	<div class="chart-table">
		
		<table border="0">
			<caption>Use to compare different products or product lines to clearly show them in ascending order from good to best</caption>
			<thead class="step-header">
				<tr>
					<th class="first" scope="col">
						Features
					</th>
					<th scope="col">
						<div class="product-box">
							<div class="product-flag basic">BASIC</div>
							<!-- 2015-06-22 lazy load 적용 -->
							<div class="product-image"><img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/chart-1.png" alt="" /></div>
							<div class="product-name">
								<!-- 3. Series/Product Name -->UF9500 
								<!-- 3.1 Series/Product Description --><span>FULL HD SMART TV</span>
							</div>
						</div>
					</th>
					<th scope="col">
						<div class="product-box">
							<div class="product-flag mid">&nbsp;</div>
							<div class="product-image">&nbsp;</div>
							<div class="product-name">&nbsp;</div>
						</div>
					</th>
					<th scope="col">
						<div class="product-box">
							<div class="product-flag high">&nbsp;</div>
							<div class="product-image">&nbsp;</div>
							<div class="product-name">&nbsp;</div>
						</div>
					</th>
					<th scope="col">
						<div class="product-box">
							<div class="product-flag premium">&nbsp;</div>
							<div class="product-image">&nbsp;</div>
							<div class="product-name">&nbsp;</div>
						</div>
					</th>
				</tr>
			</thead>
			<tbody class="expand-area">
				<tr>
					<!-- 4. Feature --><td class="first">SIZE (DIAGONAL)</td>
					<!-- 4.1 Feature Spec --><td>43”, 49”, 55”</td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">DISPLAY TYPE</td>
					<!-- 4.1 Feature Spec --><td>LED</td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">RESOLUTION</td>
					<!-- 4.1 Feature Spec --><td>Full HD 1080p</td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">SMART TV PLATFORM</td>
					<!-- 4.1 Feature Spec --><td>WebOS 2.0</td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">BACKLIGHTING</td>
					<!-- 4.1 Feature Spec --><td>Edge-Lit LED</td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">AUDIO</td>
					<!-- 4.1 Feature Spec --><td>Virtual Surround Plus</td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">MAGIC REMOTE</td>
					<!-- 4.1 Feature Spec --><td><span class="check-icon"><i class="icon icon-check"></i></span></td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">REFRESH RATES</td>
					<!-- 4.1 Feature Spec --><td>120Hz</td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">HDMI</td>
					<!-- 4.1 Feature Spec --><td>2 (rear)</td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first">PRODUCT THINNESS</td>
					<!-- 4.1 Feature Spec --><td>20mm thin</td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
				</tr>
				<tr>
					<!-- 4. Feature --><td class="first"><span class="empty">buttons</span></td>
					<!-- 4.1 Feature Spec --><td><a href="#" class="btn">View Products</a></td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
					<!-- 4.1 Feature Spec --><td></td>
				</tr>
			</tbody>
		</table>
	</div>
</section>

