<!-- N10 -->
<!--
	Requred Class : .module .m10 .with-carousel .lists .dot-line
-->
<section class="module m10 with-carousel lists dot-line" data-slides-to-show="5">
	<div class="container">
		<div class="carousel light-background">
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Inset Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/img/category/range/sub-category-easyclean.jpg" src="/lg4-common/img/placeholder.gif" alt="EasyClean" /> 
							</a>
						</p>
						<!-- 1. Body Copy -->
						<p class="desc"><a href="#">Wipe Clean with Ease</a></p>
					</div>
				</div>
			</div>
			<!-- 2015-07-30 링크 없을 시 예제 -->
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Inset Image -->
						<p class="image">
							<img data-lazy="/img_sample/img/category/range/sub-category-largecapacity.jpg" src="/lg4-common/img/placeholder.gif" alt="Large Capacity" /> 
						</p>
						<!-- 1. Body Copy -->
						<p class="desc">Cook More Dishes at <br>the Same Time</p>
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Inset Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/img/category/range/sub-category-evenjet.jpg" src="/lg4-common/img/placeholder.gif" alt="EvenJet Convection" /> 
								<!-- 2015-07-28 src="/lg4-common/img/placeholder.gif" 추가 -->
							</a>
						</p>
						<!-- 1. Body Copy -->
						<p class="desc"><a href="#">Faster Preheating and <br>More Precise Cooking</a></p>
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Inset Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/img/category/range/sub-category-btu.jpg" src="/lg4-common/img/placeholder.gif" alt="17,000 BTU" /> 
							</a>
						</p>
						<!-- 1. Body Copy -->
						<p class="desc"><a href="#">Brings Liquids to a <br>Boil Quickly</a></p>
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Inset Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/img/category/range/sub-category-burners.jpg" src="/lg4-common/img/placeholder.gif" alt="5 Burners" /> 
							</a>
						</p>
						<!-- 1. Body Copy -->
						<p class="desc"><a href="#">5 High Performance <br>Sealed Burners</a></p>
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Inset Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/img/category/range/sub-category-easyclean.jpg" src="/lg4-common/img/placeholder.gif" alt="EasyClean" /> 
							</a>
						</p>
						<!-- 1. Body Copy -->
						<p class="desc"><a href="#">Wipe Clean with Ease</a></p>
					</div>
				</div>
			</div>
			<div class="slide">
				<div class="slide-inner">
					<div class="copy-area">
						<!-- 2. Inset Image -->
						<p class="image">
							<a href="#" class="img-link">
								<img data-lazy="/img_sample/img/category/range/sub-category-evenjet.jpg" src="/lg4-common/img/placeholder.gif" alt="EvenJet Convection" /> 
							</a>
						</p>
						<!-- 1. Body Copy -->
						<p class="desc"><a href="#">Faster Preheating and <br>More Precise Cooking</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>