<!-- M12 -->
<!--
	Requred Class : .module .m12
-->
<section class="module m12">
	<div class="container">
		<div class="category-item-wrap">
			<div class="category-item">
				<div class="category-item-img">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/cate_refrig_1.jpg" alt="">
				</div>
				<div class="category-item-text">
					<!-- 2015-06-30 타이틀 a 태그 추가 -->
					<p class="category-item-title"><a href="#">Kitchen <br>Appliances</a></p>
					<ul class="category-item-links">
						<li><a href="#">Refrigerators <i class="icon icon-arrow-next"></i></a></li>
						<li><a href="#">Cooking Appliances <i class="icon icon-arrow-next"></i></a></li>
						<li><a href="#">Dishwashers <i class="icon icon-arrow-next"></i></a></li>
						<li><a href="#">Kitchen Accessories <i class="icon icon-arrow-next"></i></a></li>
					</ul>
				</div>
			</div>
			<div class="category-item">
				<div class="category-item-img">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/cate_refrig_2.jpg" alt="">
				</div>
				<div class="category-item-text">
					<!-- 2015-06-30 타이틀 a 태그 추가 -->
					<p class="category-item-title"><a href="#">Laundry</a></p>
					<ul class="category-item-links">
						<li><a href="#">Washers <i class="icon icon-arrow-next"></i></a></li>
						<li><a href="#">Washer Dryer Combo <i class="icon icon-arrow-next"></i></a></li>
						<li><a href="#">Dryers <i class="icon icon-arrow-next"></i></a></li>
						<li><a href="#">Laundry Accessories <i class="icon icon-arrow-next"></i></a></li>
					</ul>
				</div>
			</div>
			<div class="category-item">
				<div class="category-item-img">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/cate_refrig_3.jpg" alt="">
				</div>
				<div class="category-item-text">
					<!-- 2015-06-30 타이틀 a 태그 추가 -->
					<p class="category-item-title"><a href="#">Rest of Home</a></p>
					<ul class="category-item-links">
						<li><a href="#">Air Conditioners <i class="icon icon-arrow-next"></i></a></li>
						<li><a href="#">Dehumidifiers <i class="icon icon-arrow-next"></i></a></li>
						<li><a href="#">Vacuums <i class="icon icon-arrow-next"></i></a></li>
						<li><a href="#">LED Lights <i class="icon icon-arrow-next"></i></a></li>
						<li><a href="#">Appliances Accessories <i class="icon icon-arrow-next"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>
