<section class="findTheRightFilter">
	<!--  2015-06-12 data-link-json 속성 추가 -->
	<form action="/ajaxData/returnCount.html" method="post" class="filter" data-event="change" data-sc-item="filter-search" data-search-category="/us/refrigerators">
		<!-- 2015-05-22 filterField 클래스 추가 -->
		<div class="my-search-box filterField">
			<div class="my-search">
				<p class="search-title">START MY SEARCH</p>
				<div class="refrigerators-search-area">
					<div class="refrigerators-choice">
						<p class="search-sub-title">What type of refrigerator are you looking for?</p>
						<ul class="refrigerators-list">
							<!-- 2015-05-22 폰트아이콘 적용 -->
							<li>
								<label>
									<!-- 2015-06-12 name, value값 startMysearch.json 으로 추출 -->
									<input type="checkbox" class="chk" name="FT05033894" value="FV11301074" />
									<span class="img"><i class="icon icon-french-door"></i></span>
									<!-- 2015-07-30 BR 추가 -->
									<span class="list-text">French <br>Door</span><!-- 2015-06-09 모바일과 마크업 구조 동기화 -->
								</label>
							</li>
							<li>
								<label>
									<input type="checkbox" class="chk" name="FT05033894" value="FV11301075" />
									<span class="img"><i class="icon icon-side-by-side"></i></span>
									<!-- 2015-06-08 공백추가 -->
									<!-- 2015-07-30 BR 추가 -->
									<span class="list-text">Side-by-<br>
									Side</span><!-- 2015-06-09 모바일과 마크업 구조 동기화 -->
								</label>
							</li>
							<li>
								<label>
									<input type="checkbox" class="chk" name="FT05033894" value="FV11301077" />
									<span class="img"><i class="icon icon-bottom-freezer"></i></span>
									<!-- 2015-07-30 BR 추가 -->
									<span class="list-text">Bottom <br>Freezer</span><!-- 2015-06-09 모바일과 마크업 구조 동기화 -->
								</label>
							</li>
							<li>
								<label>
									<input type="checkbox" class="chk" name="FT05033894" value="FV11301076" />
									<span class="img"><i class="icon icon-top-freezer"></i></span>
									<!-- 2015-07-30 BR 추가 -->
									<span class="list-text">Top <br>Freezer</span><!-- 2015-06-09 모바일과 마크업 구조 동기화 -->
								</label>
							</li>
							<!-- //2015-05-22 폰트아이콘 적용 -->
						</ul>
					</div>
					<div class="viewing">
						<p class="search-sub-title">Size?</p>
						<ul class="check-list refrigerators-check-left">
							<li>
								<label><input type="checkbox" class="chk" name="FT05033687" value="FTV0000188V">Under (19 cu ft)</label>
							</li>
							<li>
								<label><input type="checkbox" class="chk" name="FT05033687" value="FTV0000182V">Large (20-24 cu ft)</label>
							</li>
							<li>
								<label><input type="checkbox" class="chk" name="FT05033687" value="FTV0000183V">Ultra-Large (25-29 cu ft)</label>
							</li>
						</ul>
						<ul class="check-list refrigerators-check-right">
							<li>
								<label><input type="checkbox" class="chk" name="FT05033687" value="FTV0000185V">Super (30-31 cu ft)</label>
							</li>
							<li>
								<label><input type="checkbox" class="chk" name="FT05033687" value="FTV0000203V">Mega (32+ cu ft)</label>
							</li>
						</ul>
					</div>
					<div class="viewing features-want">
						<p class="search-sub-title">Features I want?</p>
						<ul class="check-list">
							<li>
								<!-- 2015-06-08 항목 변경될 부분 확정안됨 -->
								<label><input type="checkbox" class="chk" name="test10" value="value10" />Door-in-Door</label>
							</li>
							<li>
								<label><input type="checkbox" class="chk" name="FT05033699" value="FV11300619V">Counter Depth</label>
							</li>
							<li>
								<label><input type="checkbox" class="chk" name="FT05033700" value="FV11300626V">Ice &amp; Water Dispenser</label>
							</li>
						</ul>
					</div>
					<div class="matching">
						<p class="search-sub-title">Matching Products</p>
						<!-- 2015-06-11 카운트 기본0 see result 버튼 숨김 -->
						<p class="matching-count">0</p>
						<p class="matching-btn"><a href="/category_sub_d.html" class="red-btn hide">See Results</a></p>
					</div>
				</div>
			</div>
		</div>
	</form>
</section>