<section class="notice-board list-d">
<form action="/ajaxData/board/result.html" method="post">
	<input type="hidden" name="page" value="1">
	<input type="hidden" name="pagePosition" value="1">
	<div class="board-header">
		<div class="bg-image"><img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/static/notice-board-image.jpg" itemprop="contentUrl" alt="" /></div>
		<div class="title-block">
			<div class="board-title">
				<!-- 2015-08-25 h1으로 변경 -->
				<h1 class="text-block">Public Notice</h1>
			</div>
		</div>
	</div>
	<div class="board-list">
		<ul>
			<li><a href="#"><span >General</span></a></li>
			<li><a href="#" class="active"><span>Mobile</span></a></li>
			<li><a href="#"><span>TV/Audio/Video</span></a></li>
			<li><a href="#"><span>Appliances</span></a></li>
			<li><a href="#"><span class="last">Computer Products</span></a></li>
		</ul>
	</div>
	<div class="board-wrap">
		<div class="board-title-box super-title">
			<div class="table-box">
				<div class="vertical-box">
					<h2>General Public Notices</h2>
				</div>
				<!-- <div class="vertical-box shop-button">
					<a href="#" class="btn">Shop All Cell Phones</a>
				</div> -->
			</div>
		</div>
		<!-- 2015-08-24 No Result list
		<ul class="board-lists no-result">
			<li>
				<p>There are no public notices</p>
			</li>
		</ul>
		 -->
		<ul class="board-lists">
			<li>
				<div class="text-block">
					<p class="title"><a href="#">Hearing Aid Compatibility</a></p>
					<p class="date">03/07/2014</p>
				</div>
			</li>
			<li>
				<div class="text-block">
					<p class="title"><a href="#">LG Recalls Top-Loading Washing Machines Due to Risk of Injury</a></p>
					<p class="date">03/07/2014</p>
				</div>
			</li>
			<li>
				<div class="text-block">
					<p class="title"><a href="#">Hearing Aid Compatibility</a></p>
					<p class="date">03/07/2014</p>
				</div>
			</li>
			<li>
				<div class="text-block">
					<p class="title"><a href="#">Hearing Aid Compatibility</a></p>
					<p class="date">03/07/2014</p>
				</div>
			</li>
			<li>
				<div class="text-block">
					<p class="title"><a href="#">Hearing Aid Compatibility</a></p>
					<p class="date">03/07/2014</p>
				</div>
			</li>
			<li>
				<div class="text-block">
					<p class="title"><a href="#">Hearing Aid Compatibility</a></p>
					<p class="date">03/07/2014</p>
				</div>
			</li>
			<li>
				<div class="text-block">
					<p class="title"><a href="#">Hearing Aid Compatibility</a></p>
					<p class="date">03/07/2014</p>
				</div>
			</li>
		</ul>
		<div class="board-page">
			<span class="pages">
			<!-- 2015-08-24 페이지 마크업 일부 변경 -->
				<a href="#" data-page="2" data-pageposition="1" class="prev">&lt;</a><!-- prev page (sample) -->
				<a href="#" data-page="1" data-pageposition="1" class="active">1</a> |
				<a href="#" data-page="2" data-pageposition="1">2</a> |
				<a href="#" data-page="3" data-pageposition="1">3</a> |
				<a href="#" data-page="4" data-pageposition="2">4</a> |
				<a href="#" data-page="5" data-pageposition="3">5</a> |
				<a href="#" data-page="6" data-pageposition="4">6</a>
				<a href="#" data-page="4" data-pageposition="2" class="next">&gt;</a><!-- next page  (sample) -->
			</span>
		</div>
	</div>
</form>
</section>