<section class="notice-board list-m">
<form action="/ajaxData/board/result.html" method="post">
	<input type="hidden" name="page" value="1">
	<input type="hidden" name="pagePosition" value="1">
	<div class="board-list">
		<!-- 2015-08-25 h1으로 변경 -->
		<a href="#" class="list-nav"><h1>PUBLIC NOTICE</h1> <i class="icon icon-arrow-next"></i></a>
		<ul>
			<li><a href="#">General</a></li>
			<li><a href="#">Mobile</a></li>
			<li><a href="#">TV/Audio/Video</a></li>
			<li><a href="#">Appliances</a></li>
			<li><a href="#">Computer Products</a></li>
		</ul>
	</div>
	<div class="board-wrap">
		<h2>Mobile Public Notice</h2>
		<!-- 2015-08-24 No Result list
		<ul class="board-lists no-result">
			<li>
				<p>There are no public notices</p>
			</li>
		</ul>
		-->
		<ul class="board-lists">
			<li>
				
				<div class="text-block">
					<p class="title"><a href="#">Hearing Aid Compatibility</a></p>
					<p class="date">03/07/2014</p>
				</div>
				
			</li>
			<li>
				<div class="text-block">
					<p class="title"><a href="#">Hearing Aid Compatibility</a></p>
					<p class="date">03/07/2014</p>
				</div>
			</li>
			<li>
				<div class="text-block">
					<p class="title"><a href="#">Hearing Aid Compatibility</a></p>
					<p class="date">03/07/2014</p>
				</div>
			</li>
			<li>
				<div class="text-block">
					<p class="title"><a href="#">Hearing Aid Compatibility</a></p>
					<p class="date">03/07/2014</p>
				</div>
			</li>
			<li>
				<div class="text-block">
					<p class="title"><a href="#">Hearing Aid Compatibility</a></p>
					<p class="date">03/07/2014</p>
				</div>
			</li>
			<li>
				<div class="text-block">
					<p class="title"><a href="#">Hearing Aid Compatibility</a></p>
					<p class="date">03/07/2014</p>
				</div>
			</li>
			<li>
				<div class="text-block">
					<p class="title"><a href="#">Hearing Aid Compatibility</a></p>
					<p class="date">03/07/2014</p>
				</div>
			</li>
		</ul>
	</div>
	<!-- 2015-08-24 결과 없는 경우 loadmore 삭제 -->
	<div class="list-bottom-button loadmore_btn"><a href="#">Load More</a></div>
	<!-- <div class="go-to-shop">
		<a href="#" class="btn">Shop All Cell Phones</a>
	</div> -->
</form>
</section>