<section class="notice-board read-d">
	<div class="board-header">
		<div class="bg-image"><img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/static/notice-board-image.jpg" itemprop="contentUrl" alt="" /></div>
		<div class="title-block">
			<div class="board-title">
				<!-- 2015-08-25 h1으로 변경 -->
				<h1 class="text-block">Public Notice</h1>
			</div>
		</div>
		
	</div>
	<div class="board-list">
		<ul>
			<li><a href="#" class="active"><span >General</span></a></li>
			<li><a href="#"><span>Mobile</span></a></li>
			<li><a href="#"><span>TV/Audio/Video</span></a></li>
			<li><a href="#"><span>Appliances</span></a></li>
			<li><a href="#"><span class="last">Computer Products</span></a></li>
		</ul>
	</div>
	<div class="board-wrap">
		<div class="board-title-box super-title">
			<div class="table-box">
				<div class="vertical-box">
					<h2>General Public Notices</h2>
				</div>
				<!-- <div class="vertical-box shop-button">
					<a href="#" class="btn">Shop All Cell Phones</a>
				</div> -->
			</div>
		</div>
		<div class="title-box">
			<div class="table-box">
				<div class="vertical-box">
					<p class="title">Privacy Policy - Contest, Sweepstakes, Consumer promotions </p>
					<p class="date">01/01/2010</p>
				</div>
				<div class="vertical-box util">
					<ul>
						<li class="print"><a href="#">Print</a></li><!-- add 2015-08-27 -->
						<!--<li class="last"><a href="#">SHARE <i class="icon icon-share"></i></a></li>-->
					</ul>
				</div>
			</div>
		</div>
		<div class="content-text">
			<p>Hearing Aid Compatibility</p>
			<p>Hearing Aid Compatibility with Mobile Phones <br />When some mobile phones are used near some hearing devices (hearing aids and cochlear implants), users may detect a buzzing, humming, or whining noise. Some hearing devices are more immune than others to this interference noise, and phones also vary in the amount of interference they generate.</p>
			<p>Hearing Aid Compatibility (HAC) Ratings system <br />The wireless telephone industry has developed ratings for some of their mobile phones, to assist hearing device users in finding phones that may be compatible with their hearing devices. Not all phones have been rated. Phones that are rated have the rating stated on the box or will display the following icons:</p>
		</div>

		<div class="back-to-list">
			<a href="#" class="btn gray">Back to list</a>
		</div>

		<div class="other-lists">
			<ul>
				<li><div class="prev list-box">Previous</div><a href="#">LG Mobile Optimus Facebook Posting</a></li>
				<li><div class="next list-box">Next</div><a href="#">Sweeps Rules</a></li>
			</ul>
		</div>
	</div>
</section>