<section class="static-content">
	<div class="row title-wrap">
		<h1 class="title">MyLG “1 Column” Template</h1>
		<p class="date">April 20,2015</p>
	</div>
	<div class="row-group bottom-hr">
		<div class="row type-paragraph">
			<h2 class="title">Redefining the Curve</h2>
			<p>Morbi semper, sapien ac congue posuere, felis nisi cursus risus, ut commodo ante quam et nibh. Fusce diam nisi, aliquam eget ultricies non, suscipit hendrerit augue. Sed hendrerit malesuada nisi, eu rhoncus est porttitor sit amet. Ut non metus sit amet lorem posuere blandit eget eget enim. Sed sit amet risus id eros tincidunt interdum. Curabitur accumsan magna arcu. Sed posuere augue sed porttitor ornare. Nam vehicula orci nisl, a ultricies sapien auctor vitae. In posuere ut ipsum et luctus. Nunc accumsan urna sit amet justo congue ornare. Phasellus non sollicitudin justo. Vestibulum aliquam sagittis elit lobortis varius. Donec purus diam.</p>
		</div>
		<div class="row type-paragraph">
			<h2 class="title">Lorem ipsum dolor sit amet, consectetuer</h2>
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.</p>
			<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa</p>
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.</p>
		</div>
		<div class="row type-product product-area">
			<div class="product-image">
				<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/open_template_2c.jpg" alt="" />
			</div>
			<div class="copy-area">
				<p class="model-name"><a href="#">LG G Flex2 AT&amp;T (Platinum Silver)</a></p>
				<p class="model-num"><a href="#">LG H950</a></p>
				<div class="details">
					<div class="feature-box colors">
						<p class="title">AVAILABLE COLORS:</p>
						<ul class="list_colors">
							<li itemprop="color" class="active"><a href="#"><span class="color_chip_cover"></span><span class="swatch large stainless-steel"></span>Real Stainless Steel</a></li>
							<li itemprop="color" ><a href="#"><span class="swatch large smooth-black"></span>Smooth Black</a></li>
							<li itemprop="color" ><a href="#"><span class="swatch large smooth-white"></span>Smooth White</a></li>
						</ul>
					</div>
					<div class="rating">
						<div class="points_wrap">
							<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
						</div>
						<span><a href="#">(19 Reviews)</a></span>
					</div>
					<!--
					<div class="product-purchase">
						<div class="cta cta-button">
							<a href="#" class="btn">Where to Buy</a>
						</div>
					</div>
					-->

					<div class="product-price">
						<!-- 
						<div class="suggested-price">
							<p class="price">$3499.<span>99</span></p>
							<p class="legal">Suggested Price</p>
						</div>
						<div class="purchase-price">
							<p class="price">$1499.<span>99</span></p>
							<p class="legal">Promotional Price</p>
						</div>
						-->
						<div class="purchase-price">
							<p class="price">$1499.<span>99</span></p>
							<p class="legal">Suggested Price</p>
						</div>
					</div>
					<!-- 2015-05-21 Ecorebates 
				
						data-modelId : 제품 ID
						class : ecorebates-div 필수
					-->
					<div class="ecorebates-div" data-modelId="WM3170CW"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="row-group bottom-hr">
		<div class="row type-product product-area">
			<div class="product-image">
				<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/open_template_2c.jpg" alt="" />
			</div>
			<div class="copy-area">
				<p class="model-name"><a href="#">Large Capacity Counter-Depth 22 cu.ft. Side-by-Side Refrigerator with Door-in-Door®</a></p>
				<p class="model-num"><a href="#">LFXS32766S</a></p>
				<div class="details">
					<div class="feature-box colors">
						<p class="title">AVAILABLE COLORS:</p>
						<ul class="list_colors">
							<li itemprop="color" class="active"><a href="#"><span class="color_chip_cover"></span><span class="swatch large stainless-steel"></span>Real Stainless Steel</a></li>
								<li itemprop="color" ><a href="#"><span class="swatch large smooth-black"></span>Smooth Black</a></li>
								<li itemprop="color" ><a href="#"><span class="swatch large smooth-white"></span>Smooth White</a></li>
						</ul>
					</div>
					<div class="rating">
						<div class="points_wrap">
							<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
						</div>
						<span><a href="#">(9 Reviews)</a></span>
					</div>
					<!--
					<div class="product-purchase">
						<div class="cta cta-button">
							<a href="#" class="btn">Where to Buy</a>
						</div>
					</div>
					-->
					<div class="product-price">
						<!-- 
						<div class="suggested-price">
							<p class="price">$3499.<span>99</span></p>
							<p class="legal">Suggested Price</p>
						</div>
						<div class="purchase-price">
							<p class="price">$1499.<span>99</span></p>
							<p class="legal">Promotional Price</p>
						</div>
						-->
						<div class="purchase-price">
							<p class="price">$1499.<span>99</span></p>
							<p class="legal">Suggested Price</p>
						</div>
					</div>
					<!-- 2015-05-21 Ecorebates 
				
						data-modelId : 제품 ID
						class : ecorebates-div 필수
					-->
					<div class="ecorebates-div" data-modelId="WM3170CW"></div>
				</div>
			</div>
		</div>
		<div class="row type-paragraph">
			<h2 class="title">Redefining the Curve</h2>
			<p>Morbi semper, sapien ac congue posuere, felis nisi cursus risus, ut commodo ante quam et nibh. Fusce diam nisi, aliquam eget ultricies non, suscipit hendrerit augue. Sed hendrerit malesuada nisi, eu rhoncus est porttitor sit amet. Ut non metus sit amet lorem posuere blandit eget eget enim. Sed sit amet risus id eros tincidunt interdum. Curabitur accumsan magna arcu. Sed posuere augue sed porttitor ornare. Nam vehicula orci nisl, a ultricies sapien auctor vitae. In posuere ut ipsum et luctus. Nunc accumsan urna sit amet justo congue ornare. Phasellus non sollicitudin justo. Vestibulum aliquam sagittis elit lobortis varius. Donec purus diam.</p>
		</div>
	</div>
	<div class="row-group bottom-hr">
		<div class="row type-paragraph">
			<h2 class="title">Redefining the Curve</h2>
			<p>Morbi semper, sapien ac congue posuere, felis nisi cursus risus, ut commodo ante quam et nibh. Fusce diam nisi, aliquam eget ultricies non, suscipit hendrerit augue. Sed hendrerit malesuada nisi, eu rhoncus est porttitor sit amet. Ut non metus sit amet lorem posuere blandit eget eget enim. Sed sit amet risus id eros tincidunt interdum. Curabitur accumsan magna arcu. Sed posuere augue sed porttitor ornare. Nam vehicula orci nisl, a ultricies sapien auctor vitae. In posuere ut ipsum et luctus. Nunc accumsan urna sit amet justo congue ornare. Phasellus non sollicitudin justo. Vestibulum aliquam sagittis elit lobortis varius. Donec purus diam.</p>
		</div>
		<div class="row type-paragraph">
			<h2 class="title">Redefining the Curve Redefining the Curve</h2>
			<p>Morbi semper, sapien ac congue posuere, felis nisi cursus risus, ut commodo ante quam et nibh. Fusce diam nisi, aliquam eget ultricies non, suscipit hendrerit augue. Sed hendrerit malesuada nisi, eu rhoncus est porttitor sit amet. Ut non metus sit amet lorem posuere blandit eget eget enim. Sed sit amet risus id eros tincidunt interdum. Curabitur accumsan magna arcu. Sed posuere augue sed porttitor ornare. Nam vehicula orci nisl, a ultricies sapien auctor vitae. In posuere ut ipsum et luctus. Nunc accumsan urna sit amet justo congue ornare. Phasellus non sollicitudin justo. Vestibulum aliquam sagittis elit lobortis varius. Donec purus diam.</p>
			<p>Morbi semper, sapien ac congue posuere, felis nisi cursus risus, ut commodo ante quam et nibh. Fusce diam nisi, aliquam eget ultricies non, suscipit hendrerit augue. Sed hendrerit malesuada nisi, eu rhoncus est porttitor sit amet. Ut non metus sit amet lorem posuere blandit eget eget enim. Sed sit amet risus id eros tincidunt interdum. Curabitur accumsan magna arcu.</p>
		</div>
	</div>
	<div class="row-group bottom-hr">
		<div class="row type-paragraph">
			<h2 class="title">Redefining the Curve</h2>
			<p>Morbi semper, sapien ac congue posuere, felis nisi cursus risus, ut commodo ante quam et nibh. Fusce diam nisi, aliquam eget ultricies non, suscipit hendrerit augue. Sed hendrerit malesuada nisi, eu rhoncus est porttitor sit amet. Ut non metus sit amet lorem posuere blandit eget eget enim. Sed sit amet risus id eros tincidunt interdum. Curabitur accumsan magna arcu. Sed posuere augue sed porttitor ornare. Nam vehicula orci nisl, a ultricies sapien auctor vitae. In posuere ut ipsum et luctus. Nunc accumsan urna sit amet justo congue ornare. Phasellus non sollicitudin justo. Vestibulum aliquam sagittis elit lobortis varius. Donec purus diam.</p>
		</div>
	</div>
	
</section>