<section class="static-content column-2">
	<div class="left-section">
		<div class="row title-wrap">
			<div class="title">Consectetuer Sapien</div>
			<p>Morbi Mattis Odio</p>
		</div>
		<div class="row check-option-wrap top-hr">
			<div class="subtitle">Lorem Ipsum:</div>
			<div class="option-box"><label for="option-1"><input type="checkbox" id="option-1" name="option-1" value="option-1" /><span>Dolor Sit Amet</span></label></div>
			<div class="option-box"><label for="option-2"><input type="checkbox" id="option-2" name="option-2" value="option-2" /><span>Consecteuter Adipiscing</span></label></div>
			<div class="option-box"><label for="option-3"><input type="checkbox" id="option-3" name="option-3" value="option-3" /><span>Vitae Vivamsu Torto</span></label></div>
		</div>
		<div class="row text-wrap top-hr">
			<div class="subtitle">Felis Edio Etaim:</div>
			<p>
				Vivamus ultricies, tortor non congue pharetra, massa leo hendrerit orci, sed viverra libero ipsum et diam. Nullam non dui leo. Ut interdum, magna ac tempor posuere, purus lacus posuere ligula, tincidunt vulputate metus eros id ligula sed convallis nunc.
			</p>
		</div>
		<div class="row list-wrap top-hr">
			<div class="subtitle">Felis Edio Etaim:</div>
			<ul>
				<li>
					<a href="#">Morbi Semper Sapien</a>
				</li>
				<li>
					<a href="#">Accongue Posuere Felisnisi </a>
				</li>
				<li>
					<a href="#">Cursus Risusut </a>
				</li>
				<li>
					<a href="#">Commodo Antequtuem</a>
				</li>
				<li>
					<a href="#">Suspendisse Luctus Ante </a>
				</li>
				<li>
					<a href="#">Velmauris Blandit Vitae </a>
				</li>
				<li>
					<a href="#">Maximus Purus Elementum</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="content-section">
		<div class="row title-wrap">
			<h1 class="title">MyLG “2 Column” Template</h1>
			<p class="date">April 20,2015</p>
		</div>
		<div class="row-group bottom-hr">
			<div class="row type-paragraph">
				<h2 class="title">Lorem ipsum dolor sit amet, consectetuer</h2>
				<p>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ipsum ipsum, maximus in ultricies id, dictum at velit. Vestibulum mi urna, euismod eu ligula sit amet, rhoncus sagittis quam. Nullam at massa et purus efficitur viverra nec convallis lectus. Integer scelerisque orci sed aliquam porta. Morbi pretium ex nec orci euismod, eget congue velit vestibulum. Donec vitae molestie nibh, sed mattis augue. Suspendisse commodo hendrerit est. In quis mi enim. Donec quis nisl in felis viverra suscipit. Vivamus ultricies, tortor non congue pharetra, massa leo hendrerit orci, sed viverra libero ipsum et diam. Nullam non dui leo.
				</p>
			</div>
			<div class="row type-product product-area">
				<div class="product-image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/open_template_2c.jpg" alt="" />
				</div>
				<div class="copy-area">
					<p class="model-name"><a href="#">LG G Flex2 AT&amp;T (Platinum Silver)</a></p>
					<p class="model-num"><a href="#">LG H950</a></p>
					<div class="details">
						<div class="feature-box colors">
							<p class="title">AVAILABLE COLORS:</p>
							<ul class="list_colors">
								<li itemprop="color" class="active"><a href="#"><span class="color_chip_cover"></span><span class="swatch large stainless-steel"></span>Real Stainless Steel</a></li>
								<li itemprop="color" ><a href="#"><span class="swatch large smooth-black"></span>Smooth Black</a></li>
								<li itemprop="color" ><a href="#"><span class="swatch large smooth-white"></span>Smooth White</a></li>
							</ul>
						</div>
						
						<div class="rating">
							<div class="points_wrap">
								<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
							</div>
							<span><a href="#">(19 Reviews)</a></span>
						</div>
						<!--
						<div class="product-purchase">
							<div class="cta cta-button">
								<a href="#" class="btn">Where to Buy</a>
							</div>
						</div>
						-->

						<div class="product-price">
							<!-- 
							<div class="suggested-price">
								<p class="price">$3499.<span>99</span></p>
								<p class="legal">Suggested Price</p>
							</div>
							<div class="purchase-price">
								<p class="price">$1499.<span>99</span></p>
								<p class="legal">Promotional Price</p>
							</div>
							-->
							<div class="purchase-price">
								<p class="price">$1499.<span>99</span></p>
								<p class="legal">Suggested Price</p>
							</div>
						</div>
						<!-- 2015-05-21 Ecorebates 
				
							data-modelId : 제품 ID
							class : ecorebates-div 필수
						-->
						<div class="ecorebates-div" data-modelId="WM3170CW"></div>
					</div>
				</div>
			</div>
		</div>
		<div class="row-group">
			<div class="row type-paragraph">
				<h2 class="title">Lorem ipsum dolor sit amet, consectetuer</h2>
				<p>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ipsum ipsum, maximus in ultricies id, dictum at velit. Vestibulum mi urna, euismod eu ligula sit amet, rhoncus sagittis quam. Nullam at massa et purus efficitur viverra nec convallis lectus. Integer scelerisque orci sed aliquam porta. Morbi pretium ex nec orci euismod, eget congue velit vestibulum. Donec vitae molestie nibh, sed mattis augue. Suspendisse commodo hendrerit est. In quis mi enim. Donec quis nisl in felis viverra suscipit. Vivamus ultricies, tortor non congue pharetra, massa leo hendrerit orci, sed viverra libero ipsum et diam. Nullam non dui leo.
				</p>
			</div>
			<div class="row type-product product-area">
				<div class="product-image">
					<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/open_template_2c.jpg" alt="" />
				</div>
				<div class="copy-area">
					<p class="model-name"><a href="#">LG G Flex2 AT&amp;T (Platinum Silver)</a></p>
					<p class="model-num"><a href="#">LG H950</a></p>
					<div class="details">
						<div class="feature-box colors">
							<p class="title">AVAILABLE COLORS:</p>
							<ul class="list_colors">
								<li itemprop="color" class="active"><a href="#"><span class="color_chip_cover"></span><span class="swatch large stainless-steel"></span>Real Stainless Steel</a></li>
								<li itemprop="color" ><a href="#"><span class="swatch large smooth-black"></span>Smooth Black</a></li>
								<li itemprop="color" ><a href="#"><span class="swatch large smooth-white"></span>Smooth White</a></li>
							</ul>
						</div>
						<div class="rating">
							<div class="points_wrap">
								<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
							</div>
							<span><a href="#">(19 Reviews)</a></span>
						</div>
						<!--
						<div class="product-purchase">
							<div class="cta cta-button">
								<a href="#" class="btn">Where to Buy</a>
							</div>
						</div>
						-->

						<div class="product-price">
							<!-- 
							<div class="suggested-price">
								<p class="price">$3499.<span>99</span></p>
								<p class="legal">Suggested Price</p>
							</div>
							<div class="purchase-price">
								<p class="price">$1499.<span>99</span></p>
								<p class="legal">Promotional Price</p>
							</div>
							-->
							<div class="purchase-price">
								<p class="price">$1499.<span>99</span></p>
								<p class="legal">Suggested Price</p>
							</div>
						</div>
						<!-- 2015-05-21 Ecorebates 
				
							data-modelId : 제품 ID
							class : ecorebates-div 필수
						-->
						<div class="ecorebates-div" data-modelId="WM3170CW"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

