<section class="hero text-top text-dark dot-line has-award product-page ProductHero" id="ProductHero">
	<div class="top-module-wrap">
		<div class="text-block">
			<!-- 2015-08-11 H1/H2 -->
			<h2 itemprop="name">55&rdquo; Class (54.6&rdquo; Diagonal) 1080P Smart 3D Curved OLED TV</h2>
			<ul class="specs">
				<li><h1 itemprop="sku">55EA9800p</h1></li>
				<li>Discountinued Product</li>
			</ul>
			<!-- 
			Can use ul or p
			<p>
				Paragraph Text
			</p> -->
			<div class="tools_wrap"><!-- .tools_wrap - no delete -->
				<ul class="tools">
					<!-- 2015-07-31 title, data-closetitle Attribute 추가됨 -->
					<li><a class="product-zoom" href="#" title="Open the zoom layer popup" data-closetitle="Close the zoom layer popup"><i class="icon icon-search"></i> zoom</a></li>
					<li><a class="product-360-view" href="#none" data-href="http://lgad.thorn.net/01/HE/360/2014/47LB6300/47LB6300.html" data-iframe-title="TAKE US FOR A SPIN"><i class="icon icon-360"></i> 360 view</a></li><!-- 2015-06-11 delete itemprop -->
					<!--
						3.0 sample : http://www.lg.com/us/tvs/lg-55LB6300-led-tv
					-->
				</ul>
			</div>
		</div>
	</div>
	<div class="bottom-module-wrap">
		<div class="hero-carousel-arrow">
			<!-- 확대 이미지가 들어가는 경우 img 요소에 data-largeImg 속성을 추가하여 이미지 경로 입력 (없는 경우 속성 삭제) -->
			<div class="slide">
				<div class="visuals" itemprop="image" itemscope itemtype="http://schema.org/ImageObject"><!-- 2015-08-21 add itemprop="image" -->
					<img itemprop="contentUrl" src="/img_sample/img/hero/tvs/d-hero-55EA9800p.jpg" data-largeImg="/img_sample/EG9600-750x480.jpg" alt="55EA9800p 55&rdquo; Class Smart 3d Curved OLED TV" />
					<!-- 첫번째 hero 이미지는 lazy 적용 하지 말아 주세요. data-lazy 대신 src 사용. -->
				</div>
			</div>
			<div class="slide">
				<div class="visuals" itemprop="image" itemscope itemtype="http://schema.org/ImageObject">
					<!-- 2015-06-11 data-largeImg 추가 -->
					<img itemprop="contentUrl" src="/lg4-common/img/placeholder.gif" data-lazy="/img_sample/img/hero/tvs/d-hero-55EA9800p.jpg" data-largeImg="/img_sample/EG9600-750x480.jpg" alt="55EA9800p 55&rdquo; Class Smart 3d Curved OLED TV" />
				</div>
			</div>
			<div class="slide">
				<div class="visuals" itemprop="image" itemscope itemtype="http://schema.org/ImageObject">
					<img itemprop="contentUrl" src="/lg4-common/img/placeholder.gif" data-lazy="/img_sample/img/hero/tvs/d-hero-55EA9800p.jpg" alt="55EA9800p 55&rdquo; Class Smart 3d Curved OLED TV" />
				</div>
			</div>
			<div class="slide">
				<div class="visuals" data-video-type="bc" data-video-id="1774058731001" data-account="1665893145001" data-player="default" data-iframe-title="video description (Accessibility)">
					&nbsp;
				</div>
				<!--
					브라이트코브의 경우
					data-video-type : bg
					data-account : account 값
					data-video-id : 동영상 id
					data-player : account에서 생성한 플레이어 값
					data-iframe-title : 동영상에 대한 대체 텍스트
				-->
			</div>
			<div class="slide">
				<div class="visuals" data-video-type="youtube" data-embed-code="yZdWPqpVbEk" data-iframe-title="video description (Accessibility)">
					&nbsp;
				</div>
				<!--
					유투브의 경우
					data-video-type : youtube
					data-embed-code : 유투브 동영상 구분자
					data-iframe-title : 동영상에 대한 대체 텍스트
				-->
			</div>
		</div>
		<div class="hero-gutter-wrap" itemprop="image" itemscope itemtype="http://schema.org/ImageObject">
			<!-- Begin Optional Gutter -->
			<div class="gutter-right">
				<a href="#" class="award-wrap product-hero-layer-trigger" itemprop="url">
					<div class="award logo fade-show-award">
						<div>
							<img itemprop="thumbnailUrl" src="/img_sample/img/awards/award_100-_01.jpg" class="show" alt="" />
							<img itemprop="thumbnailUrl" src="/img_sample/img/awards/award_100-_02.png" alt="" />
							<img itemprop="thumbnailUrl" src="/img_sample/img/awards/award_100-_03.png" alt="" />
						</div>
					</div>
					<div class="award view-all">
						<div>
							<i class="icon icon-award"></i><br>
							<span class="arrow">View All Awards <i class="icon icon-arrow-next"></i></span>
						</div>
					</div>
				</a>
			</div>
			<!-- End Optional Gutter -->
		</div>
		<!-- 2015-06-11 zoom popup과 구분하기 위환 class awards 추가 -->
		<div class="product-hero-layer awards" itemprop="image" itemscope itemtype="http://schema.org/ImageObject">
			<div class="product-hero-layer-inner">
				<div class="inner-wrap">
					<div class="award-list">
						<div class="award-list with-carousel">
							<!-- 2015-06-22 lazy load 적용 -->
							<div class="item"><div><div class="vertical-align-wrap"><div class="inner-wrap"><img itemprop="thumbnailUrl" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/awards/award_100-_01.jpg" class="lazy show" alt="" /></div></div><span itemprop="award" class="only-mobile">Most Innovative Device Manufacturer of the Year</span><!-- 2015-05-15 only-mobile class 추가 / vertical-align-wrap, inner-wrap div 추가 --></div></div>
							<div class="item"><div><div class="vertical-align-wrap"><div class="inner-wrap"><img itemprop="thumbnailUrl" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/awards/award_100-_02.jpg" class="lazy show" alt="" /></div></div><span itemprop="award" class="only-mobile">Phone Arena Awards 2013: Best Smartphones. "...if you want a smartphone that  has it all, then the LG G2 would  be a worthy pick."</span><!-- 2015-05-15 only-mobile class 추가 / vertical-align-wrap, inner-wrap div 추가 --></div></div>
							<div class="item"><div><div class="vertical-align-wrap"><div class="inner-wrap"><img itemprop="thumbnailUrl" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/awards/award_100-_03.jpg" class="lazy show" alt="" /></div></div><span itemprop="award" class="only-mobile">Stuff Gadget Awards 2013: The LG G2 is our Gadget of the Year. "The competition was stiff, but LG's mobile renaissance is Stuff's highlight of 2013."</span><!-- 2015-05-15 only-mobile class 추가 / vertical-align-wrap, inner-wrap div 추가 --></div></div>
							<div class="item"><div><div class="vertical-align-wrap"><div class="inner-wrap"><img itemprop="thumbnailUrl" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/awards/award_100-_04.jpg" class="lazy show" alt="" /></div></div><span itemprop="award" class="only-mobile">Stuff Gadget Awards 2013: The LG G2 is our Gadget of the Year. "The competition was stiff, but LG's mobile renaissance is Stuff's highlight of 2013."</span><!-- 2015-05-15 only-mobile class 추가 / vertical-align-wrap, inner-wrap div 추가 --></div></div>
							<div class="item"><div><div class="vertical-align-wrap"><div class="inner-wrap"><img itemprop="thumbnailUrl" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/awards/award_100-_05.jpg" class="lazy show" alt="" /></div></div><span itemprop="award" class="only-mobile">Most Innovative Device Manufacturer of the Year</span><!-- 2015-05-15 only-mobile class 추가 / vertical-align-wrap, inner-wrap div 추가 --></div></div>
						</div>
					</div>
				</div>
				<a href="#" class="close"><i class="icon icon-close"></i></a>
			</div>
		</div>
	</div>
</section>