<section class="product-lists product-three with-carousel dot-line" data-slides-to-show="3">
	<h3>RECOMMENDED PRODUCTS</h3>
	<div class="container">
		<div class="carousel light-background">
			<div class="product slide">
				<div class="slide-inner">
					<a href="#" class="img-link">
						<img itemprop="contentUrl" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/65-curved-oled-tv.jpg" data-src="" alt="64.5” Diagonal UHD 4K Smart 3D Curved OLED TV" />
					</a>
					<div class="copy-area">
						<p class="model"><a href="#">65” Class</a></p>
						<p class="model-name"><a href="#">64.5” Diagonal UHD 4K Smart 3D Curved OLED TV</a></p>
						<p class="model-num"><a href="#">65EC9700</a></p>
						<div class="details">
							<p class="compare-check">
								<label>
									<input type="checkbox" class="compare" data-product-id="65EC9700" name="compare"><span>Add to Compare</span>
								</label>
								<span class="compare_y hide"><a href="#">COMPARE (<em>1</em>)</a></span>
							</p>
							<div class="product-price">
								<!-- 2015-05-07 promotional price 가 있는 경우 -->
								<div class="suggested-price">
									<p class="price">$3499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Promotional Price</p>
								</div>
								<div class="product-rebate">
									<!-- 2015-05-27 Ecorebates 
										data-modelId : 제품 ID
										class : ecorebates-div 필수
									-->
									<div class="ecorebates-div" data-modelId="WM3170CW"></div>
								</div>
							</div>
							<p class="get-details"><a href="#" class="get-details">Get Details <i class="icon icon-arrow-next"></i></a></p>
						</div>
					</div>
				</div>
			</div>
			<div class="product slide">
				<div class="slide-inner">
					<a href="#" class="img-link">
						<img itemprop="contentUrl" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/65-curved-oled-tv.jpg" data-src="" alt="64.5” Diagonal UHD 4K Smart 3D Curved OLED TV" />
					</a>
					<div class="copy-area">
						<p class="model"><a href="#">65” Class</a></p>
						<p class="model-name"><a href="#">64.5” Diagonal UHD 4K Smart 3D Curved OLED TV</a></p>
						<p class="model-num"><a href="#">65EC9700</a></p>
						<div class="details">
							<p class="compare-check">
								<label>
									<input type="checkbox" class="compare" data-product-id="65EC9700" name="compare"><span>Add to Compare</span>
								</label>
								<span class="compare_y hide"><a href="#">COMPARE (<em>1</em>)</a></span>
							</p>
							<div class="product-price">
								<!-- 2015-05-07 promotional price 가 없는 경우 -->
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="product-rebate">
									<!-- 2015-05-27 Ecorebates 
										data-modelId : 제품 ID
										class : ecorebates-div 필수
									-->
									<div class="ecorebates-div" data-modelId="WM3170CW"></div>
								</div>
							</div>
							<p class="get-details"><a href="#" class="get-details">Get Details <i class="icon icon-arrow-next"></i></a></p>
						</div>
					</div>
				</div>
			</div>
			<div class="product slide">
				<div class="slide-inner">
					<a href="#" class="img-link">
						<img itemprop="contentUrl" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/magic-remote.jpg" data-src="" alt="Magic Remote Control with Voice Mate™ for Select 2013 TVs" />
					</a>
					<div class="copy-area">
						<p class="model"><a href="#">Magic Remote</a></p>
						<p class="model-name"><a href="#">Magic Remote Control with Voice Mate&trade; for Select 2013 TVs </a></p>
						<p class="model-num"><a href="#">AN-MR400</a></p>
						<div class="details">
							<p class="compare-check">
								<label>
									<input type="checkbox" class="compare" data-product-id="AN-MR400" name="compare"><span>Add to Compare</span>
								</label>
								<span class="compare_y hide"><a href="#">COMPARE (<em>1</em>)</a></span>
							</p>
							<div class="product-price">
								<div class="suggested-price">
									<p class="price">$3499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Promotional Price</p>
								</div>
								<div class="product-rebate">
									<!-- 2015-05-27 Ecorebates 
										data-modelId : 제품 ID
										class : ecorebates-div 필수
									-->
									<div class="ecorebates-div" data-modelId="WM3170CW"></div>
								</div>
							</div>
							<p class="get-details"><a href="#" class="get-details">Get Details <i class="icon icon-arrow-next"></i></a></p>
						</div>
					</div>
				</div>
			</div>
			<div class="product slide">
				<div class="slide-inner">
					<a href="#" class="img-link">
						<img itemprop="contentUrl" class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/product/tvs/3d-glasses.jpg" data-src="" alt="3D Shutter Glasses Lightweight, For LG Plasma 3D Ready TVs" />
					</a>
					<div class="copy-area">
						<p class="model"><a href="#">3D Shutter Glasses </a></p>
						<p class="model-name"><a href="#">Lightweight, For LG Plasma 3D Ready TVs</a></p>
						<p class="model-num"><a href="#">AG-S350</a></p>
						<div class="details">
							<p class="compare-check">
								<label>
									<input type="checkbox" class="compare" data-product-id="AG-S350" name="compare"><span>Add to Compare</span>
								</label>
								<span class="compare_y hide"><a href="#">COMPARE (<em>1</em>)</a></span>
							</p>
							<div class="product-price">
								<div class="suggested-price">
									<p class="price">$3499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Promotional Price</p>
								</div>
								<div class="product-rebate">
									<!-- 2015-05-27 Ecorebates 
										data-modelId : 제품 ID
										class : ecorebates-div 필수
									-->
									<div class="ecorebates-div" data-modelId="WM3170CW"></div>
								</div>
							</div>
							<p class="get-details"><a href="#" class="get-details">Get Details <i class="icon icon-arrow-next"></i></a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>