<section class="product-lists product-three with-carousel dot-line" data-slides-to-show="3">
	<h3>YOU MAY ALSO CONSIDER</h3>
	<div class="container">
		<div class="carousel light-background">
			<div class="product slide">
				<div class="slide-inner">
					<a href="#" class="img-link">
						<img class="lazy" src="/lg4-common/img/placeholder.gif" data-lazy="/img_sample/sample_thumbnail.jpg" alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" />
					</a>
					<div class="copy-area">
						<!-- <p class="model"><a href="#">55” Class</a></p> -->
						<p class="model-name"><a href="#">54.6” Diagonal 1080p Smart 3D Curved OLED TV</a></p>
						<p class="model-num"><a href="#">55EA9800</a></p>
						<div class="details">
							<div class="rating" data-modelid="MD00001294"><!-- 2015-08-11 add data-modelid -->
								<!--
									<div class="points_wrap">
										
										<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
										
									</div>
									<span><a href="/product_d.html#reviews">(9)</a></span>
								-->
								<!-- review 없을 시 -->
								<a href="/product_d.html#reviews"><span class="no-review">Be the first to review</span></a>
								<!-- 모바일에서는 review 없을 시 텍스트를 (Write a review) 로 사용해 주세요. -->
							</div>
							<div class="product-price">
								<!-- 2015-05-07 promotional price 가 있는 경우 
								<div class="suggested-price">
									<p class="price">$3499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Promotional Price</p>
								</div>
								-->
								<!-- 2015-05-07 promotional price 가 없는 경우 -->
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="product-rebate">
									<!-- 2015-05-27 Ecorebates 
										
										data-modelId : 제품 ID
										class : ecorebates-div 필수
									-->
									<div class="ecorebates-div" data-modelId="WM3170CW"></div>
								</div>
							</div>
							<p class="get-details"><a href="#" class="get-details">Get Details <i class="icon icon-arrow-next"></i></a></p>
						</div>
					</div>
				</div>
			</div>
			<div class="product slide">
				<div class="slide-inner">
					<a href="#" class="img-link">
						<img class="lazy" src="/lg4-common/img/placeholder.gif" data-lazy="/img_sample/sample_thumbnail.jpg" alt="59.5” Diagonal 1080p LED TV Full HD Resolution" />
					</a>
					<div class="copy-area">
						<!-- <p class="model"><a href="#">60” Class</a></p> -->
						<p class="model-name"><a href="#">59.5” Diagonal 1080p LED TV Full HD Resolution</a></p>
						<p class="model-num"><a href="#">60LB5200</a></p>
						<div class="details">
							<div class="rating" data-modelid="MD05196020">
								
									<div class="points_wrap">
										
										<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
										
									</div>
									<span><a href="/product_d.html#reviews">(9)</a></span>
								
							</div>
							<div class="product-price">
								<!-- 2015-05-07 promotional price 가 있는 경우 
								<div class="suggested-price">
									<p class="price">$3499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Promotional Price</p>
								</div>
								-->
								<!-- 2015-05-07 promotional price 가 없는 경우 -->
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="product-rebate">
									<!-- 2015-05-27 Ecorebates 
										data-modelId : 제품 ID
										class : ecorebates-div 필수
									-->
									<div class="ecorebates-div" data-modelId="WM3170CW"></div>
								</div>
							</div>
							<p class="get-details"><a href="#" class="get-details">Get Details <i class="icon icon-arrow-next"></i></a></p>
						</div>
					</div>
				</div>
			</div>
			<div class="product slide">
				<div class="slide-inner">
					<a href="#" class="img-link">
						<img class="lazy" src="/lg4-common/img/placeholder.gif" data-lazy="/img_sample/sample_thumbnail.jpg" alt="64.5” Diagonal UHD 4K Smart 3D Curved OLED TV W/ webOS™" />
					</a>
					<div class="copy-area">
						<!-- <p class="model"><a href="#">65” Class</a></p> -->
						<p class="model-name"><a href="#">64.5” Diagonal UHD 4K Smart 3D Curved OLED TV W/ webOS&trade;</a></p>
						<p class="model-num"><a href="#">55EA9800</a></p>
						<div class="details">
							<div class="rating" data-modelid="MD05196021">
								
									<div class="points_wrap">
										
										<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
										
									</div>
									<span><a href="/product_d.html#reviews">(9)</a></span>
								
							</div>
							<div class="product-price">
								<!-- 2015-05-07 promotional price 가 있는 경우 
								<div class="suggested-price">
									<p class="price">$3499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Promotional Price</p>
								</div>
								-->
								<!-- 2015-05-07 promotional price 가 없는 경우 -->
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="product-rebate">
									<!-- 2015-05-27 Ecorebates 
										
										data-modelId : 제품 ID
										class : ecorebates-div 필수
									-->
									<div class="ecorebates-div" data-modelId="WM3170CW"></div>
								</div>
							</div>
							<p class="get-details"><a href="#" class="get-details">Get Details <i class="icon icon-arrow-next"></i></a></p>
						</div>
					</div>
				</div>
			</div>
			<div class="product slide">
				<div class="slide-inner">
					<a href="#" class="img-link">
						<img class="lazy" src="/lg4-common/img/placeholder.gif" data-lazy="/img_sample/sample_thumbnail.jpg" alt="64.5” Diagonal UHD 4K Smart 3D Curved OLED TV W/ webOS™" />
					</a>
					<div class="copy-area">
						<!-- <p class="model"><a href="#">65” Class</a></p> -->
						<p class="model-name"><a href="#">64.5” Diagonal UHD 4K Smart 3D Curved OLED TV W/ webOS&trade;</a></p>
						<p class="model-num"><a href="#">55EA9800</a></p>
						<div class="details">
							<div class="rating" data-modelid="MD05196022">
								
									<div class="points_wrap">
										
										<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
										
									</div>
									<span><a href="/product_d.html#reviews">(9)</a></span>
								
							</div>
							<div class="product-price">
								<!-- 2015-05-07 promotional price 가 있는 경우 
								<div class="suggested-price">
									<p class="price">$3499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Promotional Price</p>
								</div>
								-->
								<!-- 2015-05-07 promotional price 가 없는 경우 -->
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="product-rebate">
									<!-- 2015-05-27 Ecorebates 
										
										data-modelId : 제품 ID
										class : ecorebates-div 필수
									-->
									<div class="ecorebates-div" data-modelId="WM3170CW"></div>
								</div>
							</div>
							<p class="get-details"><a href="#" class="get-details">Get Details <i class="icon icon-arrow-next"></i></a></p>
						</div>
					</div>
				</div>
			</div>
			<div class="product slide">
				<div class="slide-inner">
					<a href="#" class="img-link">
						<img class="lazy" src="/lg4-common/img/placeholder.gif" data-lazy="/img_sample/sample_thumbnail.jpg" alt="64.5” Diagonal UHD 4K Smart 3D Curved OLED TV W/ webOS™" />
					</a>
					<div class="copy-area">
						<!-- <p class="model"><a href="#">65” Class</a></p> -->
						<p class="model-name"><a href="#">64.5” Diagonal UHD 4K Smart 3D Curved OLED TV W/ webOS&trade;</a></p>
						<p class="model-num"><a href="#">55EA9800</a></p>
						<div class="details">
							<div class="rating" data-modelid="MD05196023">
								
									<div class="points_wrap">
										
										<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
										
									</div>
									<span><a href="/product_d.html#reviews">(9)</a></span>
								
							</div>
							<div class="product-price">
								<!-- 2015-05-07 promotional price 가 있는 경우 
								<div class="suggested-price">
									<p class="price">$3499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Promotional Price</p>
								</div>
								-->
								<!-- 2015-05-07 promotional price 가 없는 경우 -->
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="product-rebate">
									<!-- 2015-05-27 Ecorebates 
										
										data-modelId : 제품 ID
										class : ecorebates-div 필수
									-->
									<div class="ecorebates-div" data-modelId="WM3170CW"></div>
								</div>
							</div>
							<p class="get-details"><a href="#" class="get-details">Get Details <i class="icon icon-arrow-next"></i></a></p>
						</div>
					</div>
				</div>
			</div>
			<div class="product slide">
				<div class="slide-inner">
					<a href="#" class="img-link">
						<img class="lazy" src="/lg4-common/img/placeholder.gif" data-lazy="/img_sample/sample_thumbnail.jpg" alt="64.5” Diagonal UHD 4K Smart 3D Curved OLED TV W/ webOS™" />
					</a>
					<div class="copy-area">
						<!-- <p class="model"><a href="#">65” Class</a></p> -->
						<p class="model-name"><a href="#">64.5” Diagonal UHD 4K Smart 3D Curved OLED TV W/ webOS&trade;</a></p>
						<p class="model-num"><a href="#">55EA9800</a></p>
						<div class="details">
							<div class="rating" data-modelid="MD05196024">
								
									<div class="points_wrap">
										
										<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
										
									</div>
									<span><a href="/product_d.html#reviews">(9)</a></span>
								
							</div>
							<div class="product-price">
								<!-- 2015-05-07 promotional price 가 있는 경우 
								<div class="suggested-price">
									<p class="price">$3499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Promotional Price</p>
								</div>
								-->
								<!-- 2015-05-07 promotional price 가 없는 경우 -->
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="product-rebate">
									<!-- 2015-05-27 Ecorebates 
										data-modelId : 제품 ID
										class : ecorebates-div 필수
									-->
									<div class="ecorebates-div" data-modelId="WM3170CW"></div>
								</div>
							</div>
							<p class="get-details"><a href="#" class="get-details">Get Details <i class="icon icon-arrow-next"></i></a></p>
						</div>
					</div>
				</div>
			</div>
			<div class="product slide">
				<div class="slide-inner">
					<a href="#" class="img-link">
						<img class="lazy" src="/lg4-common/img/placeholder.gif" data-lazy="/img_sample/sample_thumbnail.jpg" alt="64.5” Diagonal UHD 4K Smart 3D Curved OLED TV W/ webOS™" />
					</a>
					<div class="copy-area">
						<!-- <p class="model"><a href="#">65” Class</a></p> -->
						<p class="model-name"><a href="#">64.5” Diagonal UHD 4K Smart 3D Curved OLED TV W/ webOS&trade;</a></p>
						<p class="model-num"><a href="#">55EA9800</a></p>
						<div class="details">
							<div class="rating" data-modelid="MD05196025">
								
									<div class="points_wrap">
										
										<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
										
									</div>
									<span><a href="/product_d.html#reviews">(9)</a></span>
								
							</div>
							<div class="product-price">
								<!-- 2015-05-07 promotional price 가 있는 경우 
								<div class="suggested-price">
									<p class="price">$3499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Promotional Price</p>
								</div>
								-->
								<!-- 2015-05-07 promotional price 가 없는 경우 -->
								<div class="purchase-price">
									<p class="price">$1499.<span>99</span></p>
									<p class="legal">Suggested Price</p>
								</div>
								<div class="product-rebate">
									<!-- 2015-05-27 Ecorebates 
										
										data-modelId : 제품 ID
										class : ecorebates-div 필수
									-->
									<div class="ecorebates-div" data-modelId="WM3170CW"></div>
								</div>
							</div>
							<p class="get-details"><a href="#" class="get-details">Get Details <i class="icon icon-arrow-next"></i></a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>