<section class="product-lists product-three with-carousel dot-line" data-slides-to-show="3">
	<h3>MOST VIEWED CELL PHONES</h3>
	<div class="container">
		<div class="carousel light-background">
			<div class="product slide">
				<div class="slide-inner">
					<a href="#" class="img-link">
						<img class="lazy" src="/lg4-common/img/placeholder.gif" data-lazy="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" />
					</a>
					<div class="copy-area">
						<p class="model-name"><a href="#">64.5” Diagonal UHD 4K Smart 3D Curved OLED TV W/ webOS&trade;</a></p>
						<p class="model-num"><a href="#">55EA9800</a></p>
						<div class="details">
							<div class="rating" data-modelid="MD00001294"><!-- 2015-08-11 add data-modelid -->
								<!--
									<div class="points_wrap">
										
										<div class="review_bg" style="width:50%;" title="2.5 out of 5 stars."><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
										
									</div>
									<span><a href="/product_d.html#reviews">(9)</a></span>
								-->
								<!-- review 없을 시 -->
								<a href="/product_d.html#reviews"><span class="no-review">Be the first to review</span></a>
								<!-- 모바일에서는 review 없을 시 텍스트를 (Write a review) 로 사용해 주세요. -->
							</div>
							<p class="get-details"><a href="#" class="get-details">Get Details <i class="icon icon-arrow-next"></i></a></p>
						</div>
					</div>
				</div>
			</div>
			<div class="product slide">
				<div class="slide-inner">
					<a href="#" class="img-link">
						<img class="lazy" src="/lg4-common/img/placeholder.gif" data-lazy="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" />
					</a>
					<div class="copy-area">
						<p class="model-name"><a href="#">64.5” Diagonal UHD 4K Smart 3D Curved OLED TV W/ webOS&trade;</a></p>
						<p class="model-num"><a href="#">55EA9800</a></p>
						<div class="details">
							<div class="rating" data-modelid="MD05196020">
									<div class="points_wrap">
										
										<div class="review_bg" style="width:50%;" title="2.5 out of 5 stars."><!-- 2015-08-04 add title --><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
										
									</div>
									<span><a href="/product_d.html#reviews">(9)</a></span>
								
							</div>
							<p class="get-details"><a href="#" class="get-details">Get Details <i class="icon icon-arrow-next"></i></a></p>
						</div>
					</div>
				</div>
			</div>
			<div class="product slide">
				<div class="slide-inner">
					<a href="#" class="img-link">
						<img class="lazy" src="/lg4-common/img/placeholder.gif" data-lazy="/img_sample/img/product/tvs/55-curved-oled-tv-man-of-steel.jpg" alt="54.6” Diagonal 1080p Smart 3D Curved OLED TV" />
					</a>
					<div class="copy-area">
						<p class="model-name"><a href="#">64.5” Diagonal UHD 4K Smart 3D Curved OLED TV W/ webOS&trade;</a></p>
						<p class="model-num"><a href="#">55EA9800</a></p>
						<div class="details">
							<div class="rating" data-modelid="MD05196021">
									<div class="points_wrap">
										
										<div class="review_bg" style="width:50%;" title="2.5 out of 5 stars."><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
										
									</div>
									<span><a href="/product_d.html#reviews">(9)</a></span>
								
							</div>
							<p class="get-details"><a href="#" class="get-details">Get Details <i class="icon icon-arrow-next"></i></a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>