<section class="support">
	<div class="support-content">
		<h3 class="bottom-hr">
			<p>We're here to</p>
			<p>support you</p> 
		</h3>
		<div class="container">
			<div class="contents-section">
				<div class="contents-title bottom-hr">
					<h4> 
						<p>Contact us for any</p>
						<p>purchasing inquiries.</p> 
					</h4>
					<a class="btn product-support">Product Support</a>
				</div>
				<ul>
					<li class="bottom-hr">
						<div class="icon-block"><i class="icon icon-chat"></i></div>
						<div class="content-block">
							<h5>Live Chat</h5>
							<p><a href="http://service.velaro.com/visitor/requestchat.aspx?siteid=4851&amp;showwhen=inqueue" data-url="http://service.velaro.com/visitor/requestchat.aspx?siteid=4851&amp;showwhen=inqueue" target="_blank" title="new window" class="popup-live-chat">Chat online</a> with LG Support</p> <p>(Weekdays 8am-8pm CST) </p>
						</div>
					</li>
					<li class="bottom-hr">
						<div class="icon-block"><i class="icon icon-support"></i></div>
						<div class="content-block">
							<h5>Call Us</h5>
							<div class="call-row">
								<a href="tel:8882430000" class="red-block">Consumer Support <strong>(888) 243-0000</strong></a>
								<p>6am-midnight CST</p><!-- 2015-07-31 텍스트 수정 -->
							</div>
							<div class="call-row">
								<a href="tel:8888653026" class="red-block">Consumer Support <strong>(888) 865-3026</strong></a>
								<p>8am-6pm CST</p><!-- 2015-07-31 텍스트 수정 -->
							</div>
						</div>
					</li>
					<li>
						<div class="icon-block"><i class="icon icon-email"></i></div>
						<div class="content-block">
							<h5>Email Us</h5>
							<p><a href="#">Send an inquiry</a> to LG Support</p>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
</section>