<section class="support">
	<div class="support-content">
		<h3>We're here to support you with our product. </h3>
		<div class="container">
			<div class="image-section">
				<div class="table-box">
					<div class="image-box"><img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/lg4-common/img/support/PDP_Support.jpg" alt=""></div>
				</div>
			</div>
			<div class="contents-section">
				<h4>Contact us for any purchasing inquiries.</h4>
				<a class="btn product-support">Product Support</a>
				<ul>
					<li>
						<div class="icon-block"><i class="icon icon-chat"></i></div>
						<div class="content-block">
							<h5>Live Chat</h5>
							<p><a href="http://service.velaro.com/visitor/requestchat.aspx?siteid=4851&amp;showwhen=inqueue" data-url="http://service.velaro.com/visitor/requestchat.aspx?siteid=4851&amp;showwhen=inqueue" target="_blank" title="new window" class="popup-live-chat">Chat online</a> with LG Support (Weekdays 8am-8pm CST) </p>
						</div>
					</li>
					<li>
						<div class="icon-block"><i class="icon icon-support"></i></div>
						<div class="content-block">
							<h5>Call Us</h5>
							<p>Call an LG Support Representative</p><!-- 2015-07-31 텍스트 수정 -->
							<p>(800) 243-0000 Consumer (6am-midnight CST)</p><!-- 2015-07-31 텍스트 수정 -->
							<p>(888) 865-3026 Commercial (8am-6pm CST)</p>
						</div>
					</li>
					<li>
						<div class="icon-block"><i class="icon icon-email"></i></div>
						<div class="content-block">
							<h5>Email Us</h5>
							<p><a href="#">Send an inquiry</a> to LG Support</p>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
</section>