<section class="site-map">
	<div class="site-map-header">
		<div class="title-wrap">
			<h1 class="title">SITEMAP</h1>
		</div>
		<a href="#" class="main-link">HOME</a>
	</div>
	<div class="site-map-content">
		<div class="site-map-box">
			<div class="column first">
				<div class="group-box hr-bottom">
					<h2><a href="#">MOBILE</a></h2>
					<ul class="depth1">
						<li><h3><a href="#">Cell Phones</a></h3>
							<ul class="depth2">
								<li><a href="#">By Type</a></li>
								<li><a href="#">All Phones</a></li>
								<li><a href="#">Android Phones</a></li>
								<li><a href="#">Smartphones</a></li>
								<li><a href="#">Basic Phones</a></li>
								<li><a href="#">4G Phones</a></li>
								<li><a href="#">Touch Screen</a></li>
								<li><a href="#">QWERTY Phones</a></li>
								<li><a href="#">Dual-core</a></li>
								<li><a href="#">Quad Core Phones</a></li>
								<li><a href="#">LG Optimus</a></li>
								<li><a href="#">By Carrier</a></li>
								<li><a href="#">AT&amp;T Phones</a></li>
								<li><a href="#">Sprint Phones</a></li>
								<li><a href="#">T-Mobile Phones</a></li>
								<li><a href="#">Verizon Phones</a></li>
								<li><a href="#">All Carriers</a></li>
							</ul>
						</li>
						<li><h3 class="single"><a href="#">Tablets</a></h3></li>
						<li><h3 class="single"><a href="#">Smart Watches</a></h3></li>
						<li><h3><a href="#">Bluetooth &amp; Mobile Accessories</a></h3>
							<ul class="depth2">
								<li><a href="#">By Type</a></li>
								<li><a href="#">Bluetooth Accessories</a></li>
								<li><a href="#">Cell Phone Batteries</a></li>
								<li><a href="#">Cell Phone Chargers</a></li>
								<li><a href="#">Phone Docks</a></li>
								<li><a href="#">Cell Phone Mounts</a></li>
								<li><a href="#">Cases &amp; Covers</a></li>
								<li><a href="#">Pocket Photo Printer</a></li>
								<li><a href="#">Fitness &amp; Activity Trackers</a></li>
							</ul>
						</li>
						<li><h3 class="single"><a href="#">Discover</a></h3></li>
						<li><h3 class="single"><a href="#">LG G3</a></h3></li>
						<li><h3 class="single"><a href="#">LG GATE</a></h3></li>
					</ul>
				</div>
				<div class="group-box">
					<h2><a href="#">COMPUTER PRODUCTS</a></h2>
					<ul class="depth1">
						<li><h3><a href="#">Monitors</a></h3>
							<ul class="depth2">
								<li><a href="#">All Monitors</a></li>
								<li><a href="#">21:9 UltraWide Monitors</a></li>
								<li><a href="#">Gaming Monitors</a></li>
								<li><a href="#">IPS Monitors</a></li>
								<li><a href="#">LED Monitors</a></li>
							</ul>
						</li>
						<li><h3 class="single"><a href="#">All-in-One Chromebase</a></h3></li>
						<li><h3><a href="#">Data Storage</a></h3>
							<ul class="depth2">
								<li><a href="#">All Data Storages</a></li>
								<li><a href="#">Blu-ray Burners and Drives</a></li>
								<li><a href="#">Blu-ray Combo Burners and Drives</a></li>
								<li><a href="#">DVD Burners and Drives</a></li>
							</ul>
						</li>
						<li><h3 class="single"><a href="#">Experience LG Monitors &amp; Computers</a></h3></li>
						<li><h3 class="single"><a href="#">Discover 21:9 UltraWide</a></h3></li>
						<li><h3 class="single"><a href="#">Discover ColorPrime</a></h3></li>
						<li><h3 class="single"><a href="#">Discover Touch10</a></h3></li>
						
					</ul>
				</div>
			</div>
			<div class="column">
				<div class="group-box">
					<h2><a href="#">TV/AUDIO/VIDEO</a></h2>
					<ul class="depth1">
						<li><h3><a href="#">TVs</a></h3>
							<ul class="depth2">
								<li><a href="#">All TVs</a></li>
								<li><a href="#">OLED TV</a></li>
								<li><a href="#">Prime 4K UHD TVs</a></li>
								<li><a href="#">4K Ultra HD TV</a></li>
								<li><a href="#">Smart TV</a></li>
								<li><a href="#">LED TV</a></li>
								<li><a href="#">Plasma TV</a></li>
							</ul>
						</li>
						<li><h3><a href="#">Home Audio / Video</a></h3>
							<ul class="depth2">
								<li><a href="#">All Home Audio / Video</a></li>
								<li><a href="#">Wireless Audio</a></li>
								<li><a href="#">Home Theater Systems</a></li>
								<li><a href="#">Sound Bars</a></li>
								<li><a href="#">SoundPlates&trade;</a></li>
								<li><a href="#">Blu-ray Players</a></li>
							</ul>
						</li>
						<li><h3 class="single"><a href="#">Docking Stations</a></h3></li>
						<li><h3 class="single"><a href="#">Projectors</a></h3></li>
						<li><h3><a href="#">TV Accessories &amp; Connected Devices</a></h3>
							<ul class="depth2">
								<li><a href="#">All TV Accessories</a></li>
								<li><a href="#">3D Glasses</a></li>
								<li><a href="#">Wall Mounts</a></li>
							</ul>
						</li>
						<li><h3 class="single"><a href="#">Fitness &amp; Activity Trackers</a></h3></li>
						<li><h3 class="single"><a href="#">Experience LG Televisions</a></h3></li>
						<li><h3 class="single"><a href="#">Discover LG Smart TV</a></h3></li>
						<li><h3 class="single"><a href="#">Discover OLED TV</a></h3></li>
						<li><h3 class="single double"><a href="#">Discover Ultra HD 4K TV</a></h3></li>
						<li><h3 class="single"><a href="#">Discover LG SoundPlate™</a></h3></li>
						<li><h3 class="single double"><a href="#">Discover Blu-ray and Home Theater</a></h3></li>
						<li><h3 class="single double"><a href="#">Discover Fitness + Activity Trackers</a></h3></li>
						<li><h3 class="single"><a href="#">Discover LG Promotions</a></h3></li>
						<li><h3 class="single"><a href="#">Redeem Spotify Offer</a></h3></li>
						<li><h3 class="single"><a href="#">Discover LG Moving Tips</a></h3></li>
					</ul>
				</div>
			</div>
			<div class="column">
				<div class="group-box">
					<h2><a href="#">APPLIANCES</a></h2>
					<ul class="depth1">
						<li><h3 class="single"><a href="#">For Your Kitchen</a></h3></li>
						<li><h3><a href="#">Refrigerators</a></h3>
							<ul class="depth2">
								<li><a href="#">Find the Right Refrigerator</a></li>
								<li><a href="#">All Refrigerators</a></li>
								<li><a href="#">French Door</a></li>
								<li><a href="#">Door-In-Door™</a></li>
								<li><a href="#">Counter Depth</a></li>
								<li><a href="#">Side by Side</a></li>
								<li><a href="#">Bottom Freezer</a></li>
								<li><a href="#">Top Freezer</a></li>
								<li><a href="#">Refrigerator Accessories</a></li>
							</ul>
						</li>
						<li><h3><a href="#">Ranges &amp; Ovens</a></h3>
							<ul class="depth2">
								<li><a href="#">Find the Right Range</a></li>
								<li><a href="#">All Ranges</a></li>
								<li><a href="#">Electric Ranges</a></li>
								<li><a href="#">Gas Ranges</a></li>
							</ul>
						</li>
						<li><h3 class="single"><a href="#">Knobs and Accessories</a></h3></li>
						<li><h3 class="single"><a href="#">Wall Ovens</a></h3></li>
						<li><h3 class="single"><a href="#">Cooktops</a></h3></li>
						<li><h3 class="single"><a href="#">Microwave Ovens</a></h3></li>
						<li><h3 class="single double"><a href="#">Dishwashers</a></h3></li>
						<li><h3 class="single"><a href="#">LG Studio</a></h3></li>
						<li><h3 class="single"><a href="#">Discover LG Washers</a></h3></li>
						<li><h3 class="single"><a href="#">Discover LG Refrigerators</a></h3></li>
						<li><h3 class="single"><a href="#">Washers &amp; Dryers</a></h3></li>
						<li><h3><a href="#">Washers</a></h3>
							<ul class="depth2">
								<li><a href="#">Find the Right Washer</a></li>
								<li><a href="#">All Washers</a></li>
								<li><a href="#">Front Load Washers</a></li>
								<li><a href="#">Top Load Washers</a></li>
								<li><a href="#">TurboWash™ Washers</a></li>
								<li><a href="#">Washer / Dryer Accessories</a></li>
							</ul>
						</li>
						<li><h3 class="single"><a href="#">Dryers</a></h3></li>
						<li><h3 class="single"><a href="#">Washer/Dryer Combos</a></h3></li>
						<li><h3 class="single"><a href="#">For Your Home</a></h3></li>
						<li><h3><a href="#">Air Conditioners</a></h3>
							<ul class="depth2">
								<li><a href="#">All Air Conditioners</a></li>
								<li><a href="#">Portable Air Conditioners</a></li>
								<li><a href="#">Window Air Conditioners</a></li>
								<li><a href="#">Wall Air Conditioners</a></li>
								<li><a href="#">Casement Air Conditioners</a></li>
								<li><a href="#">Air Conditioner Accessories</a></li>
							</ul>
						</li>
						<li><h3 class="single"><a href="#">Dehumidifiers</a></h3></li>
						<li><h3 class="single"><a href="#">LED Lights</a></h3></li>
						<li><h3><a href="#">Appliance Accessories</a></h3>
							<ul class="depth2">
								<li><a href="#">Refrigerator Filters</a></li>
							</ul>
						</li>
						<li><h3 class="single"><a href="#">Discover LG Appliances</a></h3></li>
						<li><h3 class="single"><a href="#">Discover LG Laundry</a></h3></li>
						<li><h3 class="single"><a href="#">Discover LG Refrigerators</a></h3></li>
						<li><h3 class="single"><a href="#">Discover LG Dishwashers</a></h3></li>
						<li><h3 class="single"><a href="#">Discover LG Cooking</a></h3></li>
						<li><h3 class="single"><a href="#">Discover LG Smart ThinQ</a></h3></li>
						<li><h3 class="single double"><a href="#">Discover LG Studio</a></h3></li>
						<li><h3 class="single double"><a href="#">Recipes</a></h3></li>
						<li><h3 class="single"><a href="#">Discover LG Promotions</a></h3></li>
						<li><h3 class="single"><a href="#">Discover LG Moving Tips</a></h3></li>
					</ul>
				</div>
			</div>
			<div class="column">
				<div class="group-box hr-bottom">
					<h2><a href="#">COMMERCIAL</a></h2>
					<ul class="depth1">
						<li><h3 class="single"><a href="#">Automotive</a></h3></li>
						<li><h3 class="single"><a href="#">Commercial Display</a></h3></li>
						<li><h3 class="single"><a href="#">Commercial AC</a></h3></li>
						<li><h3 class="single"><a href="#">Lighting</a></h3></li>
						<li><h3 class="single"><a href="#">Solar</a></h3></li>
						<li><h3 class="single"><a href="#">LG GATE</a></h3></li>
						<li><h3 class="single"><a href="#">Commercial Laundry</a></h3></li>
					</ul>
				</div>
				<div class="group-box hr-bottom">
					<h2><a href="#">LG LIVE</a></h2>
					<ul class="depth1">
						<li><h3><a href="#">Our Story</a></h3>
							<ul class="depth2">
								<li><a href="#">See how LG makes you</a></li>
								<li><a href="#">find the inspiration in</a></li>
								<li><a href="#">your daily life.</a></li>
							</ul>
						</li>
						<li><h3 class="single"><a href="#">Social Board</a></h3></li>
						<li><h3 class="single"><a href="#">Inside LG</a></h3></li>
					</ul>
				</div>
				<div class="group-box">
					<h2><a href="#">SUPPORT</a></h2>
					<ul class="depth1">
						<li><h3 class="single"><a href="#">Register a Product</a></h3></li>
						<li><h3 class="single"><a href="#">Download &amp; Manuals</a></h3></li>
						<li><h3 class="single"><a href="#">Videos &amp; Tutorials</a></h3></li>
						<li><h3 class="single"><a href="#">Help Library</a></h3></li>
						<li><h3><a href="#">Repair Service</a></h3>
							<ul class="depth2">
								<li><a href="#">Schedule a Repair</a></li>
								<li><a href="#">Track Repair Service</a></li>
								<li><a href="#">Find Repair Provider</a></li>
							</ul>
						</li>
						<li><h3 class="single"><a href="#">Contact Us</a></h3></li>
						<li><h3 class="single"><a href="#">Announcements</a></h3></li>
						<li><h3 class="single"><a href="#">Parts &amp; Accessories</a></h3></li>
						<li><h3 class="single"><a href="#">Extended Service Plan</a></h3></li>
						<li><h3 class="single"><a href="#">Upload Documents</a></h3></li>
						<li><h3 class="single"><a href="#">MyLG Login</a></h3></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>