<div class="tabs app-tabs">
	<section class="stickynav">
		<div class="sticky_wrap"><!-- 2015-05-06 delete itemscope -->
			<div class="product_name"><!-- 2015-06-11 SEO delete  itemprop="name" -->55" Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV 55" Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV 55" Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV</div>
			<div class="product_wrap">
				<div class="product_information" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
					<!-- Promotional Price 가 없는 경우  
					<div class="price_before"><p class="price">$3499.<sup>99</sup></p><span>Suggested Price</span></div>
					<div class="price_after"  itemprop="priceCurrency" content="USD"><p class="price" itemprop="price" content="1199.99">$1199.<sup>99</sup></p><span>Promotional Price</span></div>
					-->
					<div class="price_after" itemprop="priceCurrency" content="USD"><p class="price" itemprop="price" content="1199.99">$1199.<sup>99</sup></p><span>Suggested Price</span></div>
					
					<link itemprop="availability" href="http://schema.org/InStock" content="In stock" /><!-- 2015-05-01 - In stock, Out of stock, Pre-order -->
					<!-- 2015-05-01 warranty 항목은 현재 내용이 없어서 추가하지 못했고, 추후 추가될 수 있음. -->
				</div>
				<div class="purchase_options">
					<div class="btn_wrap">
						<!-- button set -->
						<!-- <a href="https://usstore.lg.com/store?Action=buy&Env=BASE&Locale=en_US&SiteID=lgus&productID=306352300&quantity=1" class="btn">Pre Order</a> -->
						<a href="https://usstore.lg.com/store?Action=buy&Env=BASE&Locale=en_US&SiteID=lgus&productID=306352300&quantity=1" class="btn" data-sc-item="add-to-cart" data-sc-value="{모델코드}">Add to Cart</a>
						<a href="javascript:void(0)" class="btn buynow" data-sku="3429088" data-partner-id="LG" value="buy now" title="Open New Window" data-sc-item="buy-now" data-sc-value="{모델코드}">Buy Now</a>
						<a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}"><!-- 2015-07-07 DTM -->Where to buy</a>
						<!-- // button set -->
					</div>
					<div class="purchase_options_buttons">
						<ul class="options">
							<!-- 2015-06-08 Compare 기능 추가 -->
							<li class="compare compare-check static">
								<label>
									<input type="checkbox" class="compare compare_n" data-product-id="LRG3081ST" name="compare"><span>Add to Compare</span>
								</label>
								<span class="compare_y hide"><a href="#" data-sc-item="compare-price" data-sc-value="{MSRP-price}"><!-- 2015-07-07 DTM -->COMPARE (<em>0</em>)</a></span>
							</li>
							<li class="print"><a href="#">PRINT</a></li><!-- add print class -->
							<li class="last">
								<div class="share_box" data-title-new-window="Open the new window"><!-- 2015-08-24 add data-title-new-window -->
									<!-- 2015-08-05 add title -->
									<a href="#" title="Open the share layer popup" data-url="/ajaxData/share.html?ogTitle=LG G4 AT&T: See the Great, Feel the Great | LG USA&ogImg=http://www.lg.com/us/images/cell-phones/h810-genuine-leather-black/copy-h810-genuine-leather-black-200x150.jpg&thisUrl=http://www.lg.com/us/cell-phones/lg-H810-Genuine-Leather-Black-g4" class="stickyshare">SHARE<i class="icon icon-share"></i></a>
									<!-- delete .product_share & add data-url 2015-07-21 -->
								</div>
							</li>
						</ul>
					</div>
				</div>
				<div class="review_points" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
					<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" />
					<meta itemprop="bestRating" content="5" />
					<meta itemprop="worstRating" content="1" />
					<a href="#">
						<div class="points_wrap">
							<div class="review_bg" style="width:70%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
							<meta itemprop="ratingValue" content="4.5" />
						</div>
						<span itemprop="reviewCount" content="9">(9 Reviews)</span>
					</a>
					<!--
					<a href="#">
						<span class="no-review">Be the first to review</span>
					</a>
					-->
				</div>
			</div>
			<!-- 2015-05-21 Ecorebates 
				
				data-modelId : 제품 ID
				class : ecorebates-div 필수
			-->
			<div class="ecorebates-div" data-modelId="MD05141340"></div>
		</div>
	</section>
	<div class="tabs-nav-wrapper"><!-- Web Menu -->
		<ul class="tabs-nav column5" itemscope itemtype="http://schema.org/SiteNavigationElement"><!-- tab5 : column5 , tab4 : column4 , tab3 : column3 -->
			<!-- 2015-07-02
				FLOOD1 함수 (Floodlight Script) Guide
				MOBILE과 TV/AUDIO/VIDEO  카테고리에만 추가됩니다.
			-->
			<li itemprop="name" class="active">
				<a data-toggle="tab" itemprop="url" href="/product_d.html#features"><!-- 2015-08-21 edit url {my url}#features, add itemprop="url" --><i class="icon icon-features"></i><span>Features</span></a>
				<!-- <meta itemprop="url" content="/product_d.html#features" /> --><!-- delete meta 2015-08-21 -->
			</li><!-- no space
			 --><li itemprop="name">
				<a data-toggle="tab" itemprop="url" href="/product_d.html#tech-specs" onclick="FLOOD1('mugf40', 'unive001', '1?');"><!-- 2015-08-21 edit url {my url}#tech-specs, add itemprop="url" --><i class="icon icon-specs"></i><span>Tech Specs</span></a>
				<!-- <meta itemprop="url" content="/product_d.html#tech-specs" /> --><!-- delete meta 2015-08-21 -->
				<!-- 2015-07-02
					MOBILE 카테고리의 경우 : FLOOD1('mugf40', 'unive001', '1?');
					TV/AUDIO/VIDEO 카테고리의 경우 : FLOOD1('hebxl0', 'unive00', '1?');
				-->
			</li><!-- no space
			 --><li itemprop="name">
				<a data-toggle="tab" itemprop="url" href="/product_d.html#ratings-reviews" onclick="FLOOD1('mugf40', 'unive00', '1?');"><!-- 2015-08-21 edit url {my url}#ratings-reviews, add itemprop="url" --><i class="icon icon-reviews"></i><span>Ratings &amp; Reviews</span></a>
				<!-- <meta itemprop="url" content="/product_d.html#ratings-reviews" /> --><!-- delete meta 2015-08-21 -->
				<!-- 2015-07-02
					MOBILE 카테고리의 경우 : FLOOD1('mugf40', 'unive00', '1?');
					TV/AUDIO/VIDEO 카테고리의 경우 : FLOOD1('hebxl0', 'unive002', '1?');
				-->
			</li><!-- no space
			 --><li itemprop="name">
				<a data-toggle="tab" itemprop="url" href="/product_d.html#accessories"><!-- 2015-08-21 edit url {my url}#accessories, add itemprop="url" --><i class="icon icon-accessories"></i><span>Accessories</span></a>
				<!-- <meta itemprop="url" content="/product_d.html#accessories" /> --><!-- delete meta 2015-08-21 -->
			</li><!-- no space
			 --><li itemprop="name">
				<a data-toggle="tab" itemprop="url" href="/product_d.html#support"><!-- 2015-08-21 edit url {my url}#support, add itemprop="url" --><i class="icon icon-support"></i><span>Support</span></a>
				<!-- <meta itemprop="url" content="/product_d.html#support" /> --><!-- delete meta 2015-08-21 -->
			</li>
		</ul>
	</div>
	<div class="tabs-panels">
		<div class="tabs-panel active" data-id="features" id="features">
			<div class="accordion-content">
				<!--#include virtual="/incl/components/M01A-Full-Bleed-Background-Text-Center-Static-Image.inc" -->
				<!--#include virtual="/incl/components/M10-Technical-Featurres-Blocks.inc" -->
				<!--#include virtual="/incl/components/M02A-Side-By-Side-Text-On-Right-Static-Image.inc" -->
				<!--#include virtual="/incl/components/M03A-Side-By-Side-Text-On-Left-Static-Image.inc" -->
			</div>
		</div>
		<div class="tabs-panel" data-id="tech-specs" id="tech-specs">
			<div class="accordion-content">
				<!--#include virtual="/incl/components/technical-specs.inc" -->
			</div>
		</div>
		<div class="tabs-panel" data-id="ratings-reviews" id="ratings-reviews">
			<div class="accordion-content">
				<h3 class="review-title">What People Are Saying</h3><!-- 2015-07-13 -->
				<div id="BVRRContainer"></div><!-- 2015-06-10 -->
			</div>
		</div>
		<div class="tabs-panel" data-id="accessories" id="accessories">
			<div class="accordion-content">
				<!--#include virtual="/incl/components/product-selection-accessories.inc" -->
			</div>
		</div>
		<div class="tabs-panel" data-id="support" id="support">
			<div class="accordion-content">
				<!--#include virtual="/incl/components/product-support.inc" -->
			</div>
		</div>
	</div>
</div>

