<div class="tabs app-tabs">
	<section class="stickynav-m">
		<div class="sticky_wrap"><!-- 2015-05-06 delete itemscope -->
			<!-- 2015-06-11 SEO delete -->
			<!-- <meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV 55” Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV 55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" /> -->
			<div class="product_information" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
				<!-- Promotional Price 가 있는 경우 
				<div class="price_before"><p class="price">$3499.<sup>99</sup></p><span>Suggested Price</span></div>
				<div class="price_after" itemprop="priceCurrency" content="USD"><span>Promotional Price</span><p class="price" itemprop="price" content="1199.99">$1199.<sup>99</sup></p></div>
				-->
				<!-- Promotional Price 가 없는 경우 -->
				<div class="price_before_p" itemprop="priceCurrency" content="USD"><p class="price" itemprop="price" content="1199.99">$3499.<sup>99</sup></p><span>Suggested Price</span></div>
				
				<!-- 2015-05-21 Ecorebates 
					data-modelId : 제품 ID
					class : ecorebates-div 필수
				-->
				<div class="ecorebates-div" data-modelId="MD05141340"></div>
				<link itemprop="availability" href="http://schema.org/InStock" content="In stock" /><!-- 2015-05-01 - In stock, Out of stock, Pre-order -->
				<!-- 2015-05-01 warranty 항목은 현재 내용이 없어서 추가하지 못했고, 추후 추가될 수 있음. -->
			</div>
			<div class="purchase_options">
				<div class="btn_wrap">
					<!-- button set -->
					<!-- <span class="btn_wrap_addtocart"><a href="https://usstore.lg.com/store?Action=buy&Env=BASE&Locale=en_US&SiteID=lgus&productID=306352300&quantity=1" class="btn">Pre Order</a></span> -->
					<span class="btn_wrap_addtocart"><a href="https://usstore.lg.com/store?Action=buy&Env=BASE&Locale=en_US&SiteID=lgus&productID=306352300&quantity=1" class="btn" data-sc-item="add-to-cart" data-sc-value="{모델코드}">Add to Cart</a></span>
					<span class="btn_wrap_buynow"><a href="javascript:void(0)" class="btn buynow" data-sku="3429088" data-partner-id="LG" value="buy now" title="Open New Window" data-sc-item="buy-now" data-sc-value="{모델코드}">Buy Now</a></span>
					<span class="btn_wrap_wheretobuy"><a href="#" class="btn" data-sc-item="where-to-buy" data-sc-value="{모델코드}"><!-- 2015-07-07 DTM -->Where to Buy</a></span>
					<!-- // button set -->
					<!-- <span class="btn_wrap_compare"><button class="btn gray compare">Compare</button></span> -->
					<div class="share_box" data-title-new-window="Open the new window"><!-- 2015-08-24 add data-title-new-window -->
						<!-- 2015-08-05 add title -->
						<button class="btn gray stickyshare" title="Open the share layer popup" data-url="/ajaxData/share-m.html?ogTitle=LG G4 AT&T: See the Great, Feel the Great | LG USA&ogImg=http://www.lg.com/us/images/cell-phones/h810-genuine-leather-black/copy-h810-genuine-leather-black-200x150.jpg&thisUrl=http://www.lg.com/us/cell-phones/lg-H810-Genuine-Leather-Black-g4">Share</button>
						<!-- delete .product_share & add data-url 2015-07-21 -->
					</div>
				</div>
			</div>
			<div class="review_points" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
				<meta itemprop="name" content="55”Class (54.6” Diagonal) 1080p Smart 3D Curved OLED TV" /><!-- 2015-05-05 - itemReviewed 를 name으로 변경 / 해당 값은 h2 와 동일하게 넣어 주세요. -->
				<meta itemprop="bestRating" content="5" />
				<meta itemprop="worstRating" content="1" />
				<!-- 2015-05-20 리뷰 별점이 있는 경우 -->
				<a href="#">
					<div class="points_wrap">
						<div class="review_bg" style="width:70%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
						<meta itemprop="ratingValue" content="4.5" />
					</div>
					<span itemprop="reviewCount" content="9">(9)</span><!-- 2015-07-07 for DTM (add content) -->
				</a>
				<!--
				<a href="#">
					<span class="no-review">Be the first to review</span>
				</a>
				-->
			</div>
		</div>
		<div class="tabs-panels">
			<!-- 2015-07-02
				FLOOD1 함수 (Floodlight Script) Guide
				MOBILE과 TV/AUDIO/VIDEO  카테고리에만 추가됩니다.
			-->
			<div class="tabs-panel" data-id="features" id="features">
				<div class="accordion-tab" itemscope itemtype="http://schema.org/SiteNavigationElement"><a itemprop="url" href="/product_m.html#features" data-toggle="accordion-tab"><!-- 2015-08-21 edit url {my url}#features, add itemprop="url" --><span itemprop="name"><i class="icon icon-tab-plus"></i><i class="icon icon-tab-minus"></i>Features</span></a><!--<meta itemprop="url" content="/product_m.html#features" /> delete meta 2015-08-21 --></div><!-- Mobile Menu -->
				<div class="accordion-content">
					<!--#include virtual="/incl/components/M01A-Full-Bleed-Background-Text-Center-Static-Image.inc" -->
					<!--#include virtual="/incl/components/M10-Technical-Featurres-Blocks.inc" -->
					<!--#include virtual="/incl/components/M02A-Side-By-Side-Text-On-Right-Static-Image.inc" -->
					<!--#include virtual="/incl/components/M03A-Side-By-Side-Text-On-Left-Static-Image.inc" -->
				</div>
			</div>
			<div class="tabs-panel" data-id="tech-specs" id="tech-specs">
				<!-- 2015-07-02
					MOBILE 카테고리의 경우 : FLOOD1('mugf40', 'unive001', '1?');
					TV/AUDIO/VIDEO 카테고리의 경우 : FLOOD1('hebxl0', 'unive00', '1?');
				-->
				<div class="accordion-tab" itemscope itemtype="http://schema.org/SiteNavigationElement"><a itemprop="url" href="/product_m.html#tech-specs" data-toggle="accordion-tab" onclick="FLOOD1('mugf40', 'unive001', '1?');"><!-- 2015-08-21 edit url {my url}#tech-specs, add itemprop="url" --><span itemprop="name"><i class="icon icon-tab-plus"></i><i class="icon icon-tab-minus"></i>Tech Specs</span></a><!--<meta itemprop="url" content="/product_m.html#tech-specs" /> delete meta 2015-08-21 --></div><!-- Mobile Menu -->
				<div class="accordion-content">
					<!--#include virtual="/incl/components/technical-specs-mobile.inc" -->
				</div>
			</div>
			<div class="tabs-panel" data-id="ratings-reviews" id="ratings-reviews">
				<!-- 2015-07-02
					MOBILE 카테고리의 경우 : FLOOD1('mugf40', 'unive00', '1?');
					TV/AUDIO/VIDEO 카테고리의 경우 : FLOOD1('hebxl0', 'unive002', '1?');
				-->
				<div class="accordion-tab" itemscope itemtype="http://schema.org/SiteNavigationElement"><a itemprop="url" href="/product_m.html#ratings-reviews" data-toggle="accordion-tab" onclick="FLOOD1('mugf40', 'unive00', '1?');"><!-- 2015-08-21 edit url {my url}#ratings-reviews, add itemprop="url" --><span itemprop="name"><i class="icon icon-tab-plus"></i><i class="icon icon-tab-minus"></i>Ratings &amp; Reviews</span></a><!--<meta itemprop="url" content="/product_m.html#ratings-reviews" /> delete meta 2015-08-21 --></div><!-- Mobile Menu -->
				<div class="accordion-content">
					<h3 class="review-title">What People Are Saying</h3><!-- 2015-07-13 -->
					<div id="BVRRContainer"></div><!-- 2015-06-10 -->
				</div>
			</div>
			<div class="tabs-panel" data-id="accessories" id="accessories">
				<div class="accordion-tab" itemscope itemtype="http://schema.org/SiteNavigationElement"><a itemprop="url" href="/product_m.html#accessories" data-toggle="accordion-tab"><!-- 2015-08-21 edit url {my url}#accessories, add itemprop="url" --><span itemprop="name"><i class="icon icon-tab-plus"></i><i class="icon icon-tab-minus"></i>Accessories</span></a><!-- <meta itemprop="url" content="/product_m.html#accessories" /> delete meta 2015-08-21 --></div><!-- Mobile Menu -->
				<div class="accordion-content">
					<!--#include virtual="/incl/components/product-selection-accessories.inc" -->
				</div>
			</div>
			<div class="tabs-panel" data-id="support" id="support">
				<div class="accordion-tab" itemscope itemtype="http://schema.org/SiteNavigationElement"><a itemprop="url" href="/product_m.html#support" data-toggle="accordion-tab"><!-- 2015-08-21 edit url {my url}#support, add itemprop="url" --><span itemprop="name"><i class="icon icon-tab-plus"></i><i class="icon icon-tab-minus"></i>Support</span></a><!-- <meta itemprop="url" content="/product_m.html#support" /> delete meta 2015-08-21 --></div><!-- Mobile Menu -->
				<div class="accordion-content">
					<!--#include virtual="/incl/components/product-support-m.inc" -->
				</div>
			</div>
		</div>
	</section>
</div>