<section class="tech_spec">
	<div class="tech-spec-container">
		<!-- 2015-07-06 pdf 다운로드 추가 -->
		<div class="tech_spec_download">
			<div class="tech_spec_wrap">
				<a href="#" class="btn">Download Spec Sheet</a><!-- 2015-08-05 edit text -->
			</div>
		</div>
		<!-- 끝 -->
		<div class="tech_spec_wrap">
			<table>
				<caption>Summary</caption>
				<tbody>
					<tr>
						<th scope="row">SCREEN SIZE</th>
						<td>55" Class</td>
					</tr>
					<tr>
						<th scope="row">CLASS</th>
						<td>54.6" Diagonal</td>
					</tr>
					<tr>
						<th scope="row">RESOLUTION</th>
						<td>1920X1080p</td>
					</tr>
					<tr>
						<th scope="row">BLU TYPE</th>
						<td>OLED TV</td>
					</tr>
				</tbody>
			</table>
		</div>
		<!--
		<div class="tech_spec_wrap">
			<table>
				<caption>Dimensions &amp; Weight</caption>
				<tbody>
					<tr>
						<th scope="row">WIDTH</th>
						<td itemprop="width">48.31"</td>
					</tr>
					<tr>
						<th scope="row">HEIGHT</th>
						<td itemprop="height">31.44"</td>
					</tr>
					<tr>
						<th scope="row">THINNESS</th>
						<td>4.5mm</td>
					</tr>
					<tr>
						<th scope="row">PACKAGING<br/>(WxHxD)</th>
						<td>48.31"x31.44"x7.56"</td>
					</tr>
					<tr>
						<th scope="row">TV WEIGHT</th>
						<td itemprop="weight">37.92 lbs</td>
					</tr>
					<tr>
						<th scope="row">PACKAGING WEIGHT</th>
						<td itemprop="weight">61.29 lbs</td>
					</tr>
				</tbody>
			</table>
		</div>
		-->
		<div class="tech_spec_wrap"><!-- 2015-08-24 -->
			<table>
				<caption>Dimensions &amp; Weight</caption>
				<tbody>
					<tr>
						<th scope="row">5.87" (H) X 2.96" (W)</th>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="tech_spec_wrap">
			<table>
				<caption>Video</caption>
				<tbody>
					<tr>
						<th scope="row">THX® CERTIFIED DISPLAY</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">DUAL CORE PROCESSOR</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">TRIPLE XD&trade; ENGINE</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">RESOLUTION UPSCALER</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">PICTURE MODE</th>
						<td>6 MODES <br/>16:9, Just Scan, Original, 4:3, Cinema Zoom, Zoom</span></td>
					</tr>
					<tr>
						<th scope="row">JUST SCAN</th>
						<td>HDMI: 1080P <br />Component: 1080I <br />RF: 720P</td>
					</tr>
					<tr>
						<th scope="row">AV MOVE II</th>
						<td>3 MODES <br/>Cinema, Game, Off</td>
					</tr>
					<tr>
						<th scope="row">PICTURE WIZARD</th>
						<td>YES</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="tech_spec_wrap">
			<table>
				<caption>Audio</caption>
				<tbody>
					<tr>
						<th scope="row">SPEAKER SYSTEM</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">AUDIO OUTPUT POWER <br/>(WATTS - THD 10%)</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">MONO/STEREO/DUAL <br/>(MTS/SAP)</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">DOLBY&reg; DIGITAL DECODER</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">DTS DECODER</th>
						<td>6 MODES 16:9, Just Scan, Original, 4:3, Cinema Zoom, Zoom</td>
					</tr>
					<tr>
						<th scope="row">SOUND MODE</th>
						<td>HDMI: 1080P <br />Component: 1080i <br />RF: 720P</td>
					</tr>
					<tr>
						<th scope="row">CLEAR VOICE II</th>
						<td>3 MODES Cinema, Game, Off</td>
					</tr>
					<tr>
						<th scope="row">SOUND OPTIMIZE</th>
						<td>YES</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="tech_spec_wrap">
			<table>
				<caption>Connectivity</caption>
				<tbody>
					<tr>
						<th scope="row">WI-FI&reg; BUILT-IN</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">WI-FI DIRECT</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">WINDOWS 8 CERTIFIED</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">DLNA CERTIFIED</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">INTEL&reg; WIRELESS DISPLAY (WIDI)</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">MHL&trade; (MOBILE HIGH-DEFINITION LINK)</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">NFC (NEAR FIELD COMMUNICATIONS)</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">SIMPLINK™ (HDMI™ CEC)</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">USB PLAYBACK</th>
						<td>DivX HD&reg;, JPEG, JPG, MPO, AC3 (Dolby&reg; Digital), EAC3, HAAC, AAC, MPEG, MP3, PCM, DTS®</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="tech_spec_wrap">
			<table>
				<caption>AV Inputs/Outputs</caption>
				<tbody>
					<tr>
						<th scope="row">RF IN (ANTENNA/CABLE)</th>
						<td>1 (REAR)</td>
					</tr>
					<tr>
						<th scope="row">AV IN</th>
						<td>1 (REAR)</td>
					</tr>
					<tr>
						<th scope="row">COMPONENT VIDEO IN(Y, PB, PR + AUDIO)</th>
						<td>1 (REAR)</td>
					</tr>
					<tr>
						<th scope="row">HDMI™/HDCP IN</th>
						<td>4 (SIDE)</td>
					</tr>
					<tr>
						<th scope="row">USB 3.0/2.0 IN</th>
						<td>3 (SIDE)</td>
					</tr>
					<tr>
						<th scope="row">DIGITAL AUDIO OUT (OPTICAL)</th>
						<td>1 (REAR)</td>
					</tr>
					<tr>
						<th scope="row">HEADPHONE OUT</th>
						<td>1 (SIDE)</td>
					</tr>
					<tr>
						<th scope="row">RS-232C (CONTROL/SERVICE)</th>
						<td>1 USB TO <br/>RS232C (REAR)</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="tech_spec_wrap">
			<table>
				<caption>Power</caption>
				<tbody>
					<tr>
						<th scope="row">ENERGY STAR&reg; QUALIFIED</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">POWER SUPPLY <br/>(VOLTAGE, Hz)</th>
						<td>100V ~ 240V, 50/60 Hz</td>
					</tr>
					<tr>
						<th scope="row">POWER CONSUMPTION</th>
						<td>Under 85W, Max 291W</td>
					</tr>
					<tr>
						<th scope="row">STANDBY MODE</th>
						<td>0.3W</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>