<section class="tech_spec">
	<div class="tech-spec-container">
		<!-- 2015-07-06 pdf 다운로드 추가 -->
		<div class="tech_spec_download">
			<div class="tech_spec_wrap">
				<a href="#" class="btn">Download Spec Sheet</a><!-- 2015-08-05 edit text -->
			</div>
		</div>
		<!-- 끝 -->
		<div class="tech_spec_wrap">
			<table class="product-summary" >
				<caption>Summary</caption>
				<thead>
					<tr>
						<th scope="col">SCREEN SIZE</th>
						<th scope="col">CLASS</th>
						<th scope="col">RESOLUTION</th>
						<th scope="col">BLU TYPE</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>55" Class</td>
						<td>54.6" Diagonal</td>
						<td>1920X1080p</td>
						<td>OLED TV</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="tech_spec_wrap"><!-- 2015-06-02 별도 관리 영역 / 웹에서만 출력 -->
			<table class="product-dimensions">
				<caption>Dimensions &amp; Weight</caption>
				<tr>
					<td scope="col"><img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/img/techspec/tvs/65-curved-oled-tv.jpg" alt='LG Smart TV - WIDTH 48.31", HEIGHT 31.44", THINNESS 4.5mm' /></td>
				</tr>
				<tr>
					<td>Packaging (WxHxD) 48.31"x31.44"x7.56" | TV Weight 37.92 lbs | Packaging Weight 61.29 lbs. </td><!-- 2015-06-11 SEO delete span teg -->
				</tr>
			</table>
		</div>
		<div class="tech_spec_wrap">
			<table>
				<caption>Video</caption>
				<tbody>
					<tr>
						<th scope="row">THX® CERTIFIED DISPLAY</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">DUAL CORE PROCESSOR</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">TRIPLE XD&trade; ENGINE</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">RESOLUTION UPSCALER</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">PICTURE MODE</th>
						<td>6 MODES 16:9, Just Scan, Original, 4:3, Cinema Zoom, Zoom</td>
					</tr>
					<tr>
						<th scope="row">JUST SCAN</th>
						<td>HDMI: 1080P  Component: 1080I  RF: 720P</td>
					</tr>
					<tr>
						<th scope="row">AV MOVE II</th>
						<td>3 MODES Cinema, Game, Off</td>
					</tr>
					<tr>
						<th scope="row">PICTURE WIZARD</th>
						<td>YES</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="tech_spec_wrap">
			<table>
				<caption>Audio</caption>
				<tbody>
					<tr>
						<th scope="row">SPEAKER SYSTEM</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">AUDIO OUTPUT POWER  (WATTS - THD 10%)</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">MONO/STEREO/DUAL  (MTS/SAP)</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">DOLBY&reg; DIGITAL DECODER</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">DTS DECODER</th>
						<td>6 MODES 16:9, Just Scan, Original, 4:3, Cinema Zoom, Zoom</td>
					</tr>
					<tr>
						<th scope="row">SOUND MODE</th>
						<td>HDMI: 1080P  Component: 1080I  RF: 720P</td>
					</tr>
					<tr>
						<th scope="row">CLEAR VOICE II</th>
						<td>3 MODES Cinema, Game, Off</td>
					</tr>
					<tr>
						<th scope="row">SOUND OPTIMIZE</th>
						<td>YES</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="tech_spec_wrap">
			<table>
				<caption>Connectivity</caption>
				<tbody>
					<tr>
						<th scope="row">WI-FI&reg; BUILT-IN</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">WI-FI DIRECT</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">WINDOWS 8 CERTIFIED</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">DLNA CERTIFIED</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">INTEL&reg; WIRELESS DISPLAY (WIDI)</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">MHL&trade; (MOBILE HIGH-DEFINITION LINK)</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">NFC (NEAR FIELD COMMUNICATIONS)</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">SIMPLINK™ (HDMI™ CEC)</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">USB PLAYBACK</th>
						<td>DivX HD&reg;, JPEG, JPG, MPO, AC3 (Dolby&reg; Digital), EAC3, HAAC, AAC, MPEG, MP3, PCM, DTS®</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="tech_spec_wrap">
			<table>
				<caption>AV Inputs/Outputs</caption>
				<tbody>
					<tr>
						<th scope="row">RF IN (ANTENNA/CABLE)</th>
						<td>1 (REAR)</td>
					</tr>
					<tr>
						<th scope="row">AV IN</th>
						<td>1 (REAR)</td>
					</tr>
					<tr>
						<th scope="row">COMPONENT VIDEO IN(Y, PB, PR + AUDIO)</th>
						<td>1 (REAR)</td>
					</tr>
					<tr>
						<th scope="row">HDMI™/HDCP IN</th>
						<td>4 (SIDE)</td>
					</tr>
					<tr>
						<th scope="row">USB 3.0/2.0 IN</th>
						<td>3 (SIDE)</td>
					</tr>
					<tr>
						<th scope="row">DIGITAL AUDIO OUT (OPTICAL)</th>
						<td>1 (REAR)</td>
					</tr>
					<tr>
						<th scope="row">HEADPHONE OUT</th>
						<td>1 (SIDE)</td>
					</tr>
					<tr>
						<th scope="row">RS-232C (CONTROL/SERVICE)</th>
						<td>1 USB TO  RS232C (REAR)</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="tech_spec_wrap last">
			<table>
				<caption>Power</caption>
				<tbody>
					<tr>
						<th scope="row">ENERGY STAR&reg; QUALIFIED</th>
						<td>YES</td>
					</tr>
					<tr>
						<th scope="row">POWER SUPPLY (VOLTAGE, Hz)</th>
						<td>100V ~ 240V, 50/60 Hz</td>
					</tr>
					<tr>
						<th scope="row">POWER CONSUMPTION</th>
						<td>Under 85W, Max 291W</td>
					</tr>
					<tr>
						<th scope="row">STANDBY MODE</th>
						<td>0.3W</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>