<section class="where-to-buy">
	<div class="container">
		<div class="row title-wrap">
			<h1 class="title">Where to Buy</h1><!-- 2015-08-03 change teg name -->
		</div>
		<div class="row type-product product-area">
			<div class="copy-area">
				<p class="model-num"><a href="#">LG H950</a></p>
				<p class="buynow-btn"><a href="javascript:void(0)" class="btn buynow" data-sku="3429088" data-partner-id="LG" value="buy now" title="Open New Window" data-sc-item="buy-now" data-sc-value="{모델코드}">Buy Now</a><!-- Add to Cart Btn <a href="https://usstore.lg.com/store?Action=buy&Env=BASE&Locale=en_US&SiteID=lgus&productID=306352300&quantity=1" class="btn" title="Open New Window" data-sc-item="add-to-cart" data-sc-value="{모델코드}">Add To Cart</a> --></p>
			</div>
		</div>
		<div class="row where-to-buy-info-wrap">
			<div class="tab-buttons">
				<ul>
					<li>
						<a href="#"><span>Store Near You</span></a>
					</li>
					<li>
						<a href="#"><span>Authorized Online Retailer Site</span></a>
					</li>
				</ul>
			</div>
			<div class="where-to-buy-info" id="whereToBuyArea">
				<script type="text/javascript" src="//embedded.pricespider.com/WidgetScript.psjs?wc=634ff9ef-4b08-46f4-9f17-aab1f055a05a"></script>
				<script type="text/javascript">
					//var modelId = getQueryVariable('modelId'),
					var modelId = 'D850 Silk White', /* Model Name으로 넣어 주세요. */
						area = document.getElementById("whereToBuyArea");
					ps_Show({
						widgetConfigurationId: '634ff9ef-4b08-46f4-9f17-aab1f055a05a',
						container: area,
						sku: 'US_'+ modelId
					});
					/*
					function getQueryVariable(variable) {
						var query = window.location.search.substring(1);
						var vars = query.split("&");
						for (var i=0;i<vars.length;i++) {
							var pair = vars[i].split("=");
							if(pair[0] == variable){return pair[1];}
						}
						return(false);
					}*/
				</script>
			</div>
		</div>
		<!-- 2015-08-12 삭제 <div class="back-to-top"><a href="#top">BACK TO TOP</a></div> -->
	</div>
</section>
