<section class="where-to-buy">
	<div class="container">
		<div class="row title-wrap">
			<h1 class="title">Where to Buy</h1><!-- 2015-08-03 change teg name -->
		</div>
		<div class="row type-product product-area">
			<div class="product-image">
				<img class="lazy" src="/lg4-common/img/placeholder.gif" data-original="/img_sample/open_template_2c.jpg" alt="" />
			</div>
			<div class="copy-area">
				<p class="model-name"><a href="#">65" Class (64.5" Diagonal) UHD 4K Smart 3D Curved OLED TV w/ webOS™  </a></p>
				<p class="model-num"><a href="#">LG H950</a></p>
				<ul class="model-spec-list">
					<li>LG Smart TV</li>
					<li>LG Cinema 3D</li>
					<li>Cinema Screen</li>
					<li>2.1 Speaker</li>
					<li>Energy Star® Qualified</li>
				</ul>
				<div class="sizes">
					<p class="title">AVAILABLE SIZES:</p>
					<ul class="list-sizes">
						<li class="active"><a href="#">55&rdquo;</a></li>
						<li><a href="#">60&rdquo;</a></li>
						<li><a href="#">65&rdquo;</a></li>
					</ul>
				</div>
				<div class="colors">
					<p class="title">AVAILABLE COLORS:</p>
					<ul class="list_colors">
						<li itemprop="color" class="active"><a href="#"><span class="color_chip_cover"></span><span class="swatch large stainless-steel"></span>Real Stainless Steel</a></li>
						<li itemprop="color" ><a href="#"><span class="swatch large smooth-black"></span>Smooth Black</a></li>
						<li itemprop="color" ><a href="#"><span class="swatch large smooth-white"></span>Smooth White</a></li>
					</ul>
				</div>
				<div class="details">
					<div class="cta cta-button">
						<a href="javascript:void(0)" class="button small buynow" data-sku="3429088" data-partner-id="LG" value="buy now" title="Open New Window" data-sc-item="buy-now" data-sc-value="{모델코드}">Buy Now</a>
						<!-- Add to Cart Btn
						<a href="https://usstore.lg.com/store?Action=buy&Env=BASE&Locale=en_US&SiteID=lgus&productID=306352300&quantity=1" class="button small" title="Open New Window" data-sc-item="add-to-cart" data-sc-value="{모델코드}">Add To Cart</a>
						-->
					</div>
					<div class="rating" data-modelid="MD00001294"><!-- 2015-08-11 -->
						<div class="points_wrap">
							<div class="review_bg" style="width:50%;"><div class="review_point"><i class="icon icon-stars points"></i></div><i class="icon icon-stars"></i></div>
						</div>
						<span><a href="product_d.html">(14 Reviews)</a></span>
						
						<!-- 별점 없을 경우 2015-06-16
						<a href="/product_d.html#reviews"><span class="no-review">Be the first to review</span></a>
						-->
					</div>
				</div>

			</div>
		</div>
		<div class="row where-to-buy-info-wrap">
			<div class="where-to-buy-info" id="whereToBuyArea">
				<script type="text/javascript" src="//embedded.pricespider.com/WidgetScript.psjs?wc=634ff9ef-4b08-46f4-9f17-aab1f055a05a"></script>
				<script type="text/javascript">
					//var modelId = getQueryVariable('modelId'),
					var modelId = '42LN5400', /* Model Name으로 넣어 주세요. */
						area = document.getElementById("whereToBuyArea");
					ps_Show({
						widgetConfigurationId: '634ff9ef-4b08-46f4-9f17-aab1f055a05a',
						container: area,
						sku: 'US_'+ modelId
					});
					/*
					function getQueryVariable(variable) {
						var query = window.location.search.substring(1);
						var vars = query.split("&");
						for (var i=0;i<vars.length;i++) {
							var pair = vars[i].split("=");
							if(pair[0] == variable){return pair[1];}
						}
						return(false);
					}*/
				</script>
			</div>
		</div>
	</div>
</section>