<nav id="nav-appliances" class="meganav-menu" data-index='2'>
	<!-- 2015-06-04 Skip Navigation, Category Main 버튼 추가 -->
	<div class="skip-button">
		<a href="#"><span>Skip to Next Menu</span></a>
	</div>
	<div class="container category-nav">
		<a href="#" class="heading" data-sc-item="super-category-link"><!-- 2015-07-07 DTM -->Appliances<i class="icon icon-arrow-next"></i></a>
	</div>
	<div class="container five-column">
		<section>
			<div class="nav-group group-header">
				<a href="#" class="heading" data-sc-item="group-category-link"><!-- 2015-07-07 DTM -->KITCHEN<i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Refridgerators<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->French Doors</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Door-in-Door</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Counter Depth</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Side by Side</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Bottom Freezer</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Top Freezer</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->All LG Refridgerators</a></li>
				</ul>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Ranges and Ovens<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Oven Ranges</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Wall Ovens</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Cooktops</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Microwave Ovens</a></li>
				</ul>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Dishwashers<i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Kitchen Accessories<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Refrigerator Filters</a></li>
				</ul>
			</div>
		</section>
		<section>
			<div class="nav-group group-header">
				<a href="#" class="heading" data-sc-item="group-category-link"><!-- 2015-07-07 DTM -->LAUNDRY<i class="icon icon-arrow-next"></i></a>
			</div>
			
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Washers<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->TurboWash Washers</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Front Load Washers </a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Top Load Washers</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Dryers</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Washer/Dryer Combos</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->All LG Washers</a></li>
				</ul>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Dryers<i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Washer/Dryer Combos<i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Laundry Accessories<i class="icon icon-arrow-next"></i></a>
			</div>
		</section>
		<section>
			<div class="nav-group group-header">
				<a href="#" class="heading" data-sc-item="group-category-link"><!-- 2015-07-07 DTM -->REST OF HOME<i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Air Conditioners<i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Dehumidifiers <i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Vaccums<i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->LED Lights <i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Rest of Home Accessories<i class="icon icon-arrow-next"></i></a>
			</div>
		</section>
		<section>
			
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->More About Home Appliances<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Find the Right Refridgerator</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Find the Right Washer</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Experience Smart Thinq</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Experience LG Studio</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Auxiliary link #5</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Auxiliary link #6</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Promotion Support</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Promotions</a></li>
				</ul>

			</div>
		</section>
		<section class="last"><!-- add last class 2015-04-27 -->
			<ul class="innovation"><!-- 2015-06-22 -->
				<li><a href="#" data-sc-item="gnb-promotion-area"><!-- 2015-07-07 DTM --><img src="/lg4-common/img/global/mega-menus/washer.png" alt="Washer/Dryer Combos" /></a></li>
				<li>See Our Latest Project Innovation</li>
				<li><a href="#" data-sc-item="gnb-promotion-area"><!-- 2015-07-07 DTM -->See all of our Washer/Dryer Combos</a></li>
			</ul>
		</section>
	</div>
	<!-- 2015-10-29 close-button 추가 -->
	<div class="close-button">
		<a href="#">
			<span>Close</span><i class="icon icon-close"></i>
		</a>
	</div>
</nav>
