<nav id="nav-mobile" class="meganav-menu" data-index='0'>
	<!-- 2015-06-04 Skip Navigation, Category Main 버튼 추가 -->
	<div class="skip-button">
		<a href="#"><span>Skip to Next Menu</span></a>
	</div>
	<div class="container category-nav">
		<a href="#" class="heading" data-sc-item="super-category-link"><!-- 2015-07-07 DTM -->Mobile<i class="icon icon-arrow-next"></i></a>
	</div>
	<div class="container four-column">
		<section>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Cell Phones<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->LG G Series Phones</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->LG G Flex Series Phones</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->LG Optimus Phones</a></li>
				</ul>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->AT&T Phones</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Sprint Phones</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->T-Mobile Phones</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Verizon Phones</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->All LG Phones</a></li>
				</ul>
			</div>
		</section>
		<section>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->LG G Pad Tablets<i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Wearable Technology<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->LG G Watch Smart Watches</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Fitness & Activity Trackers</a></li>
				</ul>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Headsets<i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Cell Phone Accessories<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Charges</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Docks</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Mounts</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Cases & Covers</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->All LG Cell Phone Accessories</a></li>
				</ul>
			</div>
		</section>
		<section>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->More About Mobile<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Find the Right Cell Phone</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Reviews and Awards</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->LG Gate: Guarded Access to Enterprise</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Auxiliary link #4</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Auxiliary link #5</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Auxiliary link #6</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Promotion Support</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Promotions</a></li>
				</ul>
			</div>
		</section>
		<section class="last"><!-- add last class 2015-04-27 -->
			<ul class="innovation"><!-- 2015-06-22 -->
				<li><a href="#" data-sc-item="gnb-promotion-area"><!-- 2015-07-07 DTM --><img src="/lg4-common/img/global/mega-menus/phone.png" alt="G Flex 2" /></a></li>
				<li>Discover Our Latest Project Innovation</li>
				<li><a href="#" data-sc-item="gnb-promotion-area"><!-- 2015-07-07 DTM -->See the All New G Flex 2</a></li>
			</ul>
		</section>
	</div>
	<!-- 2015-10-29 close-button 추가 -->
	<div class="close-button">
		<a href="#">
			<span>Close</span><i class="icon icon-close"></i>
		</a>
	</div>
</nav>
