<nav id="nav-tv" class="meganav-menu" data-index='1'>
	<!-- 2015-06-04 Skip Navigation, Category Main 버튼 추가 -->
	<div class="skip-button">
		<a href="#nav-appliances" data-skiplink-index="0"><span>Skip to Next Menu</span></a>
	</div>
	<div class="container category-nav">
		<a href="#" class="heading" data-sc-item="super-category-link"><!-- 2015-07-07 DTM -->TV/Audio/Video<i class="icon icon-arrow-next"></i></a>
	</div>
	<div class="container four-column">
		<section>
			<div class="nav-group group-header">
				<a href="#" class="heading" data-sc-item="group-category-link"><!-- 2015-07-07 DTM -->HOME ENTERTAINMENT<i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->TVs<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->LED TVs</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Ultra HD 4K TVs</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->OLED TVs</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Plasma TVs</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->All LG TVs</a></li>
				</ul>
			</div>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->TV Accessories<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->All TV Accessories</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->3D Glasses</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Wall Mounts</a></li>
				</ul>
			</div>
		</section>
		<section>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Audio / Video<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Blu-ray Players</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Home Theater Systems</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Sound Bars</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Sound Plates&#8482;</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Docking Stations</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Projectors</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->All LG Home Audio/Video</a></li>
				</ul>
			</div>
		</section>
		<section>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->More About TV/Audio/Video<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Find the Right TV</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Reviews and Awards</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->What is OLED?</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->What is Ultra HD 4K</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Auxiliary link #5</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Auxiliary link #6</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Promotion Support</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Promotions</a></li>
				</ul>
			</div>
		</section>
		<section class="last"><!-- add last class 2015-04-27 -->
			<ul class="innovation"><!-- 2015-06-22 -->
				<li><a href="#" data-sc-item="gnb-promotion-area"><!-- 2015-07-07 DTM --><img src="/lg4-common/img/global/mega-menus/tv.png" alt="Discover OLED" /></a></li>
				<li>See Our Latest TV Innovation</li>
				<li><a href="#" data-sc-item="gnb-promotion-area"><!-- 2015-07-07 DTM -->Discover OLED</a></li>
			</ul>
		</section>
	</div>
	<!-- 2015-10-29 close-button 추가 -->
	<div class="close-button">
		<a href="#">
			<span>Close</span><i class="icon icon-close"></i>
		</a>
	</div>
</nav>
