<nav id="nav-innovation" class="meganav-menu" data-index="4">
	<!-- 2015-06-04 Skip Navigation, Category Main 버튼 추가 -->
	<div class="skip-button">
		<a href="#"><span>Skip to Next Menu</span></a>
	</div>
	<div class="container category-nav">
		<a href="#" class="heading">Innovation<i class="icon icon-arrow-next"></i></a>
	</div>
	<div class="container four-column">
		<section>
			<div class="nav-group">
				<a href="#" class="heading">Making Life Better<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#">In the Kitchen</a></li>
					<li><a href="#">In the Laundry Room</a></li>
					<li><a href="#">Family Entertainment</a></li>
					<li><a href="#">Mobile Lifestyle</a></li>
					<li><a href="#">Computing</a></li>
				</ul>
			</div>
		</section>
		<section>
			<div class="nav-group">
				<a href="#" class="heading">Technologies<i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading">The LG Labs<i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading">Awards<i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading">Patents<i class="icon icon-arrow-next"></i></a>
			</div>
			<div class="nav-group">
				<a href="#" class="heading">What's Next<i class="icon icon-arrow-next"></i></a>
			</div>
		</section>
		<section>
			<div class="nav-group">
				<a href="#" class="heading">Experience LG Innovation<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#">Events</a></li>
					<li><a href="#">Showrooms</a></li>
					<li><a href="#">Press/Media</a></li>
				</ul>
			</div>
		</section>
		<section class="last"><!-- add last class 2015-04-27 -->
			<ul class="innovation"><!-- 2015-06-22 -->
				<li><a href="#"><img src="/lg4-common/img/global/mega-menus/innovation.png" alt="2015 International CES, The Global Stage for Innovation." /></a></li>
				<li><a href="#">Don't Miss Us at the 2015 CES</a></li>
			</ul>
		</section>
	</div>
	<!-- 2015-10-29 close-button 추가 -->
	<div class="close-button">
		<a href="#">
			<span>Close</span><i class="icon icon-close"></i>
		</a>
	</div>
</nav>
