<nav id="nav-computer" class="meganav-menu" data-index='3'>
	<!-- 2015-06-04 Skip Navigation, Category Main 버튼 추가 -->
	<div class="skip-button">
		<a href="#"><span>Skip to Next Menu</span></a>
	</div>
	<div class="container category-nav">
		<a href="#" class="heading" data-sc-item="super-category-link"><!-- 2015-07-07 DTM -->Computer<i class="icon icon-arrow-next"></i></a>
	</div>
	<div class="container four-column">
		<section>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Monitors<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->21:9 UltraWide Monitors</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Gaming Monitors</a></li>
				</ul>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->ISP Monitors</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->LED Monitors</a></li>
				</ul>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->All-in-One Chromebase</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->All LG Monitors</a></li>
				</ul>
			</div>
		</section>
		<section>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->Data Storage<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Blu-ray Burners and Drives</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->DVD Burners and Drives</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->All LG Data Storage</a></li>
				</ul>
			</div>
		</section>
		<section>
			<div class="nav-group">
				<a href="#" class="heading" data-sc-item="category-mega-link"><!-- 2015-07-07 DTM -->More About Computer Products<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Find the Right Monitor</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->What is ISP Monitors?</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Auxiliary link #4</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Auxiliary link #5</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Auxiliary link #6</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Promotion Support</a></li>
					<li><a href="#" data-sc-item="sub-category-link"><!-- 2015-07-07 DTM -->Promotions</a></li>
				</ul>
			</div>
		</section>
		<section class="last"><!-- add last class 2015-04-27 -->
			<ul class="innovation"><!-- 2015-06-22 -->
				<li><a href="#" data-sc-item="gnb-promotion-area"><!-- 2015-07-07 DTM --><img src="/lg4-common/img/global/mega-menus/computer.png" alt="LG Computers" /></a></li>
				<li>See Our Latest Project Innovation</li>
				<li><a href="#" data-sc-item="gnb-promotion-area"><!-- 2015-07-07 DTM -->Discover LG Computers</a></li>
			</ul>
		</section>
	</div>
	<!-- 2015-10-29 close-button 추가 -->
	<div class="close-button">
		<a href="#">
			<span>Close</span><i class="icon icon-close"></i>
		</a>
	</div>
</nav>
