<nav id="nav-support" class="meganav-menu" data-index='5'>
	<!-- 2015-06-04 Skip Navigation, Category Main 버튼 추가 -->
	<div class="skip-button">
		<a href="#"><span>Skip to Next Menu</span></a>
	</div>
	<div class="container category-nav">
		<a href="/support/support.html" class="heading">Support<i class="icon icon-arrow-next"></i></a>
	</div>
	<div class="container four-column">
		<section>
			<div class="nav-group"> <a href="/support/support-search.html"
				class="heading">Product Help<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li> <a href="/support/how-to-and-tips.html">Help Library</a>
					</li>
					<li> <a href="/support/video-and-tutorials.html">Video Tutorials</a>
					</li>
					<li> <a href="/support/manuals-and-documents-list.html">Manuals &amp; Documents</a>
					</li>
					<li> <a href="/support/software-and-firmware.html">Software &amp; Firmware</a>
					</li>
				</ul>
			</div>
			<div class="nav-group"> <a href="/support/register-a-products.html"
				class="heading">Register a Products<i class="icon icon-arrow-next"></i></a>
			</div>
		</section>
		<section>
			<div class="nav-group"> <a href="/support/chat-and-email-information.html"
				class="heading">Contact us<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li> <a href="/support/chat-and-email-information.html">Chat &amp; Email</a>
					</li>
					<li> <a href="/support/telephone-information.html">Telephone</a>
					</li>
				</ul>
			</div>
			<div class="nav-group"> <a href="/support/schedule-a-repair.html"
				class="heading">Repair<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li> <a href="/support/schedule-a-repair.html">Request a Repair</a>
					</li>
					<li> <a href="/support/track-repair-service.html">Track Repair</a>
					</li>
					<li> <a href="/support/repair-service-center.html">Locate Repair Center</a>
					</li>
				</ul>
			</div>
		</section>
		<section>
			<div class="nav-group"> <a href="/support/parts-and-accessories.html"
				class="heading">Additional Support<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li> <a href="/support/parts-and-accessories.html">Parts &amp; Accessories</a>
					</li>
					<li> <a href="/support/document-attachment.html">Document Upload</a>
					</li>
				</ul>
			</div>
			<div class="nav-group"> <a href="/support/my-account.html"
				class="heading">My Account<i class="icon icon-arrow-next"></i></a>
				<ul>
					<li> <a href="/support/view-my-profile.html">My Profile</a>
					</li>
					<li> <a href="/support/my-products.html">My Products</a>
					</li>
					<li> <a href="/support/my-review.html">My Review</a>
					</li>
					<li> <a href="/support/my-order-history.html">My Order History</a>
					</li>
					<li> <a href="/support/faqs.html">FAQs</a>
					</li>
					<li> <a href="/support/news-promotions.html">News &amp; Promotions</a>
					</li>
				</ul>
			</div>
		</section>
		<section class="last">
			<ul class="innovation">
				<li>
					<a href="https://lg.yourserviceplan.com/presentationlayer/RealTimeQuoteLG.aspx"
					target="_blank">
						<img src="/us/images/support/main/support-main-banner.png"
						alt="">
					</a>
				</li>
				<li> <span>Protect your investment</span>
				</li>
				<li><a href="https://lg.yourserviceplan.com/presentationlayer/RealTimeQuoteLG.aspx"
					target="_blank">LG Premium Care</a>
				</li>
			</ul>
		</section>
	</div>
	<!-- 2015-10-29 close-button 추가 -->
	<div class="close-button">
		<a href="#">
			<span>Close</span><i class="icon icon-close"></i>
		</a>
	</div>
</nav>
