	<!-- edit 2015-08-19 -->
	<div class="move-top"><a href="#" title="Go to Top"><i class="icon icon-pagenav-up"></i></a></div>
	<div id="page-dimmed" class="page-dimmed"><span>&nbsp;</span></div>

	<!-- build:remove -->
	<!--#include virtual="/incl/require.inc" -->
	<!-- /build -->
	<script src="/lg4-common/js/global/global.main.js"></script>
	<script src="/lg4-common/js/products/products.main.js"></script>
	<!--
		theJ 빌드 후 스크립트 test 
		- requirejs.inc 삭제
		- /lg4-common/을 /dist/lg4-common/ 로 변경 후 확인.
	-->

