<!-- Mbox : 페이지마다 다르게 들어갑니다. -->
	<!-- 다음 2개 JS는 모든 페이지에 적용 해 주세요. -->
	<script type="text/javascript" src="/us/general/tracking/mbox.js"></script>
	<script type="text/javascript">mboxCreate('US_LG_Mbox','path='+location.pathname);</script>

	<!-- 다음 2개 script는 Product page에만 적용해 주세요.  -->
	<script type='text/javascript'>mboxCreate('US_LG_Product_Pages_All','path='+location.pathname);</script>
	<script type='text/javascript'>mboxCreate('US_LG_Product_Pages_MU','path='+location.pathname);</script>
	<!--
		단, 위 US_LG_Product_Pages_MU 에서 MU의 경우, 아래와 같이 Super Category 별로 다르게 넣어 주세요. 
		MU : Mobile 
		HE : TV/AUDIO/VIDEO, Computer Products
		HA : Appliances
	-->

	<!-- 다음 2개 script는 Where to buy 페이지에만 적용해 주세요. -->
	<script type="text/javascript">mboxCreate('US_LG_WTB_All','path='+location.pathname);</script>
	<script type="text/javascript">mboxCreate('US_LG_WTB_MU','path='+location.pathname);</script>
	<!--
		단, 위 US_LG_Product_Pages_MU 에서 MU의 경우, 아래와 같이 Super Category 별로 다르게 넣어 주세요. 
		MU : Mobile 
		HE : TV/AUDIO/VIDEO, Computer Products
		HA : Appliances
	-->