<footer id="appFooter" class="AppFooter">
	<section class="top-bar">
		<div class="container">
			<div class="social-links">
				<span>Connect:</span>
				<ul>
					<li>
						<a target="_blank" href="http://www.facebook.com/lgusa" data-sc-item="social-sharing" data-sc-value="facebook"><!-- 2015-07-07 DTM --><img src="/lg4-common/img/global/footer/sns_facebook.png" alt="Facebook" /></a>
					</li>
					<li>
						<a target="_blank" href="http://www.twitter.com/lgus" data-sc-item="social-sharing" data-sc-value="twitter"><!-- 2015-07-07 DTM --><img src="/lg4-common/img/global/footer/sns_twitter.png" alt="Twitter" /></a>
					</li>
					<li>
						<a target="_blank" href="https://plus.google.com/105526923857641800075/" data-sc-item="social-sharing" data-sc-value="google plus"><!-- 2015-07-07 DTM --><img src="/lg4-common/img/global/footer/sns_google.png" alt="Google Plus" /></a>
					</li>
					<li>
						<a target="_blank" href="https://www.pinterest.com/lgusa/" data-sc-item="social-sharing" data-sc-value="pinterest"><!-- 2015-07-07 DTM --><img src="/lg4-common/img/global/footer/sns_pinterest.png" alt="Pinterest" /></a>
					</li>
					<li>
						<a target="_blank" href="http://www.youtube.com/experiencelg" data-sc-item="social-sharing" data-sc-value="youtube"><!-- 2015-07-07 DTM --><img src="/lg4-common/img/global/footer/sns_youtube.png" alt="Youtube" /></a>
					</li>
				</ul>
			</div>
			<div class="country-select">Select Country/Language: <a href="#" data-sc-item="local-info" data-sc-value="{country}:{language}"><!-- 2015-07-07 DTM -->U.S. / English</a><i class="icon icon-arrow-next-bold"></i></div>
			<!-- XXXXX <div class="cookie-settings"><a href="#">Change Your Cookie Settings <i class="icon icon-close"></i></a></div> -->
		</div>
	</section>
	<section class="footer-content">
		<div class="container mobile">
			<section>
				<div class="expand-footer-wrap">
					<span>
						<a href="#" class="heading">Mobile</a>
					</span>
					<span class="expand-button">
						<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a><!-- 2015-08-27 -->
					</span>
					<ul class="depth2">
						<li>
							<span><a href="#">Cell Phones </a></span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span><a href="#">LG G Series Phones</a></span>
								</li>
								<li>
									<span><a href="#">LG G Flex Series Phones</a></span>
								</li>
								<li>
									<span><a href="#">LG Optumus Phones</a></span>
								</li>
								<li>
									<span><a href="#">AT&amp;T Phones</a></span>
								</li>
								<li>
									<span><a href="#">Sprint Phones</a></span>
								</li>
								<li>
									<span><a href="#">T-Mobile Phones</a></span>
								</li>
								<li>
									<span><a href="#">Verizon Phones</a></span>
								</li>
								<li>
									<span><a href="#">All LG Phones</a></span>
								</li>
							</ul>

						</li>
						<li>
							<span><a href="#">LG G Pad Tablets</a></span>
						</li>
						<li>
							<span><a href="#">Wearable Technology</a></span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span><a href="#">LG G Watch Smart Watches</a></span>
								</li>
								<li>
									<span><a href="#">Fitness &amp; Activity Trackers</a></span>
								</li>
							</ul>
						</li>
						<li>
							<span><a href="#">Headsets</a></span>
						</li>
						<li>
							<span><a href="#">Cell Phone Accessories</a></span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span><a href="#">Charges</a></span>
								</li>
								<li>
									<span><a href="#">Docks</a></span>
								</li>
								<li>
									<span><a href="#">Mounts</a></span>
								</li>
								<li>
									<span><a href="#">Cases &amp; Covers</a></span>
								</li>
								<li>
									<span><a href="#">All LG Cell Phone Accessories</a></span>
								</li>
							</ul>
						</li>
						<li>
							<span><a href="#">More About Mobile</a></span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span><a href="#">Find the Right Cell Phone</a></span>
								</li>
								<li>
									<span><a href="#">Reviews and Awards</a></span>
								</li>
								<li>
									<span><a href="#">LG Gate: Guarded Access to Enterprise</a></span>
								</li>
								<li>
									<span><a href="#">Auxiliary link #4</a></span>
								</li>
								<li>
									<span><a href="#">Auxiliary link #5</a></span>
								</li>
								<li>
									<span><a href="#">Auxiliary link #6</a></span>
								</li>
								<li>
									<span><a href="#">Promotion Support</a></span>
								</li>
								<li>
									<span><a href="#">Promotions</a></span>
								</li>
							</ul>
						</li>
					</ul>
				</div>
				<div class="expand-footer-wrap">
					<span>
						<span class="heading">TV/Audio/Video</span>
					</span>
					<span class="expand-button">
						<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
					</span>
					<ul class="depth2">
						<li>
							<span>
								<span>HOME ENTERTAINMENT </span>
							</span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span>
										<span>TVs</span>
									</span>
									<span class="expand-button">
										<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
									</span>
									<ul class="depth4">
										<li>
											<span>LED TVs</span>
										</li>
										<li>
											<span>Ultra HD 4K TVs</span>
										</li>
										<li>
											<span>OLED TVs</span>
										</li>
										<li>
											<span>Plasma TVs</span>
										</li>
										<li>
											<span>All LG TVs</span>
										</li>
									</ul>
								</li>
								<li>
									<span>
										<span>TV Accessories</span>
									</span>
									<span class="expand-button">
										<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
									</span>
									<ul class="depth4">
										<li>
											<span>All TV Accessories</span>
										</li>
										<li>
											<span>3D Glasses</span>
										</li>
										<li>
											<span>Wall Mounts</span>
										</li>
									</ul>
								</li>
							</ul>
						</li>
						<li>
							<span>
								<span>Audio / Video</span>
							</span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span>
										<span>Blu-ray Players</span>
									</span>
								</li>
								<li>
									<span>
										<span>Home Theater Systems</span>
									</span>
								</li>
								<li>
									<span>
										<span>Sound Bars</span>
									</span>
								</li>
								<li>
									<span>
										<span>Sound Plates&#8482;</span>
									</span>
								</li>
								<li>
									<span>
										<span>Docking Stations</span>
									</span>
								</li>
								<li>
									<span>
										<span>Projectors</span>
									</span>
								</li>
								<li>
									<span>
										<span>All LG Home Audio/Video</span>
									</span>
								</li>
							</ul>
						</li>

						<li>
							<span>
								<span>More About TV/Audio/Video</span>
							</span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span>
										<span>Find the Right TV</span>
									</span>
								</li>
								<li>
									<span>
										<span>Reviews and Awards</span>
									</span>
								</li>
								<li>
									<span>
										<span>What is OLED?</span>
									</span>
								</li>
								<li>
									<span>
										<span>What is Ultra HD 4K</span>
									</span>
								</li>
								<li>
									<span>
										<span>Auxiliary link #5</span>
									</span>
								</li>
								<li>
									<span>
										<span>Auxiliary link #6</span>
									</span>
								</li>
								<li>
									<span>
										<span>Promotion Support</span>
									</span>
								</li>
								<li>
									<span>
										<span>Promotions</span>
									</span>
								</li>
							</ul>
						</li>
						
					</ul>
				</div>
				<div class="expand-footer-wrap">
					<span><a href="#" class="heading">Appliances</a></span>
					<span class="expand-button">
						<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
					</span>
					<ul class="depth2">
						<li>
							<span><a href="#" class="heading">KITCHEN </a></span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span><a href="#">Refridgerators</a></span>
									<span class="expand-button">
										<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
									</span>
									<ul class="depth4">
										<li>
											<a href="#">French Doors</a>
										</li>	
										<li>
											<a href="#">Door-in-Door</a>
										</li>	
										<li>
											<a href="#">Counter Depth</a>
										</li>	
										<li>
											<a href="#">Side by Side</a>
										</li>	
										<li>
											<a href="#">Bottom Freezer</a>
										</li>	
										<li>
											<a href="#">Top Freezer</a>
										</li>	
										<li>
											<a href="#">All LG Refridgerators</a>
										</li>
									</ul>
								</li>	
								<li>
									<span><a href="#">Ranges and Ovens</a></span>
									<span class="expand-button">
										<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
									</span>
									<ul class="depth4">
										<li>
											<a href="#">Oven Ranges</a>
										</li>	
										<li>
											<a href="#">Wall Ovens</a>
										</li>	
										<li>
											<a href="#">Cooktops</a>
										</li>	
										<li>
											<a href="#">Microwave Ovens</a>
										</li>	

									</ul>
								</li>	
								<li>
									<span><a href="#">Dishwashers</a></span>
								</li>	
								<li>
									<span><a href="#">Kitchen Accessories</a></span>
									<span class="expand-button">
										<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
									</span>
									<ul class="depth4">
										<li>
											<a href="#">Refrigerator Filters</a>
										</li>	
									</ul>
								</li>	
							</ul>
						</li>
						<li>
							<span><a href="#">LAUNDRY</a></span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span><a href="#">Washers</a></span>
									<span class="expand-button">
										<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
									</span>
									<ul class="depth4">
										<li>
											<a href="#">TurboWash Washers</a>
										</li>	
										<li>
											<a href="#">Front Load Washers </a>
										</li>	
										<li>
											<a href="#">Top Load Washers</a>
										</li>	
										<li>
											<a href="#">Dryers</a>
										</li>	
										<li>
											<a href="#">Washer/Dryer Combos</a>
										</li>	
										<li>
											<a href="#">All LG Washers</a>
										</li>	
									</ul>
								</li>	
								<li>
									<span><a href="#">Dryers</a></span>
									
								</li>
								<li>
									<span><a href="#">Washer/Dryer Combos</a></span>
								</li>
								<li>
									<span><a href="#">Laundry Accessories</a></span>
									
								</li>
							</ul>
						</li>
						<li>
							<span><a href="#">REST OF HOME</a></span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span><a href="#">Air Conditioners</a></span>
								</li>	
								<li>
									<span><a href="#">Dehumidifiers</a></span>
								</li>
								<li>
									<span><a href="#">Vaccums</a></span>
								</li>
								<li>
									<span><a href="#">LED Lights</a></span>
								</li>
								<li>
									<span><a href="#">Rest of Home Accessories</a></span>
								</li>
							</ul>
						</li>
						<li>
							<span><a href="#">More About Home Appliances</a></span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span><a href="#">Find the Right Refridgerator</a></span>
								</li>	
								<li>
									<span><a href="#">Find the Right Washer</a></span>
								</li>
								<li>
									<span><a href="#">Experience Smart Thinq</a></span>
								</li>
								<li>
									<span><a href="#">Experience LG Studio</a></span>
								</li>
								<li>
									<span><a href="#">Auxiliary link #5</a></span>
								</li>
								<li>
									<span><a href="#">Auxiliary link #6</a></span>
								</li>
								<li>
									<span><a href="#">Promotion Support</a></span>
								</li>
								<li>
									<span><a href="#">Promotions</a></span>
								</li>
							</ul>
						</li>
					</ul>
				</div>
				<div class="expand-footer-wrap">
					<span><a href="#" class="heading">Computer</a></span>
					<span class="expand-button">
						<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
					</span>
					<ul class="depth2">
						<li>
							<span><a href="#">Monitors</a></span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span><a href="#">21:9 UltraWide Monitors</a></span>
								</li>	
								<li>
									<span><a href="#">Gaming Monitors</a></span>
								</li>
								<li>
									<span><a href="#">ISP Monitors</a></span>
								</li>
								<li>
									<span><a href="#">LED Monitors</a></span>
								</li>
								<li>
									<span><a href="#">All-in-One Chromebase</a></span>
								</li>
								<li>
									<span><a href="#">All LG Monitors</a></span>
								</li>
							</ul>
						</li>	
						<li>
							<span><a href="#">Data Storage</a></span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span><a href="#">Blu-ray Burners and Drives</a></span>
								</li>	
								<li>
									<span><a href="#">DVD Burners and Drives</a></span>
								</li>
								<li>
									<span><a href="#">All LG Data Storage</a></span>
								</li>
								
							</ul>
						</li>
						<li>
							<span><a href="#">More About Computer Products</a></span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span><a href="#">Find the Right Monitor</a></span>
								</li>	
								<li>
									<span><a href="#">What is ISP Monitors?</a></span>
								</li>
								<li>
									<span><a href="#">Auxiliary link #4</a></span>
								</li>
								<li>
									<span><a href="#">Auxiliary link #5</a></span>
								</li>	
								<li>
									<span><a href="#">Auxiliary link #6</a></span>
								</li>
								<li>
									<span><a href="#">Promotion Support</a></span>
								</li>
								<li>
									<span><a href="#">Promotions</a></span>
								</li>
							</ul>
						</li>
					</ul>
				</div>
				<div class="expand-footer-wrap">
					<span><a href="#" class="heading">Innovation</a></span>
					<span class="expand-button">
						<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
					</span>
					<ul class="depth2">
						<li>
							<span><a href="#">Making Life Better</a></span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span><a href="#">In the Kitchen</a></span>
								</li>	
								<li>
									<span><a href="#">In the Laundry Room</a></span>
								</li>
								<li>
									<span><a href="#">Family Entertainment</a></span>
								</li>
								<li>
									<span><a href="#">Mobile Lifestyle</a></span>
								</li>
								<li>
									<span><a href="#">Computing</a></span>
								</li>
							</ul>
						</li>	
						<li>
							<span><a href="#">Technologies</a></span>
						</li>
						<li>
							<span><a href="#">The LG Labs</a></span>
						</li>
						<li>
							<span><a href="#">Awards</a></span>
						</li>
						<li>
							<span><a href="#">Patents</a></span>
						</li>
						<li>
							<span><a href="#">What's Next</a></span>
						</li>
						<li>
							<span><a href="#">Experience LG Innovation</a></span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span><a href="#">Events</a></span>
								</li>	
								<li>
									<span><a href="#">Showrooms</a></span>
								</li>
								<li>
									<span><a href="#">Press/Media</a></span>
								</li>
							</ul>
						</li>
					</ul>
				</div>
				<div class="expand-footer-wrap">
					<span><a href="#" class="heading">Support</a></span>
					<span class="expand-button">
						<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
					</span>
					<ul class="depth2">
						<li>
							<span><a href="#">Register a Product</a></span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span><a href="#">Benefits</a></span>
								</li>	
							</ul>
						</li>	
						<li>
							<span><a href="#">Downloads & Manuals</a></span>
						</li>
						<li>
							<span><a href="#">Experience LG Innovation</a></span>
							<span class="expand-button">
								<a href="#"><i class="icon icon-menu-plus"><span class="alt-text">Open</span></i><i class="icon icon-menu-minus hide"><span class="alt-text">Close</span></i></a>
							</span>
							<ul class="depth3">
								<li>
									<span><a href="#">Events</a></span>
								</li>	
								<li>
									<span><a href="#">Showrooms</a></span>
								</li>
								<li>
									<span><a href="#">Press/Media</a></span>
								</li>
							</ul>
						</li>

					</ul>
				</div>
				<div class="expand-footer-wrap">
					<span><a href="#" class="heading">Business</a></span>
				</div>
			</section>
			<section class="banner-area">
				<a href="#"><img src="/lg4-common/img/global/footer/m_footer_banner1.jpg" alt="LG Jeong-Do Management Ethics Hotline" /></a>
			</section>
		</div>
	</section>
	<section class="bottom-bar">
		<div class="container">
			<ul>
				<li><a href="#">Site Map</a></li>
				<li><a href="#">Privacy</a></li>
				<li><a href="#">Legal</a></li>
				<li><a href="#">Patents</a></li>
				<!-- delete <li><a href="#" id="accHelp">Accessibility Help</a></li> -->
				<!-- delete <li class="mobile"><a href="tel:18002430000">Tap to Call</a></li> -->
			</ul>
			<div class="copyright"><span>Copyright &copy; 2015 LG Electronics.</span> <span>All Rights Reserved.</span></div>
		 </div>
	</section>
</footer>