<footer id="appFooter" class="AppFooter">
	<section class="top-bar">
		<div class="container">
			<div class="social-links">
				<span>Connect:</span>
				<ul>
					<!-- 2015-07-31 title="Open the new window" 추가 -->
					<li>
						<a target="_blank" title="Open the new window" href="http://www.facebook.com/lgusa" data-sc-item="social-sharing" data-sc-value="facebook"><!-- 2015-07-07 DTM --><img src="/lg4-common/img/global/footer/sns_facebook.png" alt="Facebook" /></a>
					</li>
					<li>
						<a target="_blank" title="Open the new window" href="http://www.twitter.com/lgus" data-sc-item="social-sharing" data-sc-value="twitter"><!-- 2015-07-07 DTM --><img src="/lg4-common/img/global/footer/sns_twitter.png" alt="Twitter" /></a>
					</li>
					<li>
						<a target="_blank" title="Open the new window" href="https://plus.google.com/105526923857641800075/" data-sc-item="social-sharing" data-sc-value="google plus"><!-- 2015-07-07 DTM --><img src="/lg4-common/img/global/footer/sns_google.png" alt="Google Plus" /></a>
					</li>
					<li>
						<a target="_blank" title="Open the new window" href="https://www.pinterest.com/lgusa/" data-sc-item="social-sharing" data-sc-value="pinterest"><!-- 2015-07-07 DTM --><img src="/lg4-common/img/global/footer/sns_pinterest.png" alt="Pinterest" /></a>
					</li>
					<li>
						<a target="_blank" title="Open the new window" href="http://www.youtube.com/experiencelg" data-sc-item="social-sharing" data-sc-value="youtube"><!-- 2015-07-07 DTM --><img src="/lg4-common/img/global/footer/sns_youtube.png" alt="Youtube" /></a>
					</li>
				</ul>
			</div>
			<div class="country-select">Select Country/Language: <a href="#" data-sc-item="local-info" data-sc-value="{country}:{language}"><!-- 2015-07-07 DTM -->U.S. / English</a><i class="icon icon-arrow-next-bold"></i></div>
			<!-- XXXXX <div class="cookie-settings"><a href="#">Change Your Cookie Settings <i class="icon icon-close"></i></a></div> -->
		</div>
	</section>
	<section class="footer-content">
		<div class="container five-column web">
			<section>
				<a href="#" class="heading">Cell Phones</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">LG G Series Phones</a></li>
						<li><a href="#">LG G Flex Series Phones</a></li>
						<li><a href="#">LG Optimus Phones</a></li>
						<li><a href="#">AT&T Phones</a></li>
						<li><a href="#">Sprint Phones</a></li>
						<li><a href="#">T-Mobile Phones</a></li>
						<li><a href="#">Verizon Phones</a></li>
						<li><a href="#">All LG Cell Phones</a></li>
					</ul>
				</nav>
				<a href="#" class="heading">LG G Pad Tablets</a>
				<a href="#" class="heading">Wearable Technology</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">LG G Watch Smart Watches</a></li>
						<li><a href="#">Fitness & Activity Trackers</a></li>
					</ul>
				</nav>
				<a href="#" class="heading">Headsets</a>
				<a href="#" class="heading">Cell Phone Accessories</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">Chargers</a></li>
						<li><a href="#">Docks</a></li>
						<li><a href="#">Mounts</a></li>
						<li><a href="#">Cases &amp; Covers</a></li>
						<li><a href="#">All LG Cell Phone Accessories</a></li>
					</ul>
				</nav>
			</section>
			<section>
				<a href="#" class="heading">TVs</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">LED TVs</a></li>
						<li><a href="#">Ultra HD 4K TVs</a></li>
						<li><a href="#">OLED TVs</a></li>
						<li><a href="#">Plasma TVs</a></li>
						<li><a href="#">Smart TVs</a></li>
						<!-- delete 2015-04-27
						<li><a href="#">22" - 29" TVs</a></li>
						<li><a href="#">32" - 39" TVs</a></li>
						<li><a href="#">40" - 42" TVs</a></li>
						<li><a href="#">47" - 55" TVs</a></li>
						<li><a href="#">60" - 65" TVs</a></li>
						<li><a href="#">65" and Larger TVs</a></li>
						-->
						<li><a href="#">All LG TVs</a></li>
					</ul>
				</nav>
				<a href="#" class="heading">Audio/Video</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">Blu-ray Players</a></li>
						<li><a href="#">Home Theater Systems</a></li>
						<li><a href="#">Sounds Bars</a></li>
						<li><a href="#">SoundPlates&trade;</a></li>
						<li><a href="#">Docking Stations</a></li>
						<li><a href="#">Projectors</a></li>
						<li><a href="#">All LG Home Audio/Video</a></li>
					</ul>
				</nav>
				<a href="#" class="heading">TV Accessories</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">3D Glasses</a></li>
						<li><a href="#">Wall Mounts</a></li>
						<li><a href="#">All LG TV Accessories</a></li>
					</ul>
				</nav>
			</section>
			<section>
				<a href="#" class="heading">Refrigerators</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">French Doors</a></li>
						<li><a href="#">Door-In-Door</a></li>
						<li><a href="#">Counter Depth</a></li>
						<li><a href="#">Side by Side</a></li>
						<li><a href="#">Bottom Freezer</a></li>
						<li><a href="#">Top Freezer</a></li>
						<li><a href="#">All LG Refrigerators</a></li>
					</ul>
				</nav>
				<a href="#" class="heading">Ranges &amp; Ovens</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">Oven Ranges</a></li>
						<li><a href="#">Wall Ovens</a></li>
						<li><a href="#">Cooktops</a></li>
						<li><a href="#">Microwave Ovens</a></li>
					</ul>
				</nav>
				<a href="#" class="heading">Dishwashers</a>
				<a href="#" class="heading">Laundry</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">Front Load Washers</a></li>
						<li><a href="#">Top Load Washers</a></li>
						<li><a href="#">TurboWash Washers</a></li>
						<li><a href="#">Dryers</a></li>
						<li><a href="#">Washer/Dryer Combos</a></li>
						<li><a href="#">All LG Washers</a></li>
					</ul>
				</nav>
				<a href="#" class="heading">Air Conditioners</a>
				<a href="#" class="heading">Dehumidifiers</a>
				<a href="#" class="heading">LED Lights</a>
				<a href="#" class="heading">Appliance Accessories</a>
			</section>
			<section>
				<a href="#" class="heading">Monitors</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">21:9 UltraWide Monitors</a></li>
						<li><a href="#">Gaming Monitors</a></li>
						<li><a href="#">IPS Monitors</a></li>
						<li><a href="#">LED Monitors</a></li>
						<li><a href="#">All-In-One Chromebase</a></li>
						<li><a href="#">All LG Monitors</a></li>
					</ul>
				</nav>
				<a href="#" class="heading">Data Storage</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">Blu-ray Burners and Drives</a></li>
						<li><a href="#">DVD Burners and Drives</a></li>
						<li><a href="#">All LG Data Storage</a></li>
					</ul>
				</nav>
				<a href="#" class="heading">LG Innovation - Making Life Better</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">In the Kitchen</a></li>
						<li><a href="#">In the Laundry Room</a></li>
						<li><a href="#">Family Entertainment</a></li>
						<li><a href="#">Mobile Lifestyle</a></li>
						<li><a href="#">Computing</a></li>
					</ul>
				</nav>
				<a href="#" class="heading">Technologies</a>
				<a href="#" class="heading">The LG Labs</a>
				<a href="#" class="heading">Awards</a>
				<a href="#" class="heading">What's Next</a>
				<a href="#" class="heading">Experience LG Innovation</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">Events</a></li>
						<li><a href="#">Showrooms</a></li>
						<li><a href="#">Press/Media</a></li>
					</ul>
				</nav>
			</section>
			<section>
				<a href="#" class="heading">Company Info</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">About LG</a></li>
						<li><a href="#">Careers</a></li>
						<li><a href="#">LG Corporate</a></li>
						<li><a href="#">Other LG Affiliates</a></li>
					</ul>
				</nav>
				<a href="#" class="heading">Support</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">Contact Us</a></li>
						<li><a href="#">Register A Product</a></li>
						<li><a href="#">Download & Manuals</a></li>
						<li><a href="#">Videos and Tutorials</a></li>
						<li><a href="#">Help Library</a></li>
						<li><a href="#">LG Recycling Program</a></li>
						<li><a href="#">Public Notices</a></li>
						<li><a href="#">LG Refrigerator Energy Offer</a></li>
						<li><a href="#">Glossary</a></li>
					</ul>
				</nav>
				<a href="#" class="heading">For Business</a>
				<nav class="footer-nav">
					<ul>
						<li><a href="#">Automotive</a></li>
						<li><a href="#">Commercial Display</a></li>
						<li><a href="#">Commercial AC (HVAC)</a></li>
						<li><a href="#">Solar</a></li>
						<li><a href="#">Lighting</a></li>
						<li><a href="#">Commercial Laundry</a></li>
						<li><a href="#">LG HomNet</a></li>
						<li><a href="#">LG Iris</a></li>
					</ul>
				</nav>
			</section>
			<section class="banner-area">
				<!-- 2015-07-31 target="_blank" title="Open the new window" 추가 -->
				<a href="#" target="_blank" title="Open the new window"><img src="/lg4-common/img/global/footer/d_footer_banner1.jpg" alt="LG Jeong-Do Management Ethics Hotline" /></a>
			</section>
		</div>
	</section>
	<section class="bottom-bar">
		<div class="container">
			<ul>
				<li><a href="#">Site Map</a></li>
				<li><a href="#">Privacy</a></li>
				<li><a href="#">Legal</a></li>
				<li><a href="#">Patents</a></li>
				<li><a href="#" id="accHelp">Accessibility Help</a></li><!-- 2015-10-15 theJ -->
			</ul>
			<div class="copyright"><span>Copyright &copy; 2015 LG Electronics.</span> <span>All Rights Reserved.</span></div>
		 </div>
	</section>
</footer>