<!--
	'cookie-check' class in body tag.
	이 팝업은 추후 결정에 따라 내용이 변경되거나, 추가 될 수 있습니다.
-->
<!--
<div class="cookie-notice">
	<div class="cookie-notice-wrap">
		En cliquant sur la croix, vous acceptez l'utilisation de cookies aux fins d'analyser le trafic du site web et de vous permettre de partager du contenu sur les réseaux sociaux.<br/>
		<a href="#">Pour en savoir plus et paramétrer les </a>
		<button class="cookie-notice-close"><i class="icon icon-close"></i></button>
	</div>
</div>
-->