<nav id="mobileFlyoutNav">
	<section class="mobile-flyout-header">
		<div class="hamburger">
			<a href="#"><i class="icon icon-close"></i><span class="alt-text">Close</span></a><!-- 2015-08-26 -->
		</div>
		<ul class="search-and-nav"><!-- 2015-05-18 Search Area 마크업 변경 -->
			<li class="search-menu">
				<form action="/search_result_products_m.html" method="post">
				<div class="search-box">
					<div class="search-box-heading">
						<input class="psearch-nav" data-alignment="right" data-url="/ajaxData/response/psearch-enhanced" id="search_nav" placeholder="Search LG" maxlength="128" name="search" size="15" title="SEARCH LG.COM" type="search" autocomplete="off" placeholder="Search LG">
					</div>
				</div>
				</form>
			</li>
			<li>
				<ul class="nav">
					<li><a href="#" class="sign-anchor"><i class="icon icon-login-mobile"></i><span class="alt-text">MyLG Account</span></a></li>
					<li>
						<div class="cart-wrap">
							<!-- 2015-06-17 cart count -->
							<a href="https://usstore.lg.com/store/lgus/en_US/cart/" id="eco-mini-basket" data-apiURL="//usstore.lg.com/store?Locale=en_US&SiteID=lgus">
								<span class="alt-text">Cart</span><!-- 2015-08-27 -->
								<i class="icon icon-shopping-cart-mobile"></i>
								<span class="cart-count"><span>0</span></span>
							</a>
						</div>
					</li>
				</ul>
			</li>
		</ul>
	</section>
	<div class="mobile-flyout-body-wrapper">
		<section class="mobile-nav-section">
			<a href="#" class="nav-section-link main-menu-link"><i class="icon icon-arrow-prev"></i>Main Menu</a>
		</section>
		<!--
			DTM Guide :
			- 클릭시 열리는 링크는 제외하고 실제 페이지로 이동되는 링크에만 아래와 같이 적용. 
			- Super Cate : data-sc-item="super-category-link"
			- Group Cate : data-sc-item="group-category-link"
			- Category   : data-sc-item="category-mega-link"
			- Sub Cate   : data-sc-item="sub-category-link"
		-->
		<section class="mobile-nav-section">
			<a href="#" class="nav-section-link"><i class="icon icon-arrow-prev"></i>Mobile<i class="icon icon-arrow-next"></i></a>
			<ul class="nav-sub-list">
				<li><a class="nav-sub-list-item" href="#">Cell Phones<i class="icon icon-arrow-next"></i></a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">LG G Series Phones</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">LG G Flex Series Phones</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">LG Optimus Phones</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">AT&T Phones</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Sprint Phones</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">T-Mobile Phones</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Verizon Phones</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">All LG Phones</a></li>
					</ul>
				</li>
				<li><a class="nav-sub-list-item" href="#">LG G Pad Tablets<i class="icon icon-arrow-next"></i></a></li>

				<li><a class="nav-sub-list-item" href="#">Wearable Technology<i class="icon icon-arrow-next"></i></a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">LG G Watch Smart Watches</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Fitness & Activity Trackers</a></li>
					</ul>
				</li>

				<li><a class="nav-sub-list-item" href="#">Headsets<i class="icon icon-arrow-next"></i></a></li>

				<li><a class="nav-sub-list-item" href="#">Cell Phone Accessories<i class="icon icon-arrow-next"></i></a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Charges</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Docks</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Mounts</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Cases & Covers</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">All LG Cell Phone Accessories</a></li>
					</ul>
				</li>
				<li><a class="nav-sub-list-item" href="#">More About Mobile<i class="icon icon-arrow-next"></i></a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Find the Right Cell Phone</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Reviews and Awards</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">LG Gate: Guarded Access to Enterprise</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Auxiliary link #4</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Auxiliary link #5</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Auxiliary link #6</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Promotion Support</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Promotions</a></li>
					</ul>
				</li>
			</ul>
		</section>
		<section class="mobile-nav-section">
			<a href="#" class="nav-section-link"><i class="icon icon-arrow-prev"></i>TV/Audio/Video<i class="icon icon-arrow-next"></i></a>
			<ul class="nav-sub-list">
				<li>
					<a class="nav-sub-list-item" href="#">HOME ENTERTAINMENT<i class="icon icon-arrow-next"></i></a>
					
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#">TVs<i class="icon icon-menu-plus"></i><i class="icon icon-menu-minus hide"></i></a>
							<ul class="nav-sub-accordion-ul">
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">LED TVs</a></li>
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">Ultra HD 4K TVs</a></li>
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">OLED TVs</a></li>
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">Plasma TVs</a></li>
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">All LG TVs</a></li>
							</ul>
						</li>
					</ul>
					
				</li>
				<li><a class="nav-sub-list-item" href="#">TV Accessories<i class="icon icon-arrow-next"></i></a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">All TV Accessories</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">3D Glasses</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Wall Mounts</a></li>
					</ul>
				</li>
				<li><a class="nav-sub-list-item" href="#">Audio/Video<i class="icon icon-arrow-next"></i></a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Blu-ray Players</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Home Theater Systems</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Sound Bars</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Sound Plates&#8482;</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Docking Stations</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Projectors</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">All LG Home Audio/Video</a></li>
					</ul>
				</li>
				<li><a class="nav-sub-list-item" href="#">More About TV/Audio/Video<i class="icon icon-arrow-next"></i></a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Find the Right TV</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Reviews and Awards</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">What is OLED?</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">What is Ultra HD 4K</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Auxiliary link #5</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Auxiliary link #6</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Promotion Support</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Promotions</a></li>
					</ul>
				</li>
			</ul>
		</section>
		<section class="mobile-nav-section">

			<a href="#" class="nav-section-link"><i class="icon icon-arrow-prev"></i>Appliances<i class="icon icon-arrow-next"></i></a>

			<ul class="nav-sub-list">

				<li>
					<a class="nav-sub-list-item" href="#">KITCHEN<i class="icon icon-arrow-next"></i></a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#">Refregerators<i class="icon icon-menu-plus"></i><i class="icon icon-menu-minus hide"></i></a>
							<ul class="nav-sub-accordion-ul">
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">Door-In-Door</a></li>
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">French Doors</a></li>
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">Side by Side</a></li>
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">Bottom Freezer</a></li>
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">Top Freezer</a></li>
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">All LG Refrigerators</a></li>
							</ul>
						</li>
						<li><a class="nav-sub-accordion" href="#">Cooking<i class="icon icon-menu-plus"></i><i class="icon icon-menu-minus hide"></i></a>
							<ul class="nav-sub-accordion-ul">
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">Ranges & Ovens</a></li>
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">Wall Ovens</a></li>
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">Cooktops</a></li>
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">Microwave Ovens</a></li>
							</ul>
						</li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="category-mega-link">Dishwashers</a></li>
						<li><a class="nav-sub-accordion" href="#">Kitchen Accessories</a>
							<ul class="nav-sub-accordion-ul">
								<li><a class="nav-accordion-item" href="#" data-sc-item="sub-category-link">Refrigerator Filters</a></li>
							</ul>
						</li>
					</ul>
				</li>

				<li><a class="nav-sub-list-item" href="#">LAUNDRY<i class="icon icon-arrow-next"></i></a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#">Kitchen Accessories<i class="icon icon-menu-plus"></i><i class="icon icon-menu-minus hide"></i></a>
							<ul class="nav-sub-accordion-ul">
								<li><a class="nav-accordion-item" href="#">Front Load Washers</a></li>
								<li><a class="nav-accordion-item" href="#">Top Load Washers</a></li>
								<li><a class="nav-accordion-item" href="#">TurboWash Washers</a></li>
								<li><a class="nav-accordion-item" href="#">Dryers</a></li>
								<li><a class="nav-accordion-item" href="#">Washer/Dryer Combos</a></li>
								<li><a class="nav-accordion-item" href="#">All LG Washers</a></li>
							</ul>
						</li>
						<li><a class="nav-sub-accordion" href="#">Dryers</a></li>
						<li><a class="nav-sub-accordion" href="#">Washer/Dryer Combos</a></li>
						<li><a class="nav-sub-accordion" href="#">Laundry Accessories</a></li>
					</ul>
				</li>
				<li><a class="nav-sub-list-item" href="#">REST OF HOME<i class="icon icon-arrow-next"></i></a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#">Air Conditioners</a></li>
						<li><a class="nav-sub-accordion" href="#">Dehumidifiers</a></li>
						<li><a class="nav-sub-accordion" href="#">Vaccums </a></li>
						<li><a class="nav-sub-accordion" href="#">LED Lights</a></li>
						<li><a class="nav-sub-accordion" href="#">Rest of Home Accessories</a></li>
					</ul>
				</li>
				<li><a class="nav-sub-list-item" href="#">More About Home Appliances <i class="icon icon-arrow-next"></i></a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#">Find the Right Refridgerator</a></li>
						<li><a class="nav-sub-accordion" href="#">Find the Right Washer</a></li>
						<li><a class="nav-sub-accordion" href="#">Experience Smart Thinq</a></li>
						<li><a class="nav-sub-accordion" href="#">Experience LG Studio</a></li>
						<li><a class="nav-sub-accordion" href="#">Auxiliary link #5</a></li>
						<li><a class="nav-sub-accordion" href="#">Auxiliary link #6</a></li>
						<li><a class="nav-sub-accordion" href="#">Promotion Support</a></li>
						<li><a class="nav-sub-accordion" href="#">Promotions</a></li>
					</ul>
				</li>

			</ul>
		</section>
		<section class="mobile-nav-section">

			<a href="#" class="nav-section-link"><i class="icon icon-arrow-prev"></i>Computer<i class="icon icon-arrow-next"></i></a>

			<ul class="nav-sub-list">

				<li><a class="nav-sub-list-item" href="#">Monitors<i class="icon icon-arrow-next"></i></a>
					 <ul class="hide">
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">21:9 UltraWide Monitors</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Gaming Monitors</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">ISP Monitors</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">LED Monitors</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">All-in-One Chromebase</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">All LG Monitors</a></li>
					</ul>
				</li>
				<li><a class="nav-sub-list-item" href="#">Data Storage<i class="icon icon-arrow-next"></i></a>
					 <ul class="hide">
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Blu-ray Burners and Drives</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">DVD Burners and Drives</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">All LG Data Storage</a></li>
					</ul>
				</li>
				<li><a class="nav-sub-list-item" href="#">More About Computer Products<i class="icon icon-arrow-next"></i></a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Find the Right Monitor</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">What is ISP Monitors?</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Auxiliary link #4</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Auxiliary link #5</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Auxiliary link #6</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Promotion Support</a></li>
						<li><a class="nav-sub-accordion" href="#" data-sc-item="sub-category-link">Promotions</a></li>
					</ul>
				</li>
			</ul>
		</section>
		<section class="mobile-nav-section">
			<a href="#" class="nav-section-link"><i class="icon icon-arrow-prev"></i>Inovation<i class="icon icon-arrow-next"></i></a>
			<ul class="nav-sub-list">
				<li><a class="nav-sub-list-item" href="#">Making Life Better<i class="icon icon-arrow-next"></i></a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#">In the Kitchen</a></li>
						<li><a class="nav-sub-accordion" href="#">In the Laundry Room</a></li>
						<li><a class="nav-sub-accordion" href="#">Family Entertainment</a></li>
						<li><a class="nav-sub-accordion" href="#">Mobile Lifestyle</a></li>
						<li><a class="nav-sub-accordion" href="#">Computing</a></li>
					</ul>
				</li>
				<li><a class="nav-sub-list-item" href="#">Technologies<i class="icon icon-arrow-next"></i></a></li>
				<li><a class="nav-sub-list-item" href="#">The LG Labs<i class="icon icon-arrow-next"></i></a></li>
				<li><a class="nav-sub-list-item" href="#">Awards<i class="icon icon-arrow-next"></i></a></li>
				<li><a class="nav-sub-list-item" href="#">Patents<i class="icon icon-arrow-next"></i></a></li>
				<li><a class="nav-sub-list-item" href="#">What's Next<i class="icon icon-arrow-next"></i></a></li>
				<li><a class="nav-sub-list-item" href="#">Experience LG Innov<i class="icon icon-arrow-next"></i>ation</a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#">Events</a></li>
						<li><a class="nav-sub-accordion" href="#">Showrooms</a></li>
						<li><a class="nav-sub-accordion" href="#">Press/Media</a></li>
					</ul>
				</li>
			</ul>
		</section>
		<section class="mobile-nav-section">
			<a href="#" class="nav-section-link"><i class="icon icon-arrow-prev"></i>Support<i class="icon icon-arrow-next"></i></a>
			<ul class="nav-sub-list">
				<li><a class="nav-sub-list-item" href="#">Register a Product<i class="icon icon-arrow-next"></i></a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#">Benefits</a></li>
					</ul>
				</li>
				<li><a class="nav-sub-list-item" href="#">Downloads and Manuals<i class="icon icon-arrow-next"></i></a></li>
				<li><a class="nav-sub-list-item" href="#">Experience LG Innovation<i class="icon icon-arrow-next"></i></a>
					<ul class="hide">
						<li><a class="nav-sub-accordion" href="#">Events</a></li>
						<li><a class="nav-sub-accordion" href="#">Showrooms</a></li>
						<li><a class="nav-sub-accordion" href="#">Press/Media</a></li>
					</ul>
				</li>
			</ul>
		</section>
		<section class="mobile-nav-section">
			<a href="#" class="nav-section-link"><i class="icon icon-arrow-prev"></i>Business<i class="icon icon-arrow-next"></i></a>
		</section>
		<!-- 2015-06-17 로그인시 출력시켜 주세요. -->
		<!-- 2015-08-19  mylg-status 클래스 추가, data-uri에 ajax URI 추가 및 마크업 일부 변경 -->
		<section class="mobile-login-form mylg-status" data-uri="/ajaxData/loginCheck.html">
			<div class="form-wrap">
				<div class="my-info">
					<div class="table-box">
						<div class="icon"><i class="icon icon-login-header"></i></div>
						<div class="welcome">
							<!-- 2015-08-20 a 태그 추가 -->
							<a href="#">
								<p>Welcome</p>
								<p class="my-id"><span class="first-name"></span> <span class="last-name"></span></p>
							</a>
						</div>
					</div>
				</div>
				<a href="#" class="btn logout">Sign out</a>
			</div>
		</section>
	</div>
</nav>

