<div class="browser-alert-wrap hide">
	<div class="browser-alert-layer">
		<div class="layer-header">
			<div class="logo"><img class="logo web" alt="LG" src="/lg4-common/img/global/logo-light-59.jpg"></div>
			<p>To properly experience our LG.com website, you will need to use an alternate browser or upgrade to a newer version of internet Explorer (IE9 or greater).</p>
		</div>
		<div class="layer-body">
			<p>The LG.com website utilizes responsive design to provide convenient experience that conforms to your devices screen size. In order to get the best possible experience our LG.COM website please follow below instructions.</p>
			<p>If you’re using Internet Explorer 8 or earlier, you will need to <strong>use an alternate browser</strong> such as Firefox or Chrome or <strong>upgrade to a newer version of internet Explorer (IE9 or greater)</strong>.</p>
			<p>If you’re using Internet Explorer 9 and higher, <strong>turn off your Internet Explorer browser’s “Compatibility View settings”</strong> by following steps below:</p>
			<ul class="type-hyphen">
				<li>Right click at the top of your browser and make sure the “Menu Bar” option is selected</li>
				<li>Select “Tools” from the menu bar and then select “Compatibility View settings”</li>
				<li>In the pop-up menu uncheck all three boxes and click “Close”</li>
				<li>Your browser window will automatically refresh and you’ll be ready to go</li>
			</ul>
		</div>
		<a href="#" class="close-btn"><img src="/lg4-common/img/common/layer_close_for_ie7.png" alt=""></a>
	</div>
</div>