<div id="app-my-lg">
	<div class="container">
		<div class="mylg-login-nav active">
			<!-- edit Breadcrumb 2015-08-18 -->
			<ol itemscope itemtype="http://schema.org/BreadcrumbList">
				<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
					<a itemprop="item" href="#"><span itemprop="name">LG TV/Audio/Video</span></a>
					<meta itemprop="position" content="1" /> > 
				</li>
				<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
					<a itemprop="item" href="#"><span itemprop="name">Home Entertainment</span></a>
					<meta itemprop="position" content="2" /> > 
				</li>
				<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
					<a itemprop="item" href="#"><span itemprop="name">Audio / Video</span></a>
					<meta itemprop="position" content="3" /> > 
				</li>
				<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
					<a itemprop="item" href="#"><span itemprop="name">All LG Home Audio/Video</span></a>
					<meta itemprop="position" content="4" /> > 
				</li>
				<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
					<span itemprop="item"><span itemprop="name">65UF7700</span></span>
					<meta itemprop="position" content="5" /> 
				</li>
			</ol>

			<!--
			<p itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
				<a href="#" itemprop="url"><span itemprop="title">LG TV/Audio/Video</span></a> > 
				<span itemprop="child" itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
					<a href="#" itemprop="url"><span itemprop="title">Home Entertainment</span></a> > 
					<span>
						<a href="#" itemprop="url"><span itemprop="title">Audio / Video</span></a> > 
						<span>
							<a href="#" itemprop="url"><span itemprop="title">All LG Home Audio/Video</span></a> > 
							<span>
								<span itemprop="title">65UF7700</span>
							</span>
						</span>
					</span>
				</span>
			</p>
			-->
			<!--
				TV/Audio/Video
				Home Entertainment
				Audio / Video
				All LG Home Audio/Video
				55” Class (54.6” Diagonal) 1080P Smart 3D Curved OLED TV
			-->
			<ul>
				<!-- 2015-05-15 my lg login 과 cart 위치 변경 -->
				<li>
					<!-- 2015-08-13 SIGN IN 영역 수정됨 -->
					<div class="mylg-status" data-uri="/ajaxData/loginCheck.html">
						<div class="flag-false">
							<a class="mylg-login-btn" href="#"><i class="icon icon-login-header"></i><span>MyLG Sign In</span></a><!-- 2015-08-26 add MyLG text -->
						</div>
						<div class="flag-true">
							<span class="my-info-username"><i class="icon icon-login-header"></i>Welcome <span class="first-name"></span> <span class="last-name"></span></span><a class="mylg-login-btn" href="#">Sign out</a>
						</div>
					</div>
				</li>
				<li><a href="https://usstore.lg.com/store/lgus/en_US/cart/" id="eco-mini-basket" data-apiURL="//usstore.lg.com/store?Locale=en_US&SiteID=lgus"><i class="icon icon-shopping-cart-header"></i><span><span>0</span> Items</span></a></li><!-- 2015-08-05 숫자에 괄호 제거 -->
			</ul>
		</div>
	</div>
</div>